In [29]:
import pandas as pd
caitlin_df = pd.read_excel('AMP_Database_OzON.xlsx')
df = pd.read_csv('OzON_Possible_Database_0.csv')

In [30]:
caitlin_df

,Compound Group,Compound Name,ISTD?,Parent Ion,MS1 Res,Product Ion,MS2 Res,Dwell,Fragmentor,Collision Energy,Cell Accelerator Voltage,Polarity,Class
0,NaN,24:0,False,535.4,Unit,183,Unit,25,100,0,2,Negative,FA
1,NaN,24:1,False,533.4,Unit,183,Unit,25,100,0,2,Negative,FA
2,NaN,23:0 / 24:1n-2,False,521.4,Unit,183,Unit,25,100,0,2,Negative,FA
3,NaN,22:0 / 23:1n-2 / 24:1n-3,False,507.4,Unit,183,Unit,25,100,0,2,Negative,FA
4,NaN,22:1,False,505.4,Unit,183,Unit,25,100,0,2,Negative,FA
5,NaN,22:2,False,503.4,Unit,183,Unit,25,100,0,2,Negative,FA
6,NaN,22:6,False,495.4,Unit,183,Unit,25,100,0,2,Negative,FA
7,NaN,21:0 / 22:1n-2 / 23:1n-3 / 24:1n-4,False,493.4,Unit,183,Unit,25,100,0,2,Negative,FA
8,NaN,20:0 / 21:1n-2 / 22:1n-3 / 23:1n-4 / 24:1n-5,False,479.4,Unit,183,Unit,25,100,0,2,Negative,FA
9,NaN,20:1,False,477.4,Unit,183,Unit,25,100,0,2,Negative,FA
10,NaN,20:2,False,475.4,Unit,183,Unit,25,100,0,2,Negative,FA
11,NaN,20:3,False,473.4,Unit,183,Unit,25,100,0,2,Negative,FA
12,NaN,20:4,False,471.4,Unit,183,Unit,25,100,0,2,Negative,FA
13,NaN,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3)/20:5",False,469.4,Unit,183,Unit,25,100,0,2,Negative,FA
14,NaN,20:1n-2 / 21:1n-3 / 22:1n-4 / 23:1n-5 / 24:1n-6,False,465.3,Unit,183,Unit,25,100,0,2,Negative,FA
15,NaN,18:0 / 20:1n-3 / 21:1 n-4 / 19:1n-2 / 21:1n-4 ...,False,451.4,Unit,183,Unit,25,100,0,2,Negative,FA
16,NaN,18:1,False,449.4,Unit,183,Unit,25,100,0,2,Negative,FA
17,NaN,"18:2 / 20:3 (11Z,14Z,17Z)n-3",False,447.4,Unit,183,Unit,25,100,0,2,Negative,FA
18,NaN,18:3,False,445.4,Unit,183,Unit,25,100,0,2,Negative,FA
19,NaN,"20:5 (5Z,8Z,11Z,14Z,17Z)n-3",False,443.3,Unit,183,Unit,25,100,0,2,Negative,FA
20,NaN,17:0 / 19:1n-3 / 20:1n-4 / 21:1n-5 / 22:1n-6 /...,False,437.4,Unit,183,Unit,25,100,0,2,Negative,FA
21,NaN,"17:1 / 22:2 (13Z,16Z)n-6",False,435.4,Unit,183,Unit,25,100,0,2,Negative,FA
22,NaN,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6",False,429.2,Unit,183,Unit,25,100,0,2,Negative,FA
23,NaN,d2-16:0,False,425.4,Unit,183,Unit,25,100,0,2,Negative,FA
24,NaN,16:0 / 24:1 (15Z)n-9 / 18:1n-3 / 17:1n-2 / 19:...,False,423.3,Unit,183,Unit,25,100,0,2,Negative,FA
25,NaN,16:1,False,421.4,Unit,183,Unit,25,100,0,2,Negative,FA
26,NaN,"18:3 (9Z,12Z,15Z))n-3",False,419.3,Unit,183,Unit,25,100,0,2,Negative,FA
27,NaN,15:0 / 17:1n-3 / 18:1n-4 / 16:1n-2 / 19:1n-5 /...,False,409.3,Unit,183,Unit,25,100,0,2,Negative,FA
28,NaN,"20:2 (11Z,14Z)n-6 / 20:3 (11Z,14Z,17Z)n-3,n-6 ...",False,407.3,Unit,183,Unit,25,100,0,2,Negative,FA
29,NaN,"20:3 (8Z,11Z,14Z)n-6",False,405.2,Unit,183,Unit,25,100,0,2,Negative,FA
30,NaN,"20:4 (5Z,8Z,11Z,14Z)n-6 / 20:5 (5Z,8Z,11Z,14Z,...",False,403.2,Unit,183,Unit,25,100,0,2,Negative,FA
31,NaN,"14:0 / 22:2 (13Z,16Z)n-6,n-9 / 22:1 (13Z)n-9 /...",False,395.3,Unit,183,Unit,25,100,0,2,Negative,FA
32,NaN,14:1(9Z),False,393.4,Unit,183,Unit,25,100,0,2,Negative,FA
33,NaN,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6,n-9",False,389.3,Unit,183,Unit,25,100,0,2,Negative,FA
34,NaN,13:0 / 14:1n-2 / 15:1n-3 / 16:1n-4 / 17:1n-5 /...,False,381.3,Unit,183,Unit,25,100,0,2,Negative,FA
35,NaN,"18:2 (9Z,12Z)n-6 / 18:3 (9Z,12Z,15Z))n-3.n-6",False,379.3,Unit,183,Unit,25,100,0,2,Negative,FA
36,NaN,"18:3 (6Z,9Z,12Z))n-6",False,377.2,Unit,183,Unit,25,100,0,2,Negative,FA
37,NaN,"12:0 / 20:2 (11Z,14Z)n-6,n-9 / 20:3 (11Z,14Z,1...",False,367.3,Unit,183,Unit,25,100,0,2,Negative,FA
38,NaN,"20:3 (8Z,11Z,14Z)n-6,n-9",False,365.2,Unit,183,Unit,25,100,0,2,Negative,FA
39,NaN,"20:4 (5Z,8Z,11Z,14Z)n-6,n-9 / 20:5 (5Z,8Z,11Z,...",False,363.3,Unit,183,Unit,25,100,0,2,Negative,FA
40,NaN,11:0 / 15:1 (10Z)n-5 / 17:1 (10Z)n-7 / 12:1n-2...,False,353.3,Unit,183,Unit,25,100,0,2,Negative,FA
41,NaN,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6,n-9,n-12",False,349.2,Unit,183,Unit,25,100,0,2,Negative,FA
42,NaN,"10:0 / 18:2 (9Z,12Z)n-6,n-9 / 14:1 (9Z)n-5 / 1...",False,339.3,Unit,183,Unit,25,100,0,2,Negative,FA
43,NaN,"18:3 (6Z,9Z,12Z))n-6,n-9",False,337.2,Unit,183,Unit,25,100,0,2,Negative,FA
44,NaN,"20:3 (8Z,11Z,14Z)n-6,n-9,n-12 / 12:1n-4 / 13:1...",False,325.2,Unit,183,Unit,25,100,0,2,Negative,FA
45,NaN,"20:5 (5Z,8Z,11Z,14Z,17Z)n-3,n-6,n-9,n-12 / 20:...",False,323.2,Unit,183,Unit,25,100,0,2,Negative,FA
46,NaN,8:0 / 12:1n-5 / 13:1n-6 / 14:1n-7 / 15:1n-8 / ...,False,311.3,Unit,183,Unit,25,100,0,2,Negative,FA
47,NaN,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6,n-9,n-12,n-15",False,309.1,Unit,183,Unit,25,100,0,2,Negative,FA
48,NaN,"18:3 (6Z,9Z,12Z))n-6,n-9,n-12 / 12:1n-6 / 13:1...",False,297.2,Unit,183,Unit,25,100,0,2,Negative,FA
49,NaN,"6:0 / 20:5 (5Z,8Z,11Z,14Z,17Z)n-3,n-6,n-9,n-12...",False,283.2,Unit,183,Unit,25,100,0,2,Negative,FA
50,NaN,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6,n-9,n-12,n...",False,269.1,Unit,183,Unit,25,100,0,2,Negative,FA
51,NaN,4:0 / 12:1n-9 / 13:1n-10 / 14:1n-11 / 15:1n-12...,False,255.2,Unit,183,Unit,25,100,0,2,Negative,FA
52,NaN,12:1n-10 / 13:1n-11 / 14:1n-12 / 15:1n-13 / 16...,False,241.1,Unit,183,Unit,25,100,0,2,Negative,FA
53,NaN,12:1n-11 / 13:1n-12 / 14:1n-13 / 15:1n-14 / 16...,False,227.1,Unit,183,Unit,25,100,0,2,Negative,FA
54,NaN,dummy,False,533.5,Unit,183,Unit,25,100,0,2,Negative,FA

In [31]:
df

,Lipid,Parent_Ion,Product_Ion,Species,Class,DB Location,FA mass,[FA+AMP]+
0,FA(5:0),269.3,183.0,5:0,FA,NaN,102.2,281.3
1,FA(6:0),283.3,183.0,6:0,FA,NaN,116.2,295.3
2,FA(6:1)_<>_n-2,269.2,183.0,6:1,FA,<>,114.1,281.2
3,FA(6:1)_<>_n-3,255.2,183.0,6:1,FA,<>,114.1,281.2
4,FA(6:1)_<>_n-4,241.2,183.0,6:1,FA,<>,114.1,281.2
...,...,...,...,...,...,...,...,...
6531,FA(30:6)_<BBFFF>_n-26,265.5,183.0,30:6,FA,<BBFFF>,440.4,607.5
6532,FA(30:6)_<FFFFF>_n-27,255.5,183.0,30:6,FA,<FFFFF>,440.4,607.5
6533,FA(30:6)_<BFFFF>_n-27,253.5,183.0,30:6,FA,<BFFFF>,440.4,607.5
6534,FA(30:6)_<FFFFF>_n-28,241.5,183.0,30:6,FA,<FFFFF>,440.4,607.5
6535,FA(d2-16:0),425.4,183.0,d2-16:0,FA,NaN,258.3,437.4

# compare Parent Ion columns

In [32]:

# Align column names for comparison
df_column = df["Parent_Ion"]
caitlin_column = caitlin_df["Parent Ion"]

# 1. Elements in both
common_elements = set(df_column).intersection(caitlin_column)
print("Common elements between 'Parent_Ion' and 'Parent Ion':")
print(common_elements)

# 2. Elements only in df
unique_to_df = set(df_column) - set(caitlin_column)
print("\nElements unique to 'Parent_Ion' in df:")
print(unique_to_df)

# 3. Elements only in caitlin_df
unique_to_caitlin_df = set(caitlin_column) - set(df_column)
print("\nElements unique to 'Parent Ion' in caitlin_df:")
print(unique_to_caitlin_df)

# 4. All elements combined
all_elements = set(df_column).union(caitlin_column)
print("\nAll elements from both columns:")
print(all_elements)

Common elements between 'Parent_Ion' and 'Parent Ion':
{389.3, 521.4, 393.4, 395.3, 533.4, 533.5, 535.4, 407.3, 409.3, 283.2, 419.3, 421.4, 423.3, 425.4, 297.2, 435.4, 437.4, 311.3, 443.3, 445.4, 447.4, 449.4, 451.4, 323.2, 325.2, 465.3, 337.2, 339.3, 469.4, 471.4, 473.4, 475.4, 477.4, 349.2, 479.4, 353.3, 363.3, 493.4, 365.2, 367.3, 379.3, 503.4, 505.4, 507.4, 381.3, 255.2}

Elements unique to 'Parent_Ion' in df:
{295.4, 305.5, 419.4, 423.4, 423.5, 289.5, 435.5, 437.5, 301.4, 291.5, 303.4, 293.5, 449.5, 451.5, 241.2, 241.29999999999995, 241.4, 241.5, 303.5, 305.4, 253.29999999999995, 253.2, 255.29999999999995, 255.4, 253.4, 255.5, 253.5, 295.5, 265.2, 265.29999999999995, 267.2, 267.29999999999995, 269.2, 269.3, 269.29999999999995, 269.4, 267.4, 265.4, 269.5, 267.5, 277.2, 277.29999999999995, 279.2, 279.29999999999995, 281.2, 281.29999999999995, 283.3, 283.29999999999995, 283.4, 281.4, 279.4, 289.2, 289.29999999999995, 291.2, 291.29999999999995, 293.2, 293.29999999999995, 295.2, 295.29999999999995, 297.3, 297.29999999999995, 297.4, 301.2, 301.29999999999995, 303.2, 303.29999999999995, 305.2, 305.29999999999995, 307.4, 307.2, 309.4, 307.29999999999995, 311.5, 309.2, 309.29999999999995, 315.4, 311.2, 317.4, 311.29999999999995, 319.4, 311.4, 321.4, 315.2, 323.4, 315.29999999999995, 325.5, 317.2, 319.2, 319.29999999999995, 329.4, 321.2, 331.4, 333.4, 325.3, 335.4, 329.2, 337.4, 329.29999999999995, 339.5, 331.2, 333.2, 333.29999999999995, 343.4, 335.2, 345.4, 347.4, 349.4, 343.2, 351.4, 343.29999999999995, 353.5, 345.2, 347.2, 347.29999999999995, 357.4, 359.4, 351.2, 361.4, 357.2, 357.29999999999995, 359.2, 359.29999999999995, 367.5, 361.2, 361.3, 363.2, 365.3, 367.2, 367.4, 371.3, 373.3, 375.3, 375.4, 377.3, 377.4, 379.4, 381.4, 381.5, 385.3, 385.4, 387.3, 387.4, 389.4, 391.3, 391.4, 393.3, 395.4, 395.5, 399.3, 399.4, 401.3, 401.4, 403.3, 403.4, 407.5, 405.3, 405.4, 407.4, 413.5, 409.4, 415.5, 409.5, 417.5, 413.3, 419.5, 413.4, 421.5, 415.3, 415.4, 417.3, 417.4, 427.5, 429.5, 421.3, 431.5, 433.5, 427.3, 427.4, 429.3, 429.4, 431.3, 431.4, 433.3, 441.5, 433.4, 443.5, 435.3, 445.5, 437.3, 447.5, 441.4, 441.3, 443.4, 445.3, 447.3, 455.5, 457.5, 449.3, 459.5, 451.3, 455.3, 455.4, 457.3, 457.4, 459.3, 459.4, 461.3, 461.4, 463.3, 463.4, 465.4, 465.5, 471.5, 473.5, 475.5, 477.5, 479.3, 479.5, 483.4, 483.5, 485.4, 485.5, 487.4, 487.5, 489.4, 489.5, 491.4, 491.5, 493.3, 493.5, 497.4, 497.5, 499.4, 499.5, 501.4, 501.5, 503.5, 505.5, 507.5, 507.3, 511.4, 511.5, 513.4, 513.5, 515.4, 515.5, 517.4, 517.5, 519.4, 519.5, 521.3, 521.5, 525.4, 525.5, 527.4, 527.5, 529.4, 529.5, 531.4, 531.5, 535.3, 535.5, 297.5, 539.4, 539.5, 541.4, 541.5, 543.4, 543.5, 545.4, 545.5, 547.4, 547.5, 549.3, 549.4, 549.5, 553.4, 553.5, 555.4, 555.5, 557.4, 557.5, 559.4, 559.5, 561.4, 561.5, 563.3, 563.4, 563.5, 307.5, 567.5, 315.5, 569.5, 571.5, 277.4, 573.5, 317.29999999999995, 575.5, 317.5, 577.3, 577.5, 581.5, 319.5, 583.5, 585.5, 587.5, 265.5, 589.5, 591.3, 591.5, 321.29999999999995, 321.5, 595.5, 597.5, 599.5, 601.5, 323.29999999999995, 603.5, 323.5, 605.3, 605.5, 309.5, 325.29999999999995, 325.4, 619.3, 329.5, 469.5, 331.29999999999995, 331.5, 333.5, 461.5, 335.29999999999995, 335.5, 337.29999999999995, 337.5, 339.2, 339.29999999999995, 339.4, 343.5, 345.29999999999995, 345.5, 347.5, 349.29999999999995, 349.5, 351.29999999999995, 351.5, 353.2, 353.29999999999995, 353.4, 357.5, 359.5, 361.5, 363.4, 363.5, 365.4, 365.5, 277.5, 371.4, 371.5, 373.4, 373.5, 375.5, 377.5, 289.4, 279.5, 379.5, 463.5, 385.5, 387.5, 291.4, 281.5, 389.5, 391.5, 393.5, 293.4, 283.5, 399.5, 401.5, 403.5, 405.5, 301.5}

Elements unique to 'Parent Ion' in caitlin_df:
{227.1, 269.1, 429.2, 495.4, 241.1, 403.2, 309.1, 405.2, 377.2}

All elements from both columns:
{295.4, 305.5, 419.4, 421.4, 423.4, 423.5, 289.5, 429.2, 435.4, 435.5, 437.4, 437.5, 301.4, 291.5, 303.4, 293.5, 449.4, 449.5, 451.4, 451.5, 227.1, 241.2, 241.29999999999995, 241.4, 241.5, 303.5, 241.1, 305.4, 253.29999999999995, 253.2, 255.29999999999995, 255.2, 255.4, 253.4, 255.5, 253.5, 295.5, 265.2, 265.29999999999995, 267.2, 267.29999999999995, 269.2, 269.3, 269.29999999999995, 269.4, 267.4, 265.4, 269.5, 267.5, 277.2, 277.29999999999995, 279.2, 279.29999999999995, 281.2, 281.29999999999995, 283.2, 283.3, 283.29999999999995, 283.4, 281.4, 279.4, 289.2, 289.29999999999995, 291.2, 291.29999999999995, 293.2, 293.29999999999995, 295.2, 295.29999999999995, 297.3, 297.2, 297.29999999999995, 297.4, 301.2, 301.29999999999995, 303.2, 303.29999999999995, 305.2, 305.29999999999995, 307.4, 307.2, 309.4, 307.29999999999995, 311.5, 309.2, 309.29999999999995, 311.3, 315.4, 311.2, 317.4, 311.29999999999995, 319.4, 311.4, 321.4, 315.2, 323.4, 315.29999999999995, 325.5, 317.2, 319.2, 319.29999999999995, 329.4, 321.2, 331.4, 323.2, 333.4, 325.3, 335.4, 329.2, 337.4, 329.29999999999995, 339.5, 331.2, 333.2, 333.29999999999995, 343.4, 335.2, 345.4, 337.2, 347.4, 339.3, 349.4, 343.2, 351.4, 343.29999999999995, 353.5, 345.2, 347.2, 347.29999999999995, 357.4, 349.2, 359.4, 351.2, 361.4, 353.3, 357.2, 357.29999999999995, 359.2, 359.29999999999995, 367.5, 361.2, 361.3, 363.2, 363.3, 365.2, 365.3, 367.3, 367.2, 367.4, 371.3, 373.3, 375.3, 375.4, 377.3, 377.4, 379.3, 379.4, 381.3, 381.4, 381.5, 385.3, 385.4, 387.3, 387.4, 389.3, 389.4, 391.3, 391.4, 393.3, 393.4, 395.3, 395.4, 395.5, 399.3, 399.4, 401.3, 401.4, 403.3, 403.4, 407.5, 405.3, 405.4, 407.3, 407.4, 409.3, 413.5, 409.4, 415.5, 409.5, 417.5, 413.3, 419.5, 413.4, 421.5, 415.3, 415.4, 417.3, 425.4, 417.4, 427.5, 419.3, 429.5, 421.3, 431.5, 423.3, 433.5, 427.3, 427.4, 429.3, 429.4, 431.3, 431.4, 433.3, 441.5, 433.4, 443.5, 435.3, 445.5, 437.3, 447.5, 441.4, 441.3, 443.3, 443.4, 445.3, 445.4, 447.3, 455.5, 447.4, 457.5, 449.3, 459.5, 451.3, 455.3, 455.4, 457.3, 457.4, 459.3, 459.4, 461.3, 461.4, 463.3, 463.4, 465.3, 465.4, 465.5, 469.4, 471.4, 471.5, 473.4, 473.5, 475.4, 475.5, 477.4, 477.5, 479.3, 479.4, 479.5, 483.4, 483.5, 485.4, 485.5, 487.4, 487.5, 489.4, 489.5, 491.4, 491.5, 493.3, 493.4, 493.5, 497.4, 497.5, 499.4, 499.5, 501.4, 501.5, 503.4, 503.5, 505.4, 505.5, 507.5, 507.4, 507.3, 511.4, 511.5, 513.4, 513.5, 515.4, 515.5, 517.4, 517.5, 519.4, 519.5, 521.3, 521.4, 521.5, 525.4, 525.5, 527.4, 527.5, 529.4, 529.5, 531.4, 531.5, 533.4, 533.5, 535.3, 535.4, 535.5, 297.5, 539.4, 539.5, 541.4, 541.5, 543.4, 543.5, 545.4, 545.5, 547.4, 547.5, 549.3, 549.4, 549.5, 553.4, 553.5, 555.4, 555.5, 557.4, 557.5, 559.4, 559.5, 561.4, 561.5, 563.3, 563.4, 563.5, 307.5, 567.5, 315.5, 569.5, 571.5, 277.4, 573.5, 317.29999999999995, 575.5, 317.5, 577.3, 577.5, 581.5, 319.5, 583.5, 585.5, 587.5, 265.5, 589.5, 591.3, 591.5, 321.29999999999995, 321.5, 595.5, 597.5, 599.5, 601.5, 323.29999999999995, 603.5, 323.5, 605.3, 605.5, 309.5, 325.2, 325.29999999999995, 325.4, 619.3, 329.5, 469.5, 331.29999999999995, 331.5, 333.5, 461.5, 335.29999999999995, 335.5, 337.29999999999995, 337.5, 339.2, 339.29999999999995, 339.4, 343.5, 345.29999999999995, 345.5, 347.5, 349.29999999999995, 349.5, 351.29999999999995, 351.5, 353.2, 353.29999999999995, 353.4, 357.5, 359.5, 361.5, 363.4, 363.5, 365.4, 365.5, 277.5, 371.4, 371.5, 373.4, 373.5, 375.5, 309.1, 377.5, 377.2, 289.4, 279.5, 379.5, 269.1, 463.5, 385.5, 387.5, 291.4, 281.5, 389.5, 495.4, 391.5, 393.5, 293.4, 283.5, 399.5, 401.5, 403.5, 403.2, 405.5, 405.2, 301.5}

In [33]:
# Assuming values in df and caitlin_df are numeric for comparison with a tolerance

# Function to compare with tolerance
def compare_with_tolerance(values_df, values_caitlin, tolerance=0.3):
    matched = set()
    unique_to_df = set()
    unique_to_caitlin = set(values_caitlin)

    for val in values_df:
        matched_within_tolerance = False
        for comp_val in values_caitlin:
            if abs(val - comp_val) <= tolerance:
                matched.add(comp_val)
                matched_within_tolerance = True
        if not matched_within_tolerance:
            unique_to_df.add(val)
    unique_to_caitlin -= matched
    return matched, unique_to_df, unique_to_caitlin

In [40]:
matched_values, unique_to_df_values, unique_to_caitlin_values = compare_with_tolerance(
    df_column, caitlin_column, tolerance=0.5
)

In [41]:
# Print results with tolerance
print("Matched values with a tolerance of ±0.3:")
print(matched_values)

print("\nValues unique to df considering tolerance:")
print(unique_to_df_values)

print("\nValues unique to caitlin_df considering tolerance:")
print(unique_to_caitlin_values)

Matched values with a tolerance of ±0.3:
{389.3, 393.4, 521.4, 395.3, 269.1, 403.2, 405.2, 533.4, 407.3, 535.4, 409.3, 533.5, 283.2, 419.3, 421.4, 423.3, 297.2, 425.4, 429.2, 435.4, 309.1, 437.4, 311.3, 443.3, 445.4, 447.4, 449.4, 323.2, 451.4, 325.2, 337.2, 465.3, 339.3, 469.4, 471.4, 473.4, 475.4, 349.2, 477.4, 479.4, 353.3, 503.4, 363.3, 365.2, 493.4, 367.3, 505.4, 241.1, 507.4, 377.2, 379.3, 381.3, 255.2}

Values unique to df considering tolerance:
{513.4, 513.5, 515.4, 515.5, 517.4, 517.5, 519.4, 519.5, 511.5, 525.4, 525.5, 527.4, 527.5, 529.4, 529.5, 531.4, 531.5, 539.4, 539.5, 541.4, 541.5, 543.4, 543.5, 545.4, 545.5, 547.4, 547.5, 549.3, 549.4, 549.5, 553.4, 553.5, 555.4, 555.5, 557.4, 557.5, 559.4, 559.5, 315.4, 561.4, 563.3, 563.4, 563.5, 561.5, 567.5, 315.5, 569.5, 571.5, 317.5, 573.5, 575.5, 577.3, 577.5, 581.5, 583.5, 585.5, 587.5, 589.5, 591.3, 591.5, 595.5, 597.5, 599.5, 601.5, 603.5, 605.3, 605.5, 619.3, 329.4, 329.5, 331.5, 343.4, 343.5, 345.5, 455.5, 457.5, 253.29999999999995, 253.2, 253.4, 253.5, 357.5, 265.2, 265.29999999999995, 267.2, 267.29999999999995, 267.4, 265.4, 267.5, 265.5, 277.2, 277.29999999999995, 279.2, 279.29999999999995, 281.2, 281.29999999999995, 281.4, 279.4, 277.4, 281.5, 279.5, 289.2, 289.29999999999995, 291.2, 291.29999999999995, 293.2, 293.29999999999995, 295.2, 295.29999999999995, 295.4, 293.4, 291.4, 295.5, 301.2, 301.29999999999995, 303.2, 303.29999999999995, 305.2, 305.29999999999995, 307.2, 307.29999999999995, 307.4, 305.4, 303.4, 307.5, 305.5, 315.2, 315.29999999999995, 317.2, 317.29999999999995, 319.2, 319.29999999999995, 321.2, 321.29999999999995, 321.4, 319.4, 317.4, 321.5, 319.5, 329.2, 329.29999999999995, 331.2, 331.29999999999995, 333.2, 333.29999999999995, 335.2, 335.29999999999995, 335.4, 333.4, 331.4, 335.5, 333.5, 343.2, 343.29999999999995, 345.2, 345.29999999999995, 347.2, 347.29999999999995, 347.4, 345.4, 351.2, 351.29999999999995, 351.4, 351.5, 347.5, 357.2, 357.29999999999995, 359.2, 359.29999999999995, 361.2, 361.3, 361.4, 359.4, 357.4, 361.5, 359.5, 277.5, 371.3, 371.4, 373.3, 373.4, 375.3, 375.4, 375.5, 373.5, 371.5, 385.3, 385.4, 387.3, 387.4, 387.5, 385.5, 391.3, 391.4, 391.5, 399.3, 399.4, 401.3, 401.4, 401.5, 399.5, 413.3, 413.4, 415.3, 415.4, 417.3, 417.4, 417.5, 415.5, 413.5, 427.3, 427.4, 427.5, 431.3, 431.4, 433.3, 433.4, 289.4, 433.5, 431.5, 289.5, 441.3, 441.4, 291.5, 441.5, 293.5, 455.3, 455.4, 457.3, 457.4, 459.3, 459.4, 461.3, 461.4, 463.3, 463.4, 463.5, 461.5, 459.5, 483.4, 483.5, 485.4, 485.5, 487.4, 487.5, 489.4, 489.5, 301.4, 491.4, 491.5, 301.5, 497.4, 497.5, 499.4, 499.5, 501.4, 501.5, 303.5, 511.4}

Values unique to caitlin_df considering tolerance:
{227.1, 495.4}

In [42]:
comparison_results = pd.DataFrame({
    "Matched Values (±0.3)": pd.Series(list(matched_values)),
    "Unique to sanjay_df (±0.3)": pd.Series(list(unique_to_df_values)),
    "Unique to caitlin_df (±0.3)": pd.Series(list(unique_to_caitlin_values))
})

In [43]:

comparison_results.to_excel('results/comparison_ParentIons.xlsx', index=False)

pd.set_option('display.max_rows', None)
# # (Optional) Reset display options to default
# pd.reset_option('display.max_rows')
#print len of values in column 2 of df
print(len(df_column))

# display all results
comparison_results.head(None)

6536

,Matched Values (±0.3),Unique to sanjay_df (±0.3),Unique to caitlin_df (±0.3)
0,389.3,513.4,227.1
1,393.4,513.5,495.4
2,521.4,515.4,NaN
3,395.3,515.5,NaN
4,269.1,517.4,NaN
5,403.2,517.5,NaN
6,405.2,519.4,NaN
7,533.4,519.5,NaN
8,407.3,511.5,NaN
9,535.4,525.4,NaN
10,409.3,525.5,NaN
11,533.5,527.4,NaN
12,283.2,527.5,NaN
13,419.3,529.4,NaN
14,421.4,529.5,NaN
15,423.3,531.4,NaN
16,297.2,531.5,NaN
17,425.4,539.4,NaN
18,429.2,539.5,NaN
19,435.4,541.4,NaN
20,309.1,541.5,NaN
21,437.4,543.4,NaN
22,311.3,543.5,NaN
23,443.3,545.4,NaN
24,445.4,545.5,NaN
25,447.4,547.4,NaN
26,449.4,547.5,NaN
27,323.2,549.3,NaN
28,451.4,549.4,NaN
29,325.2,549.5,NaN
30,337.2,553.4,NaN
31,465.3,553.5,NaN
32,339.3,555.4,NaN
33,469.4,555.5,NaN
34,471.4,557.4,NaN
35,473.4,557.5,NaN
36,475.4,559.4,NaN
37,349.2,559.5,NaN
38,477.4,315.4,NaN
39,479.4,561.4,NaN
40,353.3,563.3,NaN
41,503.4,563.4,NaN
42,363.3,563.5,NaN
43,365.2,561.5,NaN
44,493.4,567.5,NaN
45,367.3,315.5,NaN
46,505.4,569.5,NaN
47,241.1,571.5,NaN
48,507.4,317.5,NaN
49,377.2,573.5,NaN
50,379.3,575.5,NaN
51,381.3,577.3,NaN
52,255.2,577.5,NaN
53,NaN,581.5,NaN
54,NaN,583.5,NaN
55,NaN,585.5,NaN
56,NaN,587.5,NaN
57,NaN,589.5,NaN
58,NaN,591.3,NaN
59,NaN,591.5,NaN
60,NaN,595.5,NaN
61,NaN,597.5,NaN
62,NaN,599.5,NaN
63,NaN,601.5,NaN
64,NaN,603.5,NaN
65,NaN,605.3,NaN
66,NaN,605.5,NaN
67,NaN,619.3,NaN
68,NaN,329.4,NaN
69,NaN,329.5,NaN
70,NaN,331.5,NaN
71,NaN,343.4,NaN
72,NaN,343.5,NaN
73,NaN,345.5,NaN
74,NaN,455.5,NaN
75,NaN,457.5,NaN
76,NaN,253.3,NaN
77,NaN,253.2,NaN
78,NaN,253.4,NaN
79,NaN,253.5,NaN
80,NaN,357.5,NaN
81,NaN,265.2,NaN
82,NaN,265.3,NaN
83,NaN,267.2,NaN
84,NaN,267.3,NaN
85,NaN,267.4,NaN
86,NaN,265.4,NaN
87,NaN,267.5,NaN
88,NaN,265.5,NaN
89,NaN,277.2,NaN
90,NaN,277.3,NaN
91,NaN,279.2,NaN
92,NaN,279.3,NaN
93,NaN,281.2,NaN
94,NaN,281.3,NaN
95,NaN,281.4,NaN
96,NaN,279.4,NaN
97,NaN,277.4,NaN
98,NaN,281.5,NaN
99,NaN,279.5,NaN
100,NaN,289.2,NaN
101,NaN,289.3,NaN
102,NaN,291.2,NaN
103,NaN,291.3,NaN
104,NaN,293.2,NaN
105,NaN,293.3,NaN
106,NaN,295.2,NaN
107,NaN,295.3,NaN
108,NaN,295.4,NaN
109,NaN,293.4,NaN
110,NaN,291.4,NaN
111,NaN,295.5,NaN
112,NaN,301.2,NaN
113,NaN,301.3,NaN
114,NaN,303.2,NaN
115,NaN,303.3,NaN
116,NaN,305.2,NaN
117,NaN,305.3,NaN
118,NaN,307.2,NaN
119,NaN,307.3,NaN
120,NaN,307.4,NaN
121,NaN,305.4,NaN
122,NaN,303.4,NaN
123,NaN,307.5,NaN
124,NaN,305.5,NaN
125,NaN,315.2,NaN
126,NaN,315.3,NaN
127,NaN,317.2,NaN
128,NaN,317.3,NaN
129,NaN,319.2,NaN
130,NaN,319.3,NaN
131,NaN,321.2,NaN
132,NaN,321.3,NaN
133,NaN,321.4,NaN
134,NaN,319.4,NaN
135,NaN,317.4,NaN
136,NaN,321.5,NaN
137,NaN,319.5,NaN
138,NaN,329.2,NaN
139,NaN,329.3,NaN
140,NaN,331.2,NaN
141,NaN,331.3,NaN
142,NaN,333.2,NaN
143,NaN,333.3,NaN
144,NaN,335.2,NaN
145,NaN,335.3,NaN
146,NaN,335.4,NaN
147,NaN,333.4,NaN
148,NaN,331.4,NaN
149,NaN,335.5,NaN
150,NaN,333.5,NaN
151,NaN,343.2,NaN
152,NaN,343.3,NaN
153,NaN,345.2,NaN
154,NaN,345.3,NaN
155,NaN,347.2,NaN
156,NaN,347.3,NaN
157,NaN,347.4,NaN
158,NaN,345.4,NaN
159,NaN,351.2,NaN
160,NaN,351.3,NaN
161,NaN,351.4,NaN
162,NaN,351.5,NaN
163,NaN,347.5,NaN
164,NaN,357.2,NaN
165,NaN,357.3,NaN
166,NaN,359.2,NaN
167,NaN,359.3,NaN
168,NaN,361.2,NaN
169,NaN,361.3,NaN
170,NaN,361.4,NaN
171,NaN,359.4,NaN
172,NaN,357.4,NaN
173,NaN,361.5,NaN
174,NaN,359.5,NaN
175,NaN,277.5,NaN
176,NaN,371.3,NaN
177,NaN,371.4,NaN
178,NaN,373.3,NaN
179,NaN,373.4,NaN
180,NaN,375.3,NaN
181,NaN,375.4,NaN
182,NaN,375.5,NaN
183,NaN,373.5,NaN
184,NaN,371.5,NaN
185,NaN,385.3,NaN
186,NaN,385.4,NaN
187,NaN,387.3,NaN
188,NaN,387.4,NaN
189,NaN,387.5,NaN
190,NaN,385.5,NaN
191,NaN,391.3,NaN
192,NaN,391.4,NaN
193,NaN,391.5,NaN
194,NaN,399.3,NaN
195,NaN,399.4,NaN
196,NaN,401.3,NaN
197,NaN,401.4,NaN
198,NaN,401.5,NaN
199,NaN,399.5,NaN
200,NaN,413.3,NaN
201,NaN,413.4,NaN
202,NaN,415.3,NaN
203,NaN,415.4,NaN
204,NaN,417.3,NaN
205,NaN,417.4,NaN
206,NaN,417.5,NaN
207,NaN,415.5,NaN
208,NaN,413.5,NaN
209,NaN,427.3,NaN
210,NaN,427.4,NaN
211,NaN,427.5,NaN
212,NaN,431.3,NaN
213,NaN,431.4,NaN
214,NaN,433.3,NaN
215,NaN,433.4,NaN
216,NaN,289.4,NaN
217,NaN,433.5,NaN
218,NaN,431.5,NaN
219,NaN,289.5,NaN
220,NaN,441.3,NaN
221,NaN,441.4,NaN
222,NaN,291.5,NaN
223,NaN,441.5,NaN
224,NaN,293.5,NaN
225,NaN,455.3,NaN
226,NaN,455.4,NaN
227,NaN,457.3,NaN
228,NaN,457.4,NaN
229,NaN,459.3,NaN
230,NaN,459.4,NaN
231,NaN,461.3,NaN
232,NaN,461.4,NaN
233,NaN,463.3,NaN
234,NaN,463.4,NaN
235,NaN,463.5,NaN
236,NaN,461.5,NaN
237,NaN,459.5,NaN
238,NaN,483.4,NaN
239,NaN,483.5,NaN
240,NaN,485.4,NaN
241,NaN,485.5,NaN
242,NaN,487.4,NaN
243,NaN,487.5,NaN
244,NaN,489.4,NaN
245,NaN,489.5,NaN
246,NaN,301.4,NaN
247,NaN,491.4,NaN
248,NaN,491.5,NaN
249,NaN,301.5,NaN
250,NaN,497.4,NaN
251,NaN,497.5,NaN
252,NaN,499.4,NaN
253,NaN,499.5,NaN
254,NaN,501.4,NaN
255,NaN,501.5,NaN
256,NaN,303.5,NaN
257,NaN,511.4,NaN

In [14]:
# Create the two new DataFrames: matched_df and sanjay_unique_df
matched_df = pd.DataFrame()
sanjay_unique_df = pd.DataFrame()

# Iterate through the comparison results for "Matched Values"
for value in comparison_results["Matched Values (±0.3)"].dropna():
    matched_rows = df[abs(df["Parent_Ion"] - value) <= 0.3]
    matched_df = pd.concat([matched_df, matched_rows])

# Iterate through the comparison results for "Unique to sanjay_df"
for value in comparison_results["Unique to sanjay_df (±0.3)"].dropna():
    unique_rows = df[abs(df["Parent_Ion"] - value) <= 0.3]
    sanjay_unique_df = pd.concat([sanjay_unique_df, unique_rows])

In [18]:
#to excel 
matched_df.to_excel('results/matched_ParentIons.xlsx', index=False)
matched_df

,Lipid,Parent_Ion,Product_Ion,Species,Class,DB Location,FA mass,[FA+AMP]+
916,FA(15:4)_<BBB>_n-2,389.3,183.0,15:4,FA,<BBB>,234.2,401.3
954,FA(15:5)_<BBBF>_n-2,389.3,183.0,15:5,FA,<BBBF>,232.2,399.3
1123,FA(16:4)_<BBB>_n-3,389.3,183.0,16:4,FA,<BBB>,248.2,415.3
1165,FA(16:5)_<BBBF>_n-3,389.3,183.0,16:5,FA,<BBBF>,246.2,413.3
1213,FA(16:6)_<BBBFF>_n-3,389.3,183.0,16:6,FA,<BBBFF>,244.2,411.3
...,...,...,...,...,...,...,...,...
4678,FA(27:2)_<F>_n-24,255.4,183.0,27:2,FA,<F>,406.3,573.4
4746,FA(27:3)_<FF>_n-24,255.4,183.0,27:3,FA,<FF>,404.3,571.4
4833,FA(27:4)_<FFF>_n-24,255.4,183.0,27:4,FA,<FFF>,402.3,569.4
4937,FA(27:5)_<FFFF>_n-24,255.4,183.0,27:5,FA,<FFFF>,400.3,567.4
5056,FA(27:6)_<FFFFF>_n-24,255.4,183.0,27:6,FA,<FFFFF>,398.3,565.4

In [19]:
# to excel
sanjay_unique_df.to_excel('results/sanjay_unique_ParentIons.xlsx', index=False)
sanjay_unique_df

,Lipid,Parent_Ion,Product_Ion,Species,Class,DB Location,FA mass,[FA+AMP]+
3583,FA(24:5)_<BBBB>_n-2,513.4,183.0,24:5,FA,<BBBB>,358.3,525.4
3671,FA(24:6)_<BBBBF>_n-2,513.4,183.0,24:6,FA,<BBBBF>,356.3,523.4
3983,FA(25:5)_<BBBB>_n-3,513.4,183.0,25:5,FA,<BBBB>,372.3,539.4
4076,FA(25:6)_<BBBBF>_n-3,513.4,183.0,25:6,FA,<BBBBF>,370.3,537.4
4405,FA(26:5)_<BBBB>_n-4,513.4,183.0,26:5,FA,<BBBB>,386.3,553.4
...,...,...,...,...,...,...,...,...
4504,FA(26:6)_<BBBBB>_n-4,511.4,183.0,26:6,FA,<BBBBB>,384.3,551.4
4953,FA(27:6)_<BBBBB>_n-5,511.4,183.0,27:6,FA,<BBBBB>,398.3,565.4
5424,FA(28:6)_<BBBBB>_n-6,511.5,183.0,28:6,FA,<BBBBB>,412.4,579.5
5916,FA(29:6)_<BBBBB>_n-7,511.5,183.0,29:6,FA,<BBBBB>,426.4,593.5
6429,FA(30:6)_<BBBBB>_n-8,511.5,183.0,30:6,FA,<BBBBB>,440.4,607.5

# filter down sanjay unique

In [1]:
# 12 - 24C
# 12 to 18 4
# 18 24 6
#dwell time 25ms to 10ms, possibily 6 scans 
# Dynamic MRM according to the retention time

import pandas as pd
df = pd.read_excel('results/sanjay_unique_ParentIons.xlsx')
df

,Lipid,Parent_Ion,Product_Ion,Species,Class,DB Location,FA mass,[FA+AMP]+
0,FA(24:5)_<BBBB>_n-2,513.4,183,24:5,FA,<BBBB>,358.3,525.4
1,FA(24:6)_<BBBBF>_n-2,513.4,183,24:6,FA,<BBBBF>,356.3,523.4
2,FA(25:5)_<BBBB>_n-3,513.4,183,25:5,FA,<BBBB>,372.3,539.4
3,FA(25:6)_<BBBBF>_n-3,513.4,183,25:6,FA,<BBBBF>,370.3,537.4
4,FA(26:5)_<BBBB>_n-4,513.4,183,26:5,FA,<BBBB>,386.3,553.4
...,...,...,...,...,...,...,...,...
11040,FA(26:6)_<BBBBB>_n-4,511.4,183,26:6,FA,<BBBBB>,384.3,551.4
11041,FA(27:6)_<BBBBB>_n-5,511.4,183,27:6,FA,<BBBBB>,398.3,565.4
11042,FA(28:6)_<BBBBB>_n-6,511.5,183,28:6,FA,<BBBBB>,412.4,579.5
11043,FA(29:6)_<BBBBB>_n-7,511.5,183,29:6,FA,<BBBBB>,426.4,593.5
11044,FA(30:6)_<BBBBB>_n-8,511.5,183,30:6,FA,<BBBBB>,440.4,607.5

In [4]:

# 1. Split the 'Species' column
species_split = df['Species'].str.split(':', expand=True)
df['Species_main'] = species_split[0].astype(int)
df['Species_sub'] = species_split[1].astype(int)

# 2. Filter for Species_main between 12 and 24
df_filtered = df[(df['Species_main'] >= 12) & (df['Species_main'] <= 24)]

# 3. Apply conditional filtering
condition_12_17 = (
    (df_filtered['Species_main'] >= 12) &
    (df_filtered['Species_main'] <= 17) &
    (df_filtered['Species_sub'] <= 4)
)

condition_18_24 = (
    (df_filtered['Species_main'] >= 18) &
    (df_filtered['Species_main'] <= 24) &
    (df_filtered['Species_sub'] <= 6)
)

final_filtered_df = df_filtered[condition_12_17 | condition_18_24]

# 4. Optional: Drop the temporary columns
final_filtered_df = final_filtered_df.drop(['Species_main', 'Species_sub'], axis=1)

#print unqiue values length of Parent_Ion
print(f"Unique Parent_Ion values: {len(final_filtered_df['Parent_Ion'].unique())}")

final_filtered_df

Unique Parent_Ion values: 160

,Lipid,Parent_Ion,Product_Ion,Species,Class,DB Location,FA mass,[FA+AMP]+
0,FA(24:5)_<BBBB>_n-2,513.4,183,24:5,FA,<BBBB>,358.3,525.4
1,FA(24:6)_<BBBBF>_n-2,513.4,183,24:6,FA,<BBBBF>,356.3,523.4
14,FA(24:5)_<BBBB>_n-2,513.4,183,24:5,FA,<BBBB>,358.3,525.4
15,FA(24:6)_<BBBBF>_n-2,513.4,183,24:6,FA,<BBBBF>,356.3,523.4
28,FA(24:4)_<BBB>_n-2,515.4,183,24:4,FA,<BBB>,360.3,527.4
...,...,...,...,...,...,...,...,...
11022,FA(23:5)_<BBBB>_n-16,303.4,183,23:5,FA,<BBBB>,344.3,511.4
11023,FA(23:6)_<BBBBF>_n-16,303.4,183,23:6,FA,<BBBBF>,342.3,509.4
11024,FA(24:5)_<BBBB>_n-17,303.4,183,24:5,FA,<BBBB>,358.3,525.4
11025,FA(24:6)_<BBBBF>_n-17,303.4,183,24:6,FA,<BBBBF>,356.3,523.4
11038,FA(24:6)_<BBBBB>_n-2,511.4,183,24:6,FA,<BBBBB>,356.3,523.4

In [14]:
# for final_filtered_df print Parent_Ion value 241.2
final_filtered_df[final_filtered_df['Parent_Ion'] == 241.2]

,Lipid,Parent_Ion,Product_Ion,Species,Class,DB Location,FA mass,[FA+AMP]+
1034,FA(12:1)_<>_n-10,241.2,183,12:1,FA,<>,198.1,365.2
1035,FA(12:2)_<F>_n-10,241.2,183,12:2,FA,<F>,196.1,363.2
1036,FA(12:3)_<FF>_n-10,241.2,183,12:3,FA,<FF>,194.1,361.2
1037,FA(12:4)_<FFF>_n-10,241.2,183,12:4,FA,<FFF>,192.1,359.2
1040,FA(13:1)_<>_n-11,241.2,183,13:1,FA,<>,212.1,379.2
1041,FA(13:2)_<F>_n-11,241.2,183,13:2,FA,<F>,210.1,377.2
1042,FA(13:3)_<FF>_n-11,241.2,183,13:3,FA,<FF>,208.1,375.2
1043,FA(13:4)_<FFF>_n-11,241.2,183,13:4,FA,<FFF>,206.1,373.2

In [12]:
final_filtered_df[final_filtered_df['Parent_Ion'] == 241.3]

,Lipid,Parent_Ion,Product_Ion,Species,Class,DB Location,FA mass,[FA+AMP]+
1046,FA(14:1)_<>_n-12,241.3,183,14:1,FA,<>,226.2,393.3
1047,FA(14:2)_<F>_n-12,241.3,183,14:2,FA,<F>,224.2,391.3
1048,FA(14:3)_<FF>_n-12,241.3,183,14:3,FA,<FF>,222.2,389.3
1049,FA(14:4)_<FFF>_n-12,241.3,183,14:4,FA,<FFF>,220.2,387.3
1052,FA(15:1)_<>_n-13,241.3,183,15:1,FA,<>,240.2,407.3
...,...,...,...,...,...,...,...,...
1185,FA(20:2)_<F>_n-18,241.3,183,20:2,FA,<F>,308.2,475.3
1186,FA(20:3)_<FF>_n-18,241.3,183,20:3,FA,<FF>,306.2,473.3
1187,FA(20:4)_<FFF>_n-18,241.3,183,20:4,FA,<FFF>,304.2,471.3
1188,FA(20:5)_<FFFF>_n-18,241.3,183,20:5,FA,<FFFF>,302.2,469.3
1189,FA(20:6)_<FFFFF>_n-18,241.3,183,20:6,FA,<FFFFF>,300.2,467.3

In [9]:
# Group by 'Parent_Ion'
grouped_df = df.groupby('Parent_Ion').agg({
    'Lipid': '|'.join,                # Concatenate Lipid values
    'Product_Ion': 'first',           # Assuming Product_Ion is the same within Parent_Ion
    'Species': 'first',               # Similarly, assuming Species is consistent
    'Class': 'first',
    'DB Location': 'first',
    'FA mass': 'first',
    '[FA+AMP]+': 'first'
}).reset_index()

print("\nGrouped DataFrame:")
grouped_df

Grouped DataFrame:

,Parent_Ion,Lipid,Product_Ion,Species,Class,DB Location,FA mass,[FA+AMP]+
0,241.2,FA(6:1)_<>_n-4|FA(6:2)_<F>_n-4|FA(6:3)_<FF>_n-...,183,6:1,FA,<>,114.1,281.2
1,241.3,FA(14:1)_<>_n-12|FA(14:2)_<F>_n-12|FA(14:3)_<F...,183,14:1,FA,<>,226.2,393.3
2,241.4,FA(21:1)_<>_n-19|FA(21:2)_<F>_n-19|FA(21:3)_<F...,183,21:1,FA,<>,324.3,491.4
3,241.5,FA(28:1)_<>_n-26|FA(28:2)_<F>_n-26|FA(28:3)_<F...,183,28:1,FA,<>,422.4,589.5
4,253.2,FA(6:2)_<B>_n-3|FA(6:3)_<BF>_n-3|FA(6:4)_<BFF>...,183,6:2,FA,<B>,112.1,279.2
...,...,...,...,...,...,...,...,...
299,601.5,FA(30:3)_<BB>_n-2|FA(30:4)_<BBF>_n-2,183,30:3,FA,<BB>,446.4,613.5
300,603.5,FA(30:2)_<B>_n-2|FA(30:3)_<BF>_n-2,183,30:2,FA,<B>,448.4,615.5
301,605.3,FA(29:0)|FA(29:0),183,29:0,FA,None,438.2,617.3
302,605.5,FA(30:1)_<>_n-2|FA(30:2)_<F>_n-2|FA(30:1)_<>_n...,183,30:1,FA,<>,450.4,617.5
303,619.3,FA(30:0),183,30:0,FA,None,452.2,631.3

In [44]:
import pandas as pd
import numpy as np

def analyze_mass_tolerance(df, tolerance=0.3):
    """
    Analyze how many values fall within a specified mass tolerance range.
    
    Parameters:
    df (pandas.DataFrame): DataFrame containing mass spectrometry data
    tolerance (float): Mass tolerance range (±) in Da/mz units
    
    Returns:
    pandas.DataFrame: Summary of groups within tolerance ranges
    """
    # Sort the dataframe by Parent_Ion values
    sorted_df = df.sort_values('Parent_Ion')
    
    # Initialize lists to store group information
    groups = []
    current_group = []
    reference_mass = None
    
    # Group masses within tolerance
    for mass in sorted_df['Parent_Ion']:
        if reference_mass is None:
            reference_mass = mass
            current_group = [mass]
        elif abs(mass - reference_mass) <= tolerance:
            current_group.append(mass)
        else:
            groups.append(current_group)
            current_group = [mass]
            reference_mass = mass
    
    # Add the last group
    if current_group:
        groups.append(current_group)
    
    # Create summary DataFrame
    summary = pd.DataFrame({
        'Reference_Mass': [group[0] for group in groups],
        'Group_Size': [len(group) for group in groups],
        'Mass_Range': [f"{min(group):.2f} - {max(group):.2f}" for group in groups],
        'Mass_Spread': [max(group) - min(group) for group in groups],
        'Values': [', '.join([f"{x:.2f}" for x in group]) for group in groups]
    })
    
    return summary

# add lipid values

In [54]:
import pandas as pd
import numpy as np

def analyze_mass_tolerance(grouped_df, tolerance=0.3):
    """
    Analyze how many values fall within a specified mass tolerance range for a grouped DataFrame.
    Include Lipid and Species values for each mass group.
    
    Parameters:
    grouped_df (pandas.DataFrame): Grouped DataFrame containing mass spectrometry data
    tolerance (float): Mass tolerance range (±) in Da/mz units
    
    Returns:
    pandas.DataFrame: Summary of groups within tolerance ranges including Lipid and Species values
    """
    # Create dictionaries of mass to lipid and species mapping
    mass_lipid_dict = dict(zip(grouped_df['Parent_Ion'], grouped_df['Lipid']))
    mass_species_dict = dict(zip(grouped_df['Parent_Ion'], grouped_df['Species']))
    
    # Sort the masses
    sorted_masses = np.sort(grouped_df['Parent_Ion'].values)
    
    # Initialize lists to store group information
    groups = []
    current_group = []
    current_lipids = []
    current_species = []
    reference_mass = None
    
    # Group masses within tolerance
    for mass in sorted_masses:
        if reference_mass is None:
            reference_mass = mass
            current_group = [mass]
            current_lipids = [mass_lipid_dict[mass]]
            current_species = [mass_species_dict[mass]]
        elif abs(mass - reference_mass) <= tolerance:
            current_group.append(mass)
            current_lipids.append(mass_lipid_dict[mass])
            current_species.append(mass_species_dict[mass])
        else:
            groups.append((current_group, current_lipids, current_species))
            current_group = [mass]
            current_lipids = [mass_lipid_dict[mass]]
            current_species = [mass_species_dict[mass]]
            reference_mass = mass
    
    # Add the last group
    if current_group:
        groups.append((current_group, current_lipids, current_species))
    
    # Create summary DataFrame
    summary = pd.DataFrame({
        'Reference_Mass': [group[0][0] for group in groups],
        'Group_Size': [len(group[0]) for group in groups],
        'Mass_Range': [f"{min(group[0]):.2f} - {max(group[0]):.2f}" for group in groups],
        'Mass_Spread': [max(group[0]) - min(group[0]) for group in groups],
        'Mass_Values': [', '.join([f"{x:.2f}" for x in group[0]]) for group in groups],
        'Lipid_Values': [' | '.join(group[1]) for group in groups],
        'Species_Values': [' | '.join(group[2]) for group in groups]
    })
    
    return summary

# Example usage:
# results = analyze_mass_tolerance(grouped_df, tolerance=0.3)

In [55]:

# Example usage:
results = analyze_mass_tolerance(grouped_df, tolerance=0.4)

In [58]:
results

,Reference_Mass,Group_Size,Mass_Range,Mass_Spread,Mass_Values,Lipid_Values,Species_Values
0,241.2,4,241.20 - 241.50,0.3,"241.20, 241.30, 241.40, 241.50",FA(6:1)_<>_n-4|FA(6:2)_<F>_n-4|FA(6:3)_<FF>_n-...,6:1 | 14:1 | 21:1 | 28:1
1,253.2,4,253.20 - 253.50,0.3,"253.20, 253.30, 253.40, 253.50",FA(6:2)_<B>_n-3|FA(6:3)_<BF>_n-3|FA(6:4)_<BFF>...,6:2 | 14:2 | 21:2 | 28:2
2,255.3,3,255.30 - 255.50,0.2,"255.30, 255.40, 255.50",FA(14:1)_<>_n-11|FA(14:2)_<F>_n-11|FA(14:3)_<F...,14:1 | 21:1 | 28:1
3,265.2,4,265.20 - 265.50,0.3,"265.20, 265.30, 265.40, 265.50",FA(6:3)_<BB>_n-2|FA(6:4)_<BBF>_n-2|FA(7:3)_<BB...,6:3 | 14:3 | 21:3 | 28:3
4,267.2,4,267.20 - 267.50,0.3,"267.20, 267.30, 267.40, 267.50",FA(6:2)_<B>_n-2|FA(6:3)_<BF>_n-2|FA(7:2)_<B>_n...,6:2 | 14:2 | 21:2 | 28:2
5,269.3,3,269.30 - 269.50,0.2,"269.30, 269.40, 269.50",FA(5:0)|FA(14:1)_<>_n-10|FA(14:2)_<F>_n-10|FA(...,5:0 | 21:1 | 28:1
6,277.2,4,277.20 - 277.50,0.3,"277.20, 277.30, 277.40, 277.50",FA(7:4)_<BBB>_n-2|FA(7:5)_<BBBF>_n-2|FA(8:4)_<...,7:4 | 14:4 | 21:4 | 28:4
7,279.2,4,279.20 - 279.50,0.3,"279.20, 279.30, 279.40, 279.50",FA(7:3)_<BB>_n-2|FA(7:4)_<BBF>_n-2|FA(8:3)_<BB...,7:3 | 14:3 | 21:3 | 28:3
8,281.2,4,281.20 - 281.50,0.3,"281.20, 281.30, 281.40, 281.50",FA(7:2)_<B>_n-2|FA(7:3)_<BF>_n-2|FA(8:2)_<B>_n...,7:2 | 14:2 | 21:2 | 28:2
9,283.3,3,283.30 - 283.50,0.2,"283.30, 283.40, 283.50",FA(6:0)|FA(14:1)_<>_n-9|FA(14:2)_<F>_n-9|FA(14...,6:0 | 21:1 | 28:1
10,289.2,4,289.20 - 289.50,0.3,"289.20, 289.30, 289.40, 289.50",FA(8:5)_<BBBB>_n-2|FA(8:6)_<BBBBF>_n-2|FA(9:5)...,8:5 | 14:5 | 21:5 | 28:5
11,291.2,4,291.20 - 291.50,0.3,"291.20, 291.30, 291.40, 291.50",FA(8:4)_<BBB>_n-2|FA(8:5)_<BBBF>_n-2|FA(9:4)_<...,8:4 | 14:4 | 21:4 | 28:4
12,293.2,4,293.20 - 293.50,0.3,"293.20, 293.30, 293.40, 293.50",FA(8:3)_<BB>_n-2|FA(8:4)_<BBF>_n-2|FA(9:3)_<BB...,8:3 | 14:3 | 21:3 | 28:3
13,295.2,4,295.20 - 295.50,0.3,"295.20, 295.30, 295.40, 295.50",FA(8:2)_<B>_n-2|FA(8:3)_<BF>_n-2|FA(9:2)_<B>_n...,8:2 | 14:2 | 21:2 | 28:2
14,297.3,3,297.30 - 297.50,0.2,"297.30, 297.40, 297.50",FA(7:0)|FA(14:1)_<>_n-8|FA(14:2)_<F>_n-8|FA(14...,7:0 | 21:1 | 28:1
15,301.2,4,301.20 - 301.50,0.3,"301.20, 301.30, 301.40, 301.50",FA(9:6)_<BBBBB>_n-2|FA(10:6)_<BBBBB>_n-3|FA(11...,9:6 | 14:6 | 21:6 | 28:6
16,303.2,4,303.20 - 303.50,0.3,"303.20, 303.30, 303.40, 303.50",FA(9:5)_<BBBB>_n-2|FA(9:6)_<BBBBF>_n-2|FA(10:5...,9:5 | 14:5 | 21:5 | 28:5
17,305.2,4,305.20 - 305.50,0.3,"305.20, 305.30, 305.40, 305.50",FA(9:4)_<BBB>_n-2|FA(9:5)_<BBBF>_n-2|FA(10:4)_...,9:4 | 14:4 | 21:4 | 28:4
18,307.2,4,307.20 - 307.50,0.3,"307.20, 307.30, 307.40, 307.50",FA(9:3)_<BB>_n-2|FA(9:4)_<BBF>_n-2|FA(10:3)_<B...,9:3 | 14:3 | 21:3 | 28:3
19,309.3,3,309.30 - 309.50,0.2,"309.30, 309.40, 309.50",FA(14:2)_<B>_n-7|FA(14:3)_<BF>_n-7|FA(14:4)_<B...,14:2 | 21:2 | 28:2
20,315.2,4,315.20 - 315.50,0.3,"315.20, 315.30, 315.40, 315.50",FA(10:6)_<BBBBB>_n-2|FA(11:6)_<BBBBB>_n-3|FA(1...,10:6 | 14:6 | 21:6 | 28:6
21,317.2,4,317.20 - 317.50,0.3,"317.20, 317.30, 317.40, 317.50",FA(10:5)_<BBBB>_n-2|FA(10:6)_<BBBBF>_n-2|FA(11...,10:5 | 14:5 | 21:5 | 28:5
22,319.2,4,319.20 - 319.50,0.3,"319.20, 319.30, 319.40, 319.50",FA(10:4)_<BBB>_n-2|FA(10:5)_<BBBF>_n-2|FA(11:4...,10:4 | 14:4 | 21:4 | 28:4
23,321.2,4,321.20 - 321.50,0.3,"321.20, 321.30, 321.40, 321.50",FA(10:3)_<BB>_n-2|FA(10:4)_<BBF>_n-2|FA(11:3)_...,10:3 | 14:3 | 21:3 | 28:3
24,323.3,3,323.30 - 323.50,0.2,"323.30, 323.40, 323.50",FA(14:2)_<B>_n-6|FA(14:3)_<BF>_n-6|FA(14:4)_<B...,14:2 | 21:2 | 28:2
25,325.3,3,325.30 - 325.50,0.2,"325.30, 325.40, 325.50",FA(9:0)|FA(14:1)_<>_n-6|FA(14:2)_<F>_n-6|FA(14...,9:0 | 21:1 | 28:1
26,329.2,4,329.20 - 329.50,0.3,"329.20, 329.30, 329.40, 329.50",FA(11:6)_<BBBBB>_n-2|FA(12:6)_<BBBBB>_n-3|FA(1...,11:6 | 14:6 | 21:6 | 28:6
27,331.2,4,331.20 - 331.50,0.3,"331.20, 331.30, 331.40, 331.50",FA(11:5)_<BBBB>_n-2|FA(11:6)_<BBBBF>_n-2|FA(12...,11:5 | 14:5 | 21:5 | 28:5
28,333.2,4,333.20 - 333.50,0.3,"333.20, 333.30, 333.40, 333.50",FA(11:4)_<BBB>_n-2|FA(11:5)_<BBBF>_n-2|FA(12:4...,11:4 | 14:4 | 21:4 | 28:4
29,335.2,4,335.20 - 335.50,0.3,"335.20, 335.30, 335.40, 335.50",FA(11:3)_<BB>_n-2|FA(11:4)_<BBF>_n-2|FA(12:3)_...,11:3 | 14:3 | 21:3 | 28:3
30,337.3,3,337.30 - 337.50,0.2,"337.30, 337.40, 337.50",FA(14:2)_<B>_n-5|FA(14:3)_<BF>_n-5|FA(14:4)_<B...,14:2 | 21:2 | 28:2
31,343.2,4,343.20 - 343.50,0.3,"343.20, 343.30, 343.40, 343.50",FA(12:6)_<BBBBB>_n-2|FA(13:6)_<BBBBB>_n-3|FA(1...,12:6 | 14:6 | 21:6 | 28:6
32,345.2,4,345.20 - 345.50,0.3,"345.20, 345.30, 345.40, 345.50",FA(12:5)_<BBBB>_n-2|FA(12:6)_<BBBBF>_n-2|FA(13...,12:5 | 14:5 | 21:5 | 28:5
33,347.2,4,347.20 - 347.50,0.3,"347.20, 347.30, 347.40, 347.50",FA(12:4)_<BBB>_n-2|FA(12:5)_<BBBF>_n-2|FA(13:4...,12:4 | 14:4 | 21:4 | 28:4
34,349.3,3,349.30 - 349.50,0.2,"349.30, 349.40, 349.50",FA(14:3)_<BB>_n-4|FA(14:4)_<BBF>_n-4|FA(14:5)_...,14:3 | 21:3 | 28:3
35,351.2,4,351.20 - 351.50,0.3,"351.20, 351.30, 351.40, 351.50",FA(12:2)_<B>_n-2|FA(12:3)_<BF>_n-2|FA(13:2)_<B...,12:2 | 14:2 | 21:2 | 28:2
36,357.2,4,357.20 - 357.50,0.3,"357.20, 357.30, 357.40, 357.50",FA(13:6)_<BBBBB>_n-2|FA(13:6)_<BBBBB>_n-2|FA(1...,13:6 | 14:6 | 21:6 | 28:6
37,359.2,4,359.20 - 359.50,0.3,"359.20, 359.30, 359.40, 359.50",FA(13:5)_<BBBB>_n-2|FA(13:6)_<BBBBF>_n-2|FA(13...,13:5 | 14:5 | 21:5 | 28:5
38,361.2,4,361.20 - 361.50,0.3,"361.20, 361.30, 361.40, 361.50",FA(13:4)_<BBB>_n-2|FA(13:5)_<BBBF>_n-2|FA(13:4...,13:4 | 14:4 | 21:4 | 28:4
39,365.3,3,365.30 - 365.50,0.2,"365.30, 365.40, 365.50",FA(14:2)_<B>_n-3|FA(14:3)_<BF>_n-3|FA(14:4)_<B...,14:2 | 21:2 | 28:2
40,371.3,3,371.30 - 371.50,0.2,"371.30, 371.40, 371.50",FA(14:6)_<BBBBB>_n-2|FA(15:6)_<BBBBB>_n-3|FA(1...,14:6 | 21:6 | 28:6
41,373.3,3,373.30 - 373.50,0.2,"373.30, 373.40, 373.50",FA(14:5)_<BBBB>_n-2|FA(14:6)_<BBBBF>_n-2|FA(15...,14:5 | 21:5 | 28:5
42,375.3,3,375.30 - 375.50,0.2,"375.30, 375.40, 375.50",FA(14:4)_<BBB>_n-2|FA(14:5)_<BBBF>_n-2|FA(15:4...,14:4 | 21:4 | 28:4
43,377.3,3,377.30 - 377.50,0.2,"377.30, 377.40, 377.50",FA(14:3)_<BB>_n-2|FA(14:4)_<BBF>_n-2|FA(15:3)_...,14:3 | 21:3 | 28:3
44,385.3,3,385.30 - 385.50,0.2,"385.30, 385.40, 385.50",FA(15:6)_<BBBBB>_n-2|FA(16:6)_<BBBBB>_n-3|FA(1...,15:6 | 21:6 | 28:6
45,387.3,3,387.30 - 387.50,0.2,"387.30, 387.40, 387.50",FA(15:5)_<BBBB>_n-2|FA(15:6)_<BBBBF>_n-2|FA(16...,15:5 | 21:5 | 28:5
46,391.3,3,391.30 - 391.50,0.2,"391.30, 391.40, 391.50",FA(15:3)_<BB>_n-2|FA(15:4)_<BBF>_n-2|FA(16:3)_...,15:3 | 21:3 | 28:3
47,399.3,3,399.30 - 399.50,0.2,"399.30, 399.40, 399.50",FA(16:6)_<BBBBB>_n-2|FA(17:6)_<BBBBB>_n-3|FA(1...,16:6 | 21:6 | 28:6
48,401.3,3,401.30 - 401.50,0.2,"401.30, 401.40, 401.50",FA(16:5)_<BBBB>_n-2|FA(16:6)_<BBBBF>_n-2|FA(17...,16:5 | 21:5 | 28:5
49,403.3,3,403.30 - 403.50,0.2,"403.30, 403.40, 403.50",FA(16:4)_<BBB>_n-2|FA(16:5)_<BBBF>_n-2|FA(17:4...,16:4 | 21:4 | 28:4
50,405.3,3,405.30 - 405.50,0.2,"405.30, 405.40, 405.50",FA(16:3)_<BB>_n-2|FA(16:4)_<BBF>_n-2|FA(17:3)_...,16:3 | 21:3 | 28:3
51,413.3,3,413.30 - 413.50,0.2,"413.30, 413.40, 413.50",FA(17:6)_<BBBBB>_n-2|FA(18:6)_<BBBBB>_n-3|FA(1...,17:6 | 21:6 | 28:6
52,415.3,3,415.30 - 415.50,0.2,"415.30, 415.40, 415.50",FA(17:5)_<BBBB>_n-2|FA(17:6)_<BBBBF>_n-2|FA(18...,17:5 | 21:5 | 28:5
53,417.3,3,417.30 - 417.50,0.2,"417.30, 417.40, 417.50",FA(17:4)_<BBB>_n-2|FA(17:5)_<BBBF>_n-2|FA(18:4...,17:4 | 21:4 | 28:4
54,427.3,3,427.30 - 427.50,0.2,"427.30, 427.40, 427.50",FA(18:6)_<BBBBB>_n-2|FA(19:6)_<BBBBB>_n-3|FA(2...,18:6 | 21:6 | 28:6
55,429.3,3,429.30 - 429.50,0.2,"429.30, 429.40, 429.50",FA(18:5)_<BBBB>_n-2|FA(18:6)_<BBBBF>_n-2|FA(19...,18:5 | 21:5 | 28:5
56,431.3,3,431.30 - 431.50,0.2,"431.30, 431.40, 431.50",FA(18:4)_<BBB>_n-2|FA(18:5)_<BBBF>_n-2|FA(19:4...,18:4 | 21:4 | 28:4
57,433.3,3,433.30 - 433.50,0.2,"433.30, 433.40, 433.50",FA(18:3)_<BB>_n-2|FA(18:4)_<BBF>_n-2|FA(19:3)_...,18:3 | 21:3 | 28:3
58,441.3,3,441.30 - 441.50,0.2,"441.30, 441.40, 441.50",FA(19:6)_<BBBBB>_n-2|FA(20:6)_<BBBBB>_n-3|FA(1...,19:6 | 21:6 | 28:6
59,455.3,3,455.30 - 455.50,0.2,"455.30, 455.40, 455.50",FA(20:6)_<BBBBB>_n-2|FA(20:6)_<BBBBB>_n-2|FA(2...,20:6 | 21:6 | 28:6
60,457.3,3,457.30 - 457.50,0.2,"457.30, 457.40, 457.50",FA(20:5)_<BBBB>_n-2|FA(20:6)_<BBBBF>_n-2|FA(20...,20:5 | 21:5 | 28:5
61,459.3,3,459.30 - 459.50,0.2,"459.30, 459.40, 459.50",FA(20:4)_<BBB>_n-2|FA(20:5)_<BBBF>_n-2|FA(20:4...,20:4 | 21:4 | 28:4
62,461.3,3,461.30 - 461.50,0.2,"461.30, 461.40, 461.50",FA(20:3)_<BB>_n-2|FA(20:4)_<BBF>_n-2|FA(20:3)_...,20:3 | 21:3 | 28:3
63,463.3,3,463.30 - 463.50,0.2,"463.30, 463.40, 463.50",FA(20:2)_<B>_n-2|FA(20:3)_<BF>_n-2|FA(20:2)_<B...,20:2 | 21:2 | 28:2
64,483.4,2,483.40 - 483.50,0.1,"483.40, 483.50",FA(22:6)_<BBBBB>_n-2|FA(23:6)_<BBBBB>_n-3|FA(2...,22:6 | 28:6
65,485.4,2,485.40 - 485.50,0.1,"485.40, 485.50",FA(22:5)_<BBBB>_n-2|FA(22:6)_<BBBBF>_n-2|FA(23...,22:5 | 28:5
66,487.4,2,487.40 - 487.50,0.1,"487.40, 487.50",FA(22:4)_<BBB>_n-2|FA(22:5)_<BBBF>_n-2|FA(23:4...,22:4 | 28:4
67,489.4,2,489.40 - 489.50,0.1,"489.40, 489.50",FA(22:3)_<BB>_n-2|FA(22:4)_<BBF>_n-2|FA(23:3)_...,22:3 | 28:3
68,491.4,2,491.40 - 491.50,0.1,"491.40, 491.50",FA(22:2)_<B>_n-2|FA(22:3)_<BF>_n-2|FA(23:2)_<B...,22:2 | 28:2
69,497.4,2,497.40 - 497.50,0.1,"497.40, 497.50",FA(23:6)_<BBBBB>_n-2|FA(24:6)_<BBBBB>_n-3|FA(2...,23:6 | 28:6
70,499.4,2,499.40 - 499.50,0.1,"499.40, 499.50",FA(23:5)_<BBBB>_n-2|FA(23:6)_<BBBBF>_n-2|FA(24...,23:5 | 28:5
71,501.4,2,501.40 - 501.50,0.1,"501.40, 501.50",FA(23:4)_<BBB>_n-2|FA(23:5)_<BBBF>_n-2|FA(24:4...,23:4 | 28:4
72,511.4,2,511.40 - 511.50,0.1,"511.40, 511.50",FA(24:6)_<BBBBB>_n-2|FA(25:6)_<BBBBB>_n-3|FA(2...,24:6 | 28:6
73,513.4,2,513.40 - 513.50,0.1,"513.40, 513.50",FA(24:5)_<BBBB>_n-2|FA(24:6)_<BBBBF>_n-2|FA(25...,24:5 | 28:5
74,515.4,2,515.40 - 515.50,0.1,"515.40, 515.50",FA(24:4)_<BBB>_n-2|FA(24:5)_<BBBF>_n-2|FA(25:4...,24:4 | 28:4
75,517.4,2,517.40 - 517.50,0.1,"517.40, 517.50",FA(24:3)_<BB>_n-2|FA(24:4)_<BBF>_n-2|FA(25:3)_...,24:3 | 28:3
76,519.4,2,519.40 - 519.50,0.1,"519.40, 519.50",FA(24:2)_<B>_n-2|FA(24:3)_<BF>_n-2|FA(25:2)_<B...,24:2 | 28:2
77,525.4,2,525.40 - 525.50,0.1,"525.40, 525.50",FA(25:6)_<BBBBB>_n-2|FA(26:6)_<BBBBB>_n-3|FA(2...,25:6 | 28:6
78,527.4,2,527.40 - 527.50,0.1,"527.40, 527.50",FA(25:5)_<BBBB>_n-2|FA(25:6)_<BBBBF>_n-2|FA(26...,25:5 | 28:5
79,529.4,2,529.40 - 529.50,0.1,"529.40, 529.50",FA(25:4)_<BBB>_n-2|FA(25:5)_<BBBF>_n-2|FA(26:4...,25:4 | 28:4
80,531.4,2,531.40 - 531.50,0.1,"531.40, 531.50",FA(25:3)_<BB>_n-2|FA(25:4)_<BBF>_n-2|FA(26:3)_...,25:3 | 28:3
81,539.4,2,539.40 - 539.50,0.1,"539.40, 539.50",FA(26:6)_<BBBBB>_n-2|FA(27:6)_<BBBBB>_n-3|FA(2...,26:6 | 28:6
82,541.4,2,541.40 - 541.50,0.1,"541.40, 541.50",FA(26:5)_<BBBB>_n-2|FA(26:6)_<BBBBF>_n-2|FA(27...,26:5 | 28:5
83,543.4,2,543.40 - 543.50,0.1,"543.40, 543.50",FA(26:4)_<BBB>_n-2|FA(26:5)_<BBBF>_n-2|FA(27:4...,26:4 | 28:4
84,545.4,2,545.40 - 545.50,0.1,"545.40, 545.50",FA(26:3)_<BB>_n-2|FA(26:4)_<BBF>_n-2|FA(27:3)_...,26:3 | 28:3
85,547.4,2,547.40 - 547.50,0.1,"547.40, 547.50",FA(26:2)_<B>_n-2|FA(26:3)_<BF>_n-2|FA(27:2)_<B...,26:2 | 28:2
86,549.3,3,549.30 - 549.50,0.2,"549.30, 549.40, 549.50",FA(25:0)|FA(25:0)|FA(25:0) | FA(26:1)_<>_n-2|F...,25:0 | 26:1 | 28:1
87,553.4,2,553.40 - 553.50,0.1,"553.40, 553.50",FA(27:6)_<BBBBB>_n-2|FA(27:6)_<BBBBB>_n-2 | FA...,27:6 | 28:6
88,555.4,2,555.40 - 555.50,0.1,"555.40, 555.50",FA(27:5)_<BBBB>_n-2|FA(27:6)_<BBBBF>_n-2|FA(27...,27:5 | 28:5
89,557.4,2,557.40 - 557.50,0.1,"557.40, 557.50",FA(27:4)_<BBB>_n-2|FA(27:5)_<BBBF>_n-2|FA(27:4...,27:4 | 28:4
90,559.4,2,559.40 - 559.50,0.1,"559.40, 559.50",FA(27:3)_<BB>_n-2|FA(27:4)_<BBF>_n-2|FA(27:3)_...,27:3 | 28:3
91,561.4,2,561.40 - 561.50,0.1,"561.40, 561.50",FA(27:2)_<B>_n-2|FA(27:3)_<BF>_n-2|FA(27:2)_<B...,27:2 | 28:2
92,563.3,3,563.30 - 563.50,0.2,"563.30, 563.40, 563.50",FA(26:0)|FA(26:0)|FA(26:0) | FA(27:1)_<>_n-2|F...,26:0 | 27:1 | 28:1
93,567.5,1,567.50 - 567.50,0.0,567.50,FA(28:6)_<BBBBB>_n-2|FA(29:6)_<BBBBB>_n-3|FA(3...,28:6
94,569.5,1,569.50 - 569.50,0.0,569.50,FA(28:5)_<BBBB>_n-2|FA(28:6)_<BBBBF>_n-2|FA(29...,28:5
95,571.5,1,571.50 - 571.50,0.0,571.50,FA(28:4)_<BBB>_n-2|FA(28:5)_<BBBF>_n-2|FA(29:4...,28:4
96,573.5,1,573.50 - 573.50,0.0,573.50,FA(28:3)_<BB>_n-2|FA(28:4)_<BBF>_n-2|FA(29:3)_...,28:3
97,575.5,1,575.50 - 575.50,0.0,575.50,FA(28:2)_<B>_n-2|FA(28:3)_<BF>_n-2|FA(29:2)_<B...,28:2
98,577.3,2,577.30 - 577.50,0.2,"577.30, 577.50",FA(27:0)|FA(27:0) | FA(28:1)_<>_n-2|FA(28:2)_<...,27:0 | 28:1
99,581.5,1,581.50 - 581.50,0.0,581.50,FA(29:6)_<BBBBB>_n-2|FA(30:6)_<BBBBB>_n-3,29:6
100,583.5,1,583.50 - 583.50,0.0,583.50,FA(29:5)_<BBBB>_n-2|FA(29:6)_<BBBBF>_n-2|FA(30...,29:5
101,585.5,1,585.50 - 585.50,0.0,585.50,FA(29:4)_<BBB>_n-2|FA(29:5)_<BBBF>_n-2|FA(30:4...,29:4
102,587.5,1,587.50 - 587.50,0.0,587.50,FA(29:3)_<BB>_n-2|FA(29:4)_<BBF>_n-2|FA(30:3)_...,29:3
103,589.5,1,589.50 - 589.50,0.0,589.50,FA(29:2)_<B>_n-2|FA(29:3)_<BF>_n-2|FA(30:2)_<B...,29:2
104,591.3,2,591.30 - 591.50,0.2,"591.30, 591.50",FA(28:0)|FA(28:0) | FA(29:1)_<>_n-2|FA(29:2)_<...,28:0 | 29:1
105,595.5,1,595.50 - 595.50,0.0,595.50,FA(30:6)_<BBBBB>_n-2,30:6
106,597.5,1,597.50 - 597.50,0.0,597.50,FA(30:5)_<BBBB>_n-2|FA(30:6)_<BBBBF>_n-2,30:5
107,599.5,1,599.50 - 599.50,0.0,599.50,FA(30:4)_<BBB>_n-2|FA(30:5)_<BBBF>_n-2,30:4
108,601.5,1,601.50 - 601.50,0.0,601.50,FA(30:3)_<BB>_n-2|FA(30:4)_<BBF>_n-2,30:3
109,603.5,1,603.50 - 603.50,0.0,603.50,FA(30:2)_<B>_n-2|FA(30:3)_<BF>_n-2,30:2
110,605.3,2,605.30 - 605.50,0.2,"605.30, 605.50",FA(29:0)|FA(29:0) | FA(30:1)_<>_n-2|FA(30:2)_<...,29:0 | 30:1
111,619.3,1,619.30 - 619.30,0.0,619.30,FA(30:0),30:0

# filter out species

In [60]:
import pandas as pd
import numpy as np

def filter_species_range(results_df):
    """
    Filter out groups where all Species values are either:
    - all above 24:X OR
    - all below 12:X
    
    Parameters:
    results_df (pandas.DataFrame): DataFrame from analyze_mass_tolerance function
    
    Returns:
    pandas.DataFrame: Filtered DataFrame excluding groups where all species are outside desired range
    """
    def check_species_range(species_str):
        # Split species into individual values
        species_list = [s.strip() for s in species_str.split('|')]
        
        # Track if we find any values in our desired range
        all_high = True
        all_low = True
        
        # Parse each species value
        for species in species_list:
            try:
                # Extract the number before the colon
                num = int(species.split(':')[0])
                if num <= 24:  # Check if not too high
                    all_high = False
                if num >= 12:  # Check if not too low
                    all_low = False
                    
                # If we've found at least one value in range, we can stop checking
                if not all_high and not all_low:
                    break
                    
            except (ValueError, IndexError):
                # If we can't parse the number, assume it's in range
                all_high = False
                all_low = False
                
        # Return True to keep rows where not all species are too high or too low
        return not (all_high or all_low)

    # Apply the filter
    filtered_df = results_df[results_df['Species_Values'].apply(check_species_range)].copy()
    
    return filtered_df

# Example usage:
# results = analyze_mass_tolerance(grouped_df, tolerance=0.3)
filtered_results = filter_species_range(results)

In [61]:
filtered_results

,Reference_Mass,Group_Size,Mass_Range,Mass_Spread,Mass_Values,Lipid_Values,Species_Values
0,241.2,4,241.20 - 241.50,0.3,"241.20, 241.30, 241.40, 241.50",FA(6:1)_<>_n-4|FA(6:2)_<F>_n-4|FA(6:3)_<FF>_n-...,6:1 | 14:1 | 21:1 | 28:1
1,253.2,4,253.20 - 253.50,0.3,"253.20, 253.30, 253.40, 253.50",FA(6:2)_<B>_n-3|FA(6:3)_<BF>_n-3|FA(6:4)_<BFF>...,6:2 | 14:2 | 21:2 | 28:2
2,255.3,3,255.30 - 255.50,0.2,"255.30, 255.40, 255.50",FA(14:1)_<>_n-11|FA(14:2)_<F>_n-11|FA(14:3)_<F...,14:1 | 21:1 | 28:1
3,265.2,4,265.20 - 265.50,0.3,"265.20, 265.30, 265.40, 265.50",FA(6:3)_<BB>_n-2|FA(6:4)_<BBF>_n-2|FA(7:3)_<BB...,6:3 | 14:3 | 21:3 | 28:3
4,267.2,4,267.20 - 267.50,0.3,"267.20, 267.30, 267.40, 267.50",FA(6:2)_<B>_n-2|FA(6:3)_<BF>_n-2|FA(7:2)_<B>_n...,6:2 | 14:2 | 21:2 | 28:2
5,269.3,3,269.30 - 269.50,0.2,"269.30, 269.40, 269.50",FA(5:0)|FA(14:1)_<>_n-10|FA(14:2)_<F>_n-10|FA(...,5:0 | 21:1 | 28:1
6,277.2,4,277.20 - 277.50,0.3,"277.20, 277.30, 277.40, 277.50",FA(7:4)_<BBB>_n-2|FA(7:5)_<BBBF>_n-2|FA(8:4)_<...,7:4 | 14:4 | 21:4 | 28:4
7,279.2,4,279.20 - 279.50,0.3,"279.20, 279.30, 279.40, 279.50",FA(7:3)_<BB>_n-2|FA(7:4)_<BBF>_n-2|FA(8:3)_<BB...,7:3 | 14:3 | 21:3 | 28:3
8,281.2,4,281.20 - 281.50,0.3,"281.20, 281.30, 281.40, 281.50",FA(7:2)_<B>_n-2|FA(7:3)_<BF>_n-2|FA(8:2)_<B>_n...,7:2 | 14:2 | 21:2 | 28:2
9,283.3,3,283.30 - 283.50,0.2,"283.30, 283.40, 283.50",FA(6:0)|FA(14:1)_<>_n-9|FA(14:2)_<F>_n-9|FA(14...,6:0 | 21:1 | 28:1
10,289.2,4,289.20 - 289.50,0.3,"289.20, 289.30, 289.40, 289.50",FA(8:5)_<BBBB>_n-2|FA(8:6)_<BBBBF>_n-2|FA(9:5)...,8:5 | 14:5 | 21:5 | 28:5
11,291.2,4,291.20 - 291.50,0.3,"291.20, 291.30, 291.40, 291.50",FA(8:4)_<BBB>_n-2|FA(8:5)_<BBBF>_n-2|FA(9:4)_<...,8:4 | 14:4 | 21:4 | 28:4
12,293.2,4,293.20 - 293.50,0.3,"293.20, 293.30, 293.40, 293.50",FA(8:3)_<BB>_n-2|FA(8:4)_<BBF>_n-2|FA(9:3)_<BB...,8:3 | 14:3 | 21:3 | 28:3
13,295.2,4,295.20 - 295.50,0.3,"295.20, 295.30, 295.40, 295.50",FA(8:2)_<B>_n-2|FA(8:3)_<BF>_n-2|FA(9:2)_<B>_n...,8:2 | 14:2 | 21:2 | 28:2
14,297.3,3,297.30 - 297.50,0.2,"297.30, 297.40, 297.50",FA(7:0)|FA(14:1)_<>_n-8|FA(14:2)_<F>_n-8|FA(14...,7:0 | 21:1 | 28:1
15,301.2,4,301.20 - 301.50,0.3,"301.20, 301.30, 301.40, 301.50",FA(9:6)_<BBBBB>_n-2|FA(10:6)_<BBBBB>_n-3|FA(11...,9:6 | 14:6 | 21:6 | 28:6
16,303.2,4,303.20 - 303.50,0.3,"303.20, 303.30, 303.40, 303.50",FA(9:5)_<BBBB>_n-2|FA(9:6)_<BBBBF>_n-2|FA(10:5...,9:5 | 14:5 | 21:5 | 28:5
17,305.2,4,305.20 - 305.50,0.3,"305.20, 305.30, 305.40, 305.50",FA(9:4)_<BBB>_n-2|FA(9:5)_<BBBF>_n-2|FA(10:4)_...,9:4 | 14:4 | 21:4 | 28:4
18,307.2,4,307.20 - 307.50,0.3,"307.20, 307.30, 307.40, 307.50",FA(9:3)_<BB>_n-2|FA(9:4)_<BBF>_n-2|FA(10:3)_<B...,9:3 | 14:3 | 21:3 | 28:3
19,309.3,3,309.30 - 309.50,0.2,"309.30, 309.40, 309.50",FA(14:2)_<B>_n-7|FA(14:3)_<BF>_n-7|FA(14:4)_<B...,14:2 | 21:2 | 28:2
20,315.2,4,315.20 - 315.50,0.3,"315.20, 315.30, 315.40, 315.50",FA(10:6)_<BBBBB>_n-2|FA(11:6)_<BBBBB>_n-3|FA(1...,10:6 | 14:6 | 21:6 | 28:6
21,317.2,4,317.20 - 317.50,0.3,"317.20, 317.30, 317.40, 317.50",FA(10:5)_<BBBB>_n-2|FA(10:6)_<BBBBF>_n-2|FA(11...,10:5 | 14:5 | 21:5 | 28:5
22,319.2,4,319.20 - 319.50,0.3,"319.20, 319.30, 319.40, 319.50",FA(10:4)_<BBB>_n-2|FA(10:5)_<BBBF>_n-2|FA(11:4...,10:4 | 14:4 | 21:4 | 28:4
23,321.2,4,321.20 - 321.50,0.3,"321.20, 321.30, 321.40, 321.50",FA(10:3)_<BB>_n-2|FA(10:4)_<BBF>_n-2|FA(11:3)_...,10:3 | 14:3 | 21:3 | 28:3
24,323.3,3,323.30 - 323.50,0.2,"323.30, 323.40, 323.50",FA(14:2)_<B>_n-6|FA(14:3)_<BF>_n-6|FA(14:4)_<B...,14:2 | 21:2 | 28:2
25,325.3,3,325.30 - 325.50,0.2,"325.30, 325.40, 325.50",FA(9:0)|FA(14:1)_<>_n-6|FA(14:2)_<F>_n-6|FA(14...,9:0 | 21:1 | 28:1
26,329.2,4,329.20 - 329.50,0.3,"329.20, 329.30, 329.40, 329.50",FA(11:6)_<BBBBB>_n-2|FA(12:6)_<BBBBB>_n-3|FA(1...,11:6 | 14:6 | 21:6 | 28:6
27,331.2,4,331.20 - 331.50,0.3,"331.20, 331.30, 331.40, 331.50",FA(11:5)_<BBBB>_n-2|FA(11:6)_<BBBBF>_n-2|FA(12...,11:5 | 14:5 | 21:5 | 28:5
28,333.2,4,333.20 - 333.50,0.3,"333.20, 333.30, 333.40, 333.50",FA(11:4)_<BBB>_n-2|FA(11:5)_<BBBF>_n-2|FA(12:4...,11:4 | 14:4 | 21:4 | 28:4
29,335.2,4,335.20 - 335.50,0.3,"335.20, 335.30, 335.40, 335.50",FA(11:3)_<BB>_n-2|FA(11:4)_<BBF>_n-2|FA(12:3)_...,11:3 | 14:3 | 21:3 | 28:3
30,337.3,3,337.30 - 337.50,0.2,"337.30, 337.40, 337.50",FA(14:2)_<B>_n-5|FA(14:3)_<BF>_n-5|FA(14:4)_<B...,14:2 | 21:2 | 28:2
31,343.2,4,343.20 - 343.50,0.3,"343.20, 343.30, 343.40, 343.50",FA(12:6)_<BBBBB>_n-2|FA(13:6)_<BBBBB>_n-3|FA(1...,12:6 | 14:6 | 21:6 | 28:6
32,345.2,4,345.20 - 345.50,0.3,"345.20, 345.30, 345.40, 345.50",FA(12:5)_<BBBB>_n-2|FA(12:6)_<BBBBF>_n-2|FA(13...,12:5 | 14:5 | 21:5 | 28:5
33,347.2,4,347.20 - 347.50,0.3,"347.20, 347.30, 347.40, 347.50",FA(12:4)_<BBB>_n-2|FA(12:5)_<BBBF>_n-2|FA(13:4...,12:4 | 14:4 | 21:4 | 28:4
34,349.3,3,349.30 - 349.50,0.2,"349.30, 349.40, 349.50",FA(14:3)_<BB>_n-4|FA(14:4)_<BBF>_n-4|FA(14:5)_...,14:3 | 21:3 | 28:3
35,351.2,4,351.20 - 351.50,0.3,"351.20, 351.30, 351.40, 351.50",FA(12:2)_<B>_n-2|FA(12:3)_<BF>_n-2|FA(13:2)_<B...,12:2 | 14:2 | 21:2 | 28:2
36,357.2,4,357.20 - 357.50,0.3,"357.20, 357.30, 357.40, 357.50",FA(13:6)_<BBBBB>_n-2|FA(13:6)_<BBBBB>_n-2|FA(1...,13:6 | 14:6 | 21:6 | 28:6
37,359.2,4,359.20 - 359.50,0.3,"359.20, 359.30, 359.40, 359.50",FA(13:5)_<BBBB>_n-2|FA(13:6)_<BBBBF>_n-2|FA(13...,13:5 | 14:5 | 21:5 | 28:5
38,361.2,4,361.20 - 361.50,0.3,"361.20, 361.30, 361.40, 361.50",FA(13:4)_<BBB>_n-2|FA(13:5)_<BBBF>_n-2|FA(13:4...,13:4 | 14:4 | 21:4 | 28:4
39,365.3,3,365.30 - 365.50,0.2,"365.30, 365.40, 365.50",FA(14:2)_<B>_n-3|FA(14:3)_<BF>_n-3|FA(14:4)_<B...,14:2 | 21:2 | 28:2
40,371.3,3,371.30 - 371.50,0.2,"371.30, 371.40, 371.50",FA(14:6)_<BBBBB>_n-2|FA(15:6)_<BBBBB>_n-3|FA(1...,14:6 | 21:6 | 28:6
41,373.3,3,373.30 - 373.50,0.2,"373.30, 373.40, 373.50",FA(14:5)_<BBBB>_n-2|FA(14:6)_<BBBBF>_n-2|FA(15...,14:5 | 21:5 | 28:5
42,375.3,3,375.30 - 375.50,0.2,"375.30, 375.40, 375.50",FA(14:4)_<BBB>_n-2|FA(14:5)_<BBBF>_n-2|FA(15:4...,14:4 | 21:4 | 28:4
43,377.3,3,377.30 - 377.50,0.2,"377.30, 377.40, 377.50",FA(14:3)_<BB>_n-2|FA(14:4)_<BBF>_n-2|FA(15:3)_...,14:3 | 21:3 | 28:3
44,385.3,3,385.30 - 385.50,0.2,"385.30, 385.40, 385.50",FA(15:6)_<BBBBB>_n-2|FA(16:6)_<BBBBB>_n-3|FA(1...,15:6 | 21:6 | 28:6
45,387.3,3,387.30 - 387.50,0.2,"387.30, 387.40, 387.50",FA(15:5)_<BBBB>_n-2|FA(15:6)_<BBBBF>_n-2|FA(16...,15:5 | 21:5 | 28:5
46,391.3,3,391.30 - 391.50,0.2,"391.30, 391.40, 391.50",FA(15:3)_<BB>_n-2|FA(15:4)_<BBF>_n-2|FA(16:3)_...,15:3 | 21:3 | 28:3
47,399.3,3,399.30 - 399.50,0.2,"399.30, 399.40, 399.50",FA(16:6)_<BBBBB>_n-2|FA(17:6)_<BBBBB>_n-3|FA(1...,16:6 | 21:6 | 28:6
48,401.3,3,401.30 - 401.50,0.2,"401.30, 401.40, 401.50",FA(16:5)_<BBBB>_n-2|FA(16:6)_<BBBBF>_n-2|FA(17...,16:5 | 21:5 | 28:5
49,403.3,3,403.30 - 403.50,0.2,"403.30, 403.40, 403.50",FA(16:4)_<BBB>_n-2|FA(16:5)_<BBBF>_n-2|FA(17:4...,16:4 | 21:4 | 28:4
50,405.3,3,405.30 - 405.50,0.2,"405.30, 405.40, 405.50",FA(16:3)_<BB>_n-2|FA(16:4)_<BBF>_n-2|FA(17:3)_...,16:3 | 21:3 | 28:3
51,413.3,3,413.30 - 413.50,0.2,"413.30, 413.40, 413.50",FA(17:6)_<BBBBB>_n-2|FA(18:6)_<BBBBB>_n-3|FA(1...,17:6 | 21:6 | 28:6
52,415.3,3,415.30 - 415.50,0.2,"415.30, 415.40, 415.50",FA(17:5)_<BBBB>_n-2|FA(17:6)_<BBBBF>_n-2|FA(18...,17:5 | 21:5 | 28:5
53,417.3,3,417.30 - 417.50,0.2,"417.30, 417.40, 417.50",FA(17:4)_<BBB>_n-2|FA(17:5)_<BBBF>_n-2|FA(18:4...,17:4 | 21:4 | 28:4
54,427.3,3,427.30 - 427.50,0.2,"427.30, 427.40, 427.50",FA(18:6)_<BBBBB>_n-2|FA(19:6)_<BBBBB>_n-3|FA(2...,18:6 | 21:6 | 28:6
55,429.3,3,429.30 - 429.50,0.2,"429.30, 429.40, 429.50",FA(18:5)_<BBBB>_n-2|FA(18:6)_<BBBBF>_n-2|FA(19...,18:5 | 21:5 | 28:5
56,431.3,3,431.30 - 431.50,0.2,"431.30, 431.40, 431.50",FA(18:4)_<BBB>_n-2|FA(18:5)_<BBBF>_n-2|FA(19:4...,18:4 | 21:4 | 28:4
57,433.3,3,433.30 - 433.50,0.2,"433.30, 433.40, 433.50",FA(18:3)_<BB>_n-2|FA(18:4)_<BBF>_n-2|FA(19:3)_...,18:3 | 21:3 | 28:3
58,441.3,3,441.30 - 441.50,0.2,"441.30, 441.40, 441.50",FA(19:6)_<BBBBB>_n-2|FA(20:6)_<BBBBB>_n-3|FA(1...,19:6 | 21:6 | 28:6
59,455.3,3,455.30 - 455.50,0.2,"455.30, 455.40, 455.50",FA(20:6)_<BBBBB>_n-2|FA(20:6)_<BBBBB>_n-2|FA(2...,20:6 | 21:6 | 28:6
60,457.3,3,457.30 - 457.50,0.2,"457.30, 457.40, 457.50",FA(20:5)_<BBBB>_n-2|FA(20:6)_<BBBBF>_n-2|FA(20...,20:5 | 21:5 | 28:5
61,459.3,3,459.30 - 459.50,0.2,"459.30, 459.40, 459.50",FA(20:4)_<BBB>_n-2|FA(20:5)_<BBBF>_n-2|FA(20:4...,20:4 | 21:4 | 28:4
62,461.3,3,461.30 - 461.50,0.2,"461.30, 461.40, 461.50",FA(20:3)_<BB>_n-2|FA(20:4)_<BBF>_n-2|FA(20:3)_...,20:3 | 21:3 | 28:3
63,463.3,3,463.30 - 463.50,0.2,"463.30, 463.40, 463.50",FA(20:2)_<B>_n-2|FA(20:3)_<BF>_n-2|FA(20:2)_<B...,20:2 | 21:2 | 28:2
64,483.4,2,483.40 - 483.50,0.1,"483.40, 483.50",FA(22:6)_<BBBBB>_n-2|FA(23:6)_<BBBBB>_n-3|FA(2...,22:6 | 28:6
65,485.4,2,485.40 - 485.50,0.1,"485.40, 485.50",FA(22:5)_<BBBB>_n-2|FA(22:6)_<BBBBF>_n-2|FA(23...,22:5 | 28:5
66,487.4,2,487.40 - 487.50,0.1,"487.40, 487.50",FA(22:4)_<BBB>_n-2|FA(22:5)_<BBBF>_n-2|FA(23:4...,22:4 | 28:4
67,489.4,2,489.40 - 489.50,0.1,"489.40, 489.50",FA(22:3)_<BB>_n-2|FA(22:4)_<BBF>_n-2|FA(23:3)_...,22:3 | 28:3
68,491.4,2,491.40 - 491.50,0.1,"491.40, 491.50",FA(22:2)_<B>_n-2|FA(22:3)_<BF>_n-2|FA(23:2)_<B...,22:2 | 28:2
69,497.4,2,497.40 - 497.50,0.1,"497.40, 497.50",FA(23:6)_<BBBBB>_n-2|FA(24:6)_<BBBBB>_n-3|FA(2...,23:6 | 28:6
70,499.4,2,499.40 - 499.50,0.1,"499.40, 499.50",FA(23:5)_<BBBB>_n-2|FA(23:6)_<BBBBF>_n-2|FA(24...,23:5 | 28:5
71,501.4,2,501.40 - 501.50,0.1,"501.40, 501.50",FA(23:4)_<BBB>_n-2|FA(23:5)_<BBBF>_n-2|FA(24:4...,23:4 | 28:4
72,511.4,2,511.40 - 511.50,0.1,"511.40, 511.50",FA(24:6)_<BBBBB>_n-2|FA(25:6)_<BBBBB>_n-3|FA(2...,24:6 | 28:6
73,513.4,2,513.40 - 513.50,0.1,"513.40, 513.50",FA(24:5)_<BBBB>_n-2|FA(24:6)_<BBBBF>_n-2|FA(25...,24:5 | 28:5
74,515.4,2,515.40 - 515.50,0.1,"515.40, 515.50",FA(24:4)_<BBB>_n-2|FA(24:5)_<BBBF>_n-2|FA(25:4...,24:4 | 28:4
75,517.4,2,517.40 - 517.50,0.1,"517.40, 517.50",FA(24:3)_<BB>_n-2|FA(24:4)_<BBF>_n-2|FA(25:3)_...,24:3 | 28:3
76,519.4,2,519.40 - 519.50,0.1,"519.40, 519.50",FA(24:2)_<B>_n-2|FA(24:3)_<BF>_n-2|FA(25:2)_<B...,24:2 | 28:2

In [62]:
caitlin_df

,Compound Group,Compound Name,ISTD?,Parent Ion,MS1 Res,Product Ion,MS2 Res,Dwell,Fragmentor,Collision Energy,Cell Accelerator Voltage,Polarity,Class
0,NaN,24:0,False,535.4,Unit,183,Unit,25,100,0,2,Negative,FA
1,NaN,24:1,False,533.4,Unit,183,Unit,25,100,0,2,Negative,FA
2,NaN,23:0 / 24:1n-2,False,521.4,Unit,183,Unit,25,100,0,2,Negative,FA
3,NaN,22:0 / 23:1n-2 / 24:1n-3,False,507.4,Unit,183,Unit,25,100,0,2,Negative,FA
4,NaN,22:1,False,505.4,Unit,183,Unit,25,100,0,2,Negative,FA
5,NaN,22:2,False,503.4,Unit,183,Unit,25,100,0,2,Negative,FA
6,NaN,22:6,False,495.4,Unit,183,Unit,25,100,0,2,Negative,FA
7,NaN,21:0 / 22:1n-2 / 23:1n-3 / 24:1n-4,False,493.4,Unit,183,Unit,25,100,0,2,Negative,FA
8,NaN,20:0 / 21:1n-2 / 22:1n-3 / 23:1n-4 / 24:1n-5,False,479.4,Unit,183,Unit,25,100,0,2,Negative,FA
9,NaN,20:1,False,477.4,Unit,183,Unit,25,100,0,2,Negative,FA
10,NaN,20:2,False,475.4,Unit,183,Unit,25,100,0,2,Negative,FA
11,NaN,20:3,False,473.4,Unit,183,Unit,25,100,0,2,Negative,FA
12,NaN,20:4,False,471.4,Unit,183,Unit,25,100,0,2,Negative,FA
13,NaN,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3)/20:5",False,469.4,Unit,183,Unit,25,100,0,2,Negative,FA
14,NaN,20:1n-2 / 21:1n-3 / 22:1n-4 / 23:1n-5 / 24:1n-6,False,465.3,Unit,183,Unit,25,100,0,2,Negative,FA
15,NaN,18:0 / 20:1n-3 / 21:1 n-4 / 19:1n-2 / 21:1n-4 ...,False,451.4,Unit,183,Unit,25,100,0,2,Negative,FA
16,NaN,18:1,False,449.4,Unit,183,Unit,25,100,0,2,Negative,FA
17,NaN,"18:2 / 20:3 (11Z,14Z,17Z)n-3",False,447.4,Unit,183,Unit,25,100,0,2,Negative,FA
18,NaN,18:3,False,445.4,Unit,183,Unit,25,100,0,2,Negative,FA
19,NaN,"20:5 (5Z,8Z,11Z,14Z,17Z)n-3",False,443.3,Unit,183,Unit,25,100,0,2,Negative,FA
20,NaN,17:0 / 19:1n-3 / 20:1n-4 / 21:1n-5 / 22:1n-6 /...,False,437.4,Unit,183,Unit,25,100,0,2,Negative,FA
21,NaN,"17:1 / 22:2 (13Z,16Z)n-6",False,435.4,Unit,183,Unit,25,100,0,2,Negative,FA
22,NaN,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6",False,429.2,Unit,183,Unit,25,100,0,2,Negative,FA
23,NaN,d2-16:0,False,425.4,Unit,183,Unit,25,100,0,2,Negative,FA
24,NaN,16:0 / 24:1 (15Z)n-9 / 18:1n-3 / 17:1n-2 / 19:...,False,423.3,Unit,183,Unit,25,100,0,2,Negative,FA
25,NaN,16:1,False,421.4,Unit,183,Unit,25,100,0,2,Negative,FA
26,NaN,"18:3 (9Z,12Z,15Z))n-3",False,419.3,Unit,183,Unit,25,100,0,2,Negative,FA
27,NaN,15:0 / 17:1n-3 / 18:1n-4 / 16:1n-2 / 19:1n-5 /...,False,409.3,Unit,183,Unit,25,100,0,2,Negative,FA
28,NaN,"20:2 (11Z,14Z)n-6 / 20:3 (11Z,14Z,17Z)n-3,n-6 ...",False,407.3,Unit,183,Unit,25,100,0,2,Negative,FA
29,NaN,"20:3 (8Z,11Z,14Z)n-6",False,405.2,Unit,183,Unit,25,100,0,2,Negative,FA
30,NaN,"20:4 (5Z,8Z,11Z,14Z)n-6 / 20:5 (5Z,8Z,11Z,14Z,...",False,403.2,Unit,183,Unit,25,100,0,2,Negative,FA
31,NaN,"14:0 / 22:2 (13Z,16Z)n-6,n-9 / 22:1 (13Z)n-9 /...",False,395.3,Unit,183,Unit,25,100,0,2,Negative,FA
32,NaN,14:1(9Z),False,393.4,Unit,183,Unit,25,100,0,2,Negative,FA
33,NaN,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6,n-9",False,389.3,Unit,183,Unit,25,100,0,2,Negative,FA
34,NaN,13:0 / 14:1n-2 / 15:1n-3 / 16:1n-4 / 17:1n-5 /...,False,381.3,Unit,183,Unit,25,100,0,2,Negative,FA
35,NaN,"18:2 (9Z,12Z)n-6 / 18:3 (9Z,12Z,15Z))n-3.n-6",False,379.3,Unit,183,Unit,25,100,0,2,Negative,FA
36,NaN,"18:3 (6Z,9Z,12Z))n-6",False,377.2,Unit,183,Unit,25,100,0,2,Negative,FA
37,NaN,"12:0 / 20:2 (11Z,14Z)n-6,n-9 / 20:3 (11Z,14Z,1...",False,367.3,Unit,183,Unit,25,100,0,2,Negative,FA
38,NaN,"20:3 (8Z,11Z,14Z)n-6,n-9",False,365.2,Unit,183,Unit,25,100,0,2,Negative,FA
39,NaN,"20:4 (5Z,8Z,11Z,14Z)n-6,n-9 / 20:5 (5Z,8Z,11Z,...",False,363.3,Unit,183,Unit,25,100,0,2,Negative,FA
40,NaN,11:0 / 15:1 (10Z)n-5 / 17:1 (10Z)n-7 / 12:1n-2...,False,353.3,Unit,183,Unit,25,100,0,2,Negative,FA
41,NaN,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6,n-9,n-12",False,349.2,Unit,183,Unit,25,100,0,2,Negative,FA
42,NaN,"10:0 / 18:2 (9Z,12Z)n-6,n-9 / 14:1 (9Z)n-5 / 1...",False,339.3,Unit,183,Unit,25,100,0,2,Negative,FA
43,NaN,"18:3 (6Z,9Z,12Z))n-6,n-9",False,337.2,Unit,183,Unit,25,100,0,2,Negative,FA
44,NaN,"20:3 (8Z,11Z,14Z)n-6,n-9,n-12 / 12:1n-4 / 13:1...",False,325.2,Unit,183,Unit,25,100,0,2,Negative,FA
45,NaN,"20:5 (5Z,8Z,11Z,14Z,17Z)n-3,n-6,n-9,n-12 / 20:...",False,323.2,Unit,183,Unit,25,100,0,2,Negative,FA
46,NaN,8:0 / 12:1n-5 / 13:1n-6 / 14:1n-7 / 15:1n-8 / ...,False,311.3,Unit,183,Unit,25,100,0,2,Negative,FA
47,NaN,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6,n-9,n-12,n-15",False,309.1,Unit,183,Unit,25,100,0,2,Negative,FA
48,NaN,"18:3 (6Z,9Z,12Z))n-6,n-9,n-12 / 12:1n-6 / 13:1...",False,297.2,Unit,183,Unit,25,100,0,2,Negative,FA
49,NaN,"6:0 / 20:5 (5Z,8Z,11Z,14Z,17Z)n-3,n-6,n-9,n-12...",False,283.2,Unit,183,Unit,25,100,0,2,Negative,FA
50,NaN,"22:6 (4Z,7Z,10Z,13Z,16Z,19Z)n-3,n-6,n-9,n-12,n...",False,269.1,Unit,183,Unit,25,100,0,2,Negative,FA
51,NaN,4:0 / 12:1n-9 / 13:1n-10 / 14:1n-11 / 15:1n-12...,False,255.2,Unit,183,Unit,25,100,0,2,Negative,FA
52,NaN,12:1n-10 / 13:1n-11 / 14:1n-12 / 15:1n-13 / 16...,False,241.1,Unit,183,Unit,25,100,0,2,Negative,FA
53,NaN,12:1n-11 / 13:1n-12 / 14:1n-13 / 15:1n-14 / 16...,False,227.1,Unit,183,Unit,25,100,0,2,Negative,FA
54,NaN,dummy,False,533.5,Unit,183,Unit,25,100,0,2,Negative,FA

# filter again with Caitln df

In [65]:
import pandas as pd
import numpy as np

def compare_and_filter_masses(caitlin_df, filtered_results, tolerance=0.3):
    """
    Compare Parent Ion masses between caitlin_df and filtered_results within a tolerance range
    and return both matching and non-matching results.
    
    Parameters:
    caitlin_df (pandas.DataFrame): DataFrame containing 'Parent Ion' column
    filtered_results (pandas.DataFrame): DataFrame containing 'Reference_Mass' column
    tolerance (float): Mass tolerance range (±) in Da/mz units
    
    Returns:
    tuple: (matching_df, non_matching_df) containing results that match/don't match caitlin_df values
    """
    def find_match(mass, reference_masses, tolerance):
        """Helper function to check if a mass has a match within tolerance"""
        return any(abs(mass - ref_mass) <= tolerance for ref_mass in reference_masses)
    
    # Get unique masses from both dataframes
    caitlin_masses = caitlin_df['Parent Ion'].unique()
    result_masses = filtered_results['Reference_Mass'].values
    
    # Create mask for matching masses
    mask = filtered_results['Reference_Mass'].apply(
        lambda x: find_match(x, caitlin_masses, tolerance)
    )
    
    # Split into matching and non-matching results
    matched_results = filtered_results[mask].copy()
    non_matched_results = filtered_results[~mask].copy()
    
    # Add information about matching to matched results
    matched_results['Matching_Caitlin_Masses'] = matched_results['Reference_Mass'].apply(
        lambda x: ', '.join([f"{m:.2f}" for m in caitlin_masses if abs(m - x) <= tolerance])
    )
    
    # Print summary
    print("\nMatching Summary:")
    print(f"Original number of masses in filtered_results: {len(filtered_results)}")
    print(f"Number of masses in caitlin_df: {len(caitlin_masses)}")
    print(f"Number of matching masses (within ±{tolerance} tolerance): {len(matched_results)}")
    print(f"Number of non-matching masses: {len(non_matched_results)}")
    
    # Also find caitlin masses that don't match any in filtered_results
    unmatched_caitlin_masses = [
        mass for mass in caitlin_masses 
        if not find_match(mass, filtered_results['Reference_Mass'], tolerance)
    ]
    
    print(f"\nNumber of caitlin masses without matches: {len(unmatched_caitlin_masses)}")
    if unmatched_caitlin_masses:
        print("Unmatched Caitlin masses:", ', '.join([f"{m:.2f}" for m in unmatched_caitlin_masses]))
    
    return matched_results, non_matched_results

# Example usage:
# matching_df, non_matching_df = compare_and_filter_masses(caitlin_df, filtered_results, tolerance=0.3)

In [66]:
# First ensure you have your previous results
results = analyze_mass_tolerance(grouped_df, tolerance=0.3)
filtered_results = filter_species_range(results)

# Then compare with caitlin_df and get both matching and non-matching results
matching_df, non_matching_df = compare_and_filter_masses(caitlin_df, filtered_results, tolerance=0.3)

# Display the matching results
print("\nMatching results:")
print(matching_df)

# Display the non-matching results
print("\nNon-matching results:")
print(non_matching_df)

# Save to CSV if needed:
# matching_df.to_csv('matching_results.csv', index=False)
# non_matching_df.to_csv('non_matching_results.csv', index=False)

# Get some statistics about the matches
print("\nMatching statistics:")
print(f"Average mass spread in matching groups: {matching_df['Mass_Spread'].mean():.3f}")
print(f"Average group size in matching groups: {matching_df['Group_Size'].mean():.1f}")

Matching Summary:
Original number of masses in filtered_results: 77
Number of masses in caitlin_df: 55
Number of matching masses (within ±0.3 tolerance): 15
Number of non-matching masses: 62

Number of caitlin masses without matches: 40
Unmatched Caitlin masses: 535.40, 533.40, 521.40, 507.40, 505.40, 503.40, 495.40, 493.40, 479.40, 477.40, 475.40, 473.40, 471.40, 469.40, 465.30, 451.40, 449.40, 447.40, 445.40, 443.30, 437.40, 435.40, 425.40, 423.30, 421.40, 419.30, 409.30, 407.30, 395.30, 393.40, 389.30, 381.30, 379.30, 367.30, 363.30, 353.30, 339.30, 311.30, 227.10, 533.50

Matching results:
    Reference_Mass  Group_Size       Mass_Range  Mass_Spread  \
0            241.2           3  241.20 - 241.40          0.2
4            255.3           3  255.30 - 255.50          0.2
9            269.3           3  269.30 - 269.50          0.2
16           283.3           3  283.30 - 283.50          0.2
25           297.3           3  297.30 - 297.50          0.2
34           309.3           3  309.30 - 309.50          0.2
43           323.3           3  323.30 - 323.50          0.2
44           325.3           3  325.30 - 325.50          0.2
53           337.3           3  337.30 - 337.50          0.2
60           349.3           3  349.30 - 349.50          0.2
69           365.3           3  365.30 - 365.50          0.2
73           377.3           3  377.30 - 377.50          0.2
79           403.3           3  403.30 - 403.50          0.2
80           405.3           3  405.30 - 405.50          0.2
85           429.3           3  429.30 - 429.50          0.2

               Mass_Values                                       Lipid_Values  \
0   241.20, 241.30, 241.40  FA(6:1)_<>_n-4|FA(6:2)_<F>_n-4|FA(6:3)_<FF>_n-...
4   255.30, 255.40, 255.50  FA(14:1)_<>_n-11|FA(14:2)_<F>_n-11|FA(14:3)_<F...
9   269.30, 269.40, 269.50  FA(5:0)|FA(14:1)_<>_n-10|FA(14:2)_<F>_n-10|FA(...
16  283.30, 283.40, 283.50  FA(6:0)|FA(14:1)_<>_n-9|FA(14:2)_<F>_n-9|FA(14...
25  297.30, 297.40, 297.50  FA(7:0)|FA(14:1)_<>_n-8|FA(14:2)_<F>_n-8|FA(14...
34  309.30, 309.40, 309.50  FA(14:2)_<B>_n-7|FA(14:3)_<BF>_n-7|FA(14:4)_<B...
43  323.30, 323.40, 323.50  FA(14:2)_<B>_n-6|FA(14:3)_<BF>_n-6|FA(14:4)_<B...
44  325.30, 325.40, 325.50  FA(9:0)|FA(14:1)_<>_n-6|FA(14:2)_<F>_n-6|FA(14...
53  337.30, 337.40, 337.50  FA(14:2)_<B>_n-5|FA(14:3)_<BF>_n-5|FA(14:4)_<B...
60  349.30, 349.40, 349.50  FA(14:3)_<BB>_n-4|FA(14:4)_<BBF>_n-4|FA(14:5)_...
69  365.30, 365.40, 365.50  FA(14:2)_<B>_n-3|FA(14:3)_<BF>_n-3|FA(14:4)_<B...
73  377.30, 377.40, 377.50  FA(14:3)_<BB>_n-2|FA(14:4)_<BBF>_n-2|FA(15:3)_...
79  403.30, 403.40, 403.50  FA(16:4)_<BBB>_n-2|FA(16:5)_<BBBF>_n-2|FA(17:4...
80  405.30, 405.40, 405.50  FA(16:3)_<BB>_n-2|FA(16:4)_<BBF>_n-2|FA(17:3)_...
85  429.30, 429.40, 429.50  FA(18:5)_<BBBB>_n-2|FA(18:6)_<BBBBF>_n-2|FA(19...

        Species_Values Matching_Caitlin_Masses
0    6:1 | 14:1 | 21:1                  241.10
4   14:1 | 21:1 | 28:1                  255.20
9    5:0 | 21:1 | 28:1                  269.10
16   6:0 | 21:1 | 28:1                  283.20
25   7:0 | 21:1 | 28:1                  297.20
34  14:2 | 21:2 | 28:2                  309.10
43  14:2 | 21:2 | 28:2                  323.20
44   9:0 | 21:1 | 28:1                  325.20
53  14:2 | 21:2 | 28:2                  337.20
60  14:3 | 21:3 | 28:3                  349.20
69  14:2 | 21:2 | 28:2                  365.20
73  14:3 | 21:3 | 28:3                  377.20
79  16:4 | 21:4 | 28:4                  403.20
80  16:3 | 21:3 | 28:3                  405.20
85  18:5 | 21:5 | 28:5                  429.20

Non-matching results:
     Reference_Mass  Group_Size       Mass_Range  Mass_Spread  \
2             253.2           3  253.20 - 253.40          0.2
5             265.2           3  265.20 - 265.40          0.2
7             267.2           3  267.20 - 267.40          0.2
10            277.2           3  277.20 - 277.40          0.2
12            279.2           3  279.20 - 279.40          0.2
14            281.2           3  281.20 - 281.40          0.2
17            289.2           3  289.20 - 289.40          0.2
19            291.2           3  291.20 - 291.40          0.2
21            293.2           3  293.20 - 293.40          0.2
23            295.2           3  295.20 - 295.40          0.2
26            301.2           3  301.20 - 301.40          0.2
28            303.2           3  303.20 - 303.40          0.2
30            305.2           3  305.20 - 305.40          0.2
32            307.2           3  307.20 - 307.40          0.2
35            315.2           3  315.20 - 315.40          0.2
37            317.2           3  317.20 - 317.40          0.2
39            319.2           3  319.20 - 319.40          0.2
41            321.2           3  321.20 - 321.40          0.2
45            329.2           3  329.20 - 329.40          0.2
47            331.2           3  331.20 - 331.40          0.2
49            333.2           3  333.20 - 333.40          0.2
51            335.2           3  335.20 - 335.40          0.2
54            343.2           3  343.20 - 343.40          0.2
56            345.2           3  345.20 - 345.40          0.2
58            347.2           3  347.20 - 347.40          0.2
61            351.2           3  351.20 - 351.40          0.2
63            357.2           3  357.20 - 357.40          0.2
65            359.2           3  359.20 - 359.40          0.2
67            361.2           3  361.20 - 361.40          0.2
70            371.3           3  371.30 - 371.50          0.2
71            373.3           3  373.30 - 373.50          0.2
72            375.3           3  375.30 - 375.50          0.2
74            385.3           3  385.30 - 385.50          0.2
75            387.3           3  387.30 - 387.50          0.2
76            391.3           3  391.30 - 391.50          0.2
77            399.3           3  399.30 - 399.50          0.2
78            401.3           3  401.30 - 401.50          0.2
81            413.3           3  413.30 - 413.50          0.2
82            415.3           3  415.30 - 415.50          0.2
83            417.3           3  417.30 - 417.50          0.2
84            427.3           3  427.30 - 427.50          0.2
86            431.3           3  431.30 - 431.50          0.2
87            433.3           3  433.30 - 433.50          0.2
88            441.3           3  441.30 - 441.50          0.2
89            455.3           3  455.30 - 455.50          0.2
90            457.3           3  457.30 - 457.50          0.2
91            459.3           3  459.30 - 459.50          0.2
92            461.3           3  461.30 - 461.50          0.2
93            463.3           3  463.30 - 463.50          0.2
94            483.4           2  483.40 - 483.50          0.1
95            485.4           2  485.40 - 485.50          0.1
96            487.4           2  487.40 - 487.50          0.1
97            489.4           2  489.40 - 489.50          0.1
98            491.4           2  491.40 - 491.50          0.1
99            497.4           2  497.40 - 497.50          0.1
100           499.4           2  499.40 - 499.50          0.1
101           501.4           2  501.40 - 501.50          0.1
102           511.4           2  511.40 - 511.50          0.1
103           513.4           2  513.40 - 513.50          0.1
104           515.4           2  515.40 - 515.50          0.1
105           517.4           2  517.40 - 517.50          0.1
106           519.4           2  519.40 - 519.50          0.1

                Mass_Values  \
2    253.20, 253.30, 253.40
5    265.20, 265.30, 265.40
7    267.20, 267.30, 267.40
10   277.20, 277.30, 277.40
12   279.20, 279.30, 279.40
14   281.20, 281.30, 281.40
17   289.20, 289.30, 289.40
19   291.20, 291.30, 291.40
21   293.20, 293.30, 293.40
23   295.20, 295.30, 295.40
26   301.20, 301.30, 301.40
28   303.20, 303.30, 303.40
30   305.20, 305.30, 305.40
32   307.20, 307.30, 307.40
35   315.20, 315.30, 315.40
37   317.20, 317.30, 317.40
39   319.20, 319.30, 319.40
41   321.20, 321.30, 321.40
45   329.20, 329.30, 329.40
47   331.20, 331.30, 331.40
49   333.20, 333.30, 333.40
51   335.20, 335.30, 335.40
54   343.20, 343.30, 343.40
56   345.20, 345.30, 345.40
58   347.20, 347.30, 347.40
61   351.20, 351.30, 351.40
63   357.20, 357.30, 357.40
65   359.20, 359.30, 359.40
67   361.20, 361.30, 361.40
70   371.30, 371.40, 371.50
71   373.30, 373.40, 373.50
72   375.30, 375.40, 375.50
74   385.30, 385.40, 385.50
75   387.30, 387.40, 387.50
76   391.30, 391.40, 391.50
77   399.30, 399.40, 399.50
78   401.30, 401.40, 401.50
81   413.30, 413.40, 413.50
82   415.30, 415.40, 415.50
83   417.30, 417.40, 417.50
84   427.30, 427.40, 427.50
86   431.30, 431.40, 431.50
87   433.30, 433.40, 433.50
88   441.30, 441.40, 441.50
89   455.30, 455.40, 455.50
90   457.30, 457.40, 457.50
91   459.30, 459.40, 459.50
92   461.30, 461.40, 461.50
93   463.30, 463.40, 463.50
94           483.40, 483.50
95           485.40, 485.50
96           487.40, 487.50
97           489.40, 489.50
98           491.40, 491.50
99           497.40, 497.50
100          499.40, 499.50
101          501.40, 501.50
102          511.40, 511.50
103          513.40, 513.50
104          515.40, 515.50
105          517.40, 517.50
106          519.40, 519.50

                                          Lipid_Values      Species_Values
2    FA(6:2)_<B>_n-3|FA(6:3)_<BF>_n-3|FA(6:4)_<BFF>...   6:2 | 14:2 | 21:2
5    FA(6:3)_<BB>_n-2|FA(6:4)_<BBF>_n-2|FA(7:3)_<BB...   6:3 | 14:3 | 21:3
7    FA(6:2)_<B>_n-2|FA(6:3)_<BF>_n-2|FA(7:2)_<B>_n...   6:2 | 14:2 | 21:2
10   FA(7:4)_<BBB>_n-2|FA(7:5)_<BBBF>_n-2|FA(8:4)_<...   7:4 | 14:4 | 21:4
12   FA(7:3)_<BB>_n-2|FA(7:4)_<BBF>_n-2|FA(8:3)_<BB...   7:3 | 14:3 | 21:3
14   FA(7:2)_<B>_n-2|FA(7:3)_<BF>_n-2|FA(8:2)_<B>_n...   7:2 | 14:2 | 21:2
17   FA(8:5)_<BBBB>_n-2|FA(8:6)_<BBBBF>_n-2|FA(9:5)...   8:5 | 14:5 | 21:5
19   FA(8:4)_<BBB>_n-2|FA(8:5)_<BBBF>_n-2|FA(9:4)_<...   8:4 | 14:4 | 21:4
21   FA(8:3)_<BB>_n-2|FA(8:4)_<BBF>_n-2|FA(9:3)_<BB...   8:3 | 14:3 | 21:3
23   FA(8:2)_<B>_n-2|FA(8:3)_<BF>_n-2|FA(9:2)_<B>_n...   8:2 | 14:2 | 21:2
26   FA(9:6)_<BBBBB>_n-2|FA(10:6)_<BBBBB>_n-3|FA(11...   9:6 | 14:6 | 21:6
28   FA(9:5)_<BBBB>_n-2|FA(9:6)_<BBBBF>_n-2|FA(10:5...   9:5 | 14:5 | 21:5
30   FA(9:4)_<BBB>_n-2|FA(9:5)_<BBBF>_n-2|FA(10:4)_...   9:4 | 14:4 | 21:4
32   FA(9:3)_<BB>_n-2|FA(9:4)_<BBF>_n-2|FA(10:3)_<B...   9:3 | 14:3 | 21:3
35   FA(10:6)_<BBBBB>_n-2|FA(11:6)_<BBBBB>_n-3|FA(1...  10:6 | 14:6 | 21:6
37   FA(10:5)_<BBBB>_n-2|FA(10:6)_<BBBBF>_n-2|FA(11...  10:5 | 14:5 | 21:5
39   FA(10:4)_<BBB>_n-2|FA(10:5)_<BBBF>_n-2|FA(11:4...  10:4 | 14:4 | 21:4
41   FA(10:3)_<BB>_n-2|FA(10:4)_<BBF>_n-2|FA(11:3)_...  10:3 | 14:3 | 21:3
45   FA(11:6)_<BBBBB>_n-2|FA(12:6)_<BBBBB>_n-3|FA(1...  11:6 | 14:6 | 21:6
47   FA(11:5)_<BBBB>_n-2|FA(11:6)_<BBBBF>_n-2|FA(12...  11:5 | 14:5 | 21:5
49   FA(11:4)_<BBB>_n-2|FA(11:5)_<BBBF>_n-2|FA(12:4...  11:4 | 14:4 | 21:4
51   FA(11:3)_<BB>_n-2|FA(11:4)_<BBF>_n-2|FA(12:3)_...  11:3 | 14:3 | 21:3
54   FA(12:6)_<BBBBB>_n-2|FA(13:6)_<BBBBB>_n-3|FA(1...  12:6 | 14:6 | 21:6
56   FA(12:5)_<BBBB>_n-2|FA(12:6)_<BBBBF>_n-2|FA(13...  12:5 | 14:5 | 21:5
58   FA(12:4)_<BBB>_n-2|FA(12:5)_<BBBF>_n-2|FA(13:4...  12:4 | 14:4 | 21:4
61   FA(12:2)_<B>_n-2|FA(12:3)_<BF>_n-2|FA(13:2)_<B...  12:2 | 14:2 | 21:2
63   FA(13:6)_<BBBBB>_n-2|FA(13:6)_<BBBBB>_n-2|FA(1...  13:6 | 14:6 | 21:6
65   FA(13:5)_<BBBB>_n-2|FA(13:6)_<BBBBF>_n-2|FA(13...  13:5 | 14:5 | 21:5
67   FA(13:4)_<BBB>_n-2|FA(13:5)_<BBBF>_n-2|FA(13:4...  13:4 | 14:4 | 21:4
70   FA(14:6)_<BBBBB>_n-2|FA(15:6)_<BBBBB>_n-3|FA(1...  14:6 | 21:6 | 28:6
71   FA(14:5)_<BBBB>_n-2|FA(14:6)_<BBBBF>_n-2|FA(15...  14:5 | 21:5 | 28:5
72   FA(14:4)_<BBB>_n-2|FA(14:5)_<BBBF>_n-2|FA(15:4...  14:4 | 21:4 | 28:4
74   FA(15:6)_<BBBBB>_n-2|FA(16:6)_<BBBBB>_n-3|FA(1...  15:6 | 21:6 | 28:6
75   FA(15:5)_<BBBB>_n-2|FA(15:6)_<BBBBF>_n-2|FA(16...  15:5 | 21:5 | 28:5
76   FA(15:3)_<BB>_n-2|FA(15:4)_<BBF>_n-2|FA(16:3)_...  15:3 | 21:3 | 28:3
77   FA(16:6)_<BBBBB>_n-2|FA(17:6)_<BBBBB>_n-3|FA(1...  16:6 | 21:6 | 28:6
78   FA(16:5)_<BBBB>_n-2|FA(16:6)_<BBBBF>_n-2|FA(17...  16:5 | 21:5 | 28:5
81   FA(17:6)_<BBBBB>_n-2|FA(18:6)_<BBBBB>_n-3|FA(1...  17:6 | 21:6 | 28:6
82   FA(17:5)_<BBBB>_n-2|FA(17:6)_<BBBBF>_n-2|FA(18...  17:5 | 21:5 | 28:5
83   FA(17:4)_<BBB>_n-2|FA(17:5)_<BBBF>_n-2|FA(18:4...  17:4 | 21:4 | 28:4
84   FA(18:6)_<BBBBB>_n-2|FA(19:6)_<BBBBB>_n-3|FA(2...  18:6 | 21:6 | 28:6
86   FA(18:4)_<BBB>_n-2|FA(18:5)_<BBBF>_n-2|FA(19:4...  18:4 | 21:4 | 28:4
87   FA(18:3)_<BB>_n-2|FA(18:4)_<BBF>_n-2|FA(19:3)_...  18:3 | 21:3 | 28:3
88   FA(19:6)_<BBBBB>_n-2|FA(20:6)_<BBBBB>_n-3|FA(1...  19:6 | 21:6 | 28:6
89   FA(20:6)_<BBBBB>_n-2|FA(20:6)_<BBBBB>_n-2|FA(2...  20:6 | 21:6 | 28:6
90   FA(20:5)_<BBBB>_n-2|FA(20:6)_<BBBBF>_n-2|FA(20...  20:5 | 21:5 | 28:5
91   FA(20:4)_<BBB>_n-2|FA(20:5)_<BBBF>_n-2|FA(20:4...  20:4 | 21:4 | 28:4
92   FA(20:3)_<BB>_n-2|FA(20:4)_<BBF>_n-2|FA(20:3)_...  20:3 | 21:3 | 28:3
93   FA(20:2)_<B>_n-2|FA(20:3)_<BF>_n-2|FA(20:2)_<B...  20:2 | 21:2 | 28:2
94   FA(22:6)_<BBBBB>_n-2|FA(23:6)_<BBBBB>_n-3|FA(2...         22:6 | 28:6
95   FA(22:5)_<BBBB>_n-2|FA(22:6)_<BBBBF>_n-2|FA(23...         22:5 | 28:5
96   FA(22:4)_<BBB>_n-2|FA(22:5)_<BBBF>_n-2|FA(23:4...         22:4 | 28:4
97   FA(22:3)_<BB>_n-2|FA(22:4)_<BBF>_n-2|FA(23:3)_...         22:3 | 28:3
98   FA(22:2)_<B>_n-2|FA(22:3)_<BF>_n-2|FA(23:2)_<B...         22:2 | 28:2
99   FA(23:6)_<BBBBB>_n-2|FA(24:6)_<BBBBB>_n-3|FA(2...         23:6 | 28:6
100  FA(23:5)_<BBBB>_n-2|FA(23:6)_<BBBBF>_n-2|FA(24...         23:5 | 28:5
101  FA(23:4)_<BBB>_n-2|FA(23:5)_<BBBF>_n-2|FA(24:4...         23:4 | 28:4
102  FA(24:6)_<BBBBB>_n-2|FA(25:6)_<BBBBB>_n-3|FA(2...         24:6 | 28:6
103  FA(24:5)_<BBBB>_n-2|FA(24:6)_<BBBBF>_n-2|FA(25...         24:5 | 28:5
104  FA(24:4)_<BBB>_n-2|FA(24:5)_<BBBF>_n-2|FA(25:4...         24:4 | 28:4
105  FA(24:3)_<BB>_n-2|FA(24:4)_<BBF>_n-2|FA(25:3)_...         24:3 | 28:3
106  FA(24:2)_<B>_n-2|FA(24:3)_<BF>_n-2|FA(25:2)_<B...         24:2 | 28:2

Matching statistics:
Average mass spread in matching groups: 0.200
Average group size in matching groups: 3.0

In [67]:
matching_df

,Reference_Mass,Group_Size,Mass_Range,Mass_Spread,Mass_Values,Lipid_Values,Species_Values,Matching_Caitlin_Masses
0,241.2,3,241.20 - 241.40,0.2,"241.20, 241.30, 241.40",FA(6:1)_<>_n-4|FA(6:2)_<F>_n-4|FA(6:3)_<FF>_n-...,6:1 | 14:1 | 21:1,241.10
4,255.3,3,255.30 - 255.50,0.2,"255.30, 255.40, 255.50",FA(14:1)_<>_n-11|FA(14:2)_<F>_n-11|FA(14:3)_<F...,14:1 | 21:1 | 28:1,255.20
9,269.3,3,269.30 - 269.50,0.2,"269.30, 269.40, 269.50",FA(5:0)|FA(14:1)_<>_n-10|FA(14:2)_<F>_n-10|FA(...,5:0 | 21:1 | 28:1,269.10
16,283.3,3,283.30 - 283.50,0.2,"283.30, 283.40, 283.50",FA(6:0)|FA(14:1)_<>_n-9|FA(14:2)_<F>_n-9|FA(14...,6:0 | 21:1 | 28:1,283.20
25,297.3,3,297.30 - 297.50,0.2,"297.30, 297.40, 297.50",FA(7:0)|FA(14:1)_<>_n-8|FA(14:2)_<F>_n-8|FA(14...,7:0 | 21:1 | 28:1,297.20
34,309.3,3,309.30 - 309.50,0.2,"309.30, 309.40, 309.50",FA(14:2)_<B>_n-7|FA(14:3)_<BF>_n-7|FA(14:4)_<B...,14:2 | 21:2 | 28:2,309.10
43,323.3,3,323.30 - 323.50,0.2,"323.30, 323.40, 323.50",FA(14:2)_<B>_n-6|FA(14:3)_<BF>_n-6|FA(14:4)_<B...,14:2 | 21:2 | 28:2,323.20
44,325.3,3,325.30 - 325.50,0.2,"325.30, 325.40, 325.50",FA(9:0)|FA(14:1)_<>_n-6|FA(14:2)_<F>_n-6|FA(14...,9:0 | 21:1 | 28:1,325.20
53,337.3,3,337.30 - 337.50,0.2,"337.30, 337.40, 337.50",FA(14:2)_<B>_n-5|FA(14:3)_<BF>_n-5|FA(14:4)_<B...,14:2 | 21:2 | 28:2,337.20
60,349.3,3,349.30 - 349.50,0.2,"349.30, 349.40, 349.50",FA(14:3)_<BB>_n-4|FA(14:4)_<BBF>_n-4|FA(14:5)_...,14:3 | 21:3 | 28:3,349.20
69,365.3,3,365.30 - 365.50,0.2,"365.30, 365.40, 365.50",FA(14:2)_<B>_n-3|FA(14:3)_<BF>_n-3|FA(14:4)_<B...,14:2 | 21:2 | 28:2,365.20
73,377.3,3,377.30 - 377.50,0.2,"377.30, 377.40, 377.50",FA(14:3)_<BB>_n-2|FA(14:4)_<BBF>_n-2|FA(15:3)_...,14:3 | 21:3 | 28:3,377.20
79,403.3,3,403.30 - 403.50,0.2,"403.30, 403.40, 403.50",FA(16:4)_<BBB>_n-2|FA(16:5)_<BBBF>_n-2|FA(17:4...,16:4 | 21:4 | 28:4,403.20
80,405.3,3,405.30 - 405.50,0.2,"405.30, 405.40, 405.50",FA(16:3)_<BB>_n-2|FA(16:4)_<BBF>_n-2|FA(17:3)_...,16:3 | 21:3 | 28:3,405.20
85,429.3,3,429.30 - 429.50,0.2,"429.30, 429.40, 429.50",FA(18:5)_<BBBB>_n-2|FA(18:6)_<BBBBF>_n-2|FA(19...,18:5 | 21:5 | 28:5,429.20

In [70]:
# save to excel
non_matching_df.to_excel('results/22Nov24_MissingMRMsToAddToMethod.xlsx', index=False)
non_matching_df

,Reference_Mass,Group_Size,Mass_Range,Mass_Spread,Mass_Values,Lipid_Values,Species_Values
2,253.2,3,253.20 - 253.40,0.2,"253.20, 253.30, 253.40",FA(6:2)_<B>_n-3|FA(6:3)_<BF>_n-3|FA(6:4)_<BFF>...,6:2 | 14:2 | 21:2
5,265.2,3,265.20 - 265.40,0.2,"265.20, 265.30, 265.40",FA(6:3)_<BB>_n-2|FA(6:4)_<BBF>_n-2|FA(7:3)_<BB...,6:3 | 14:3 | 21:3
7,267.2,3,267.20 - 267.40,0.2,"267.20, 267.30, 267.40",FA(6:2)_<B>_n-2|FA(6:3)_<BF>_n-2|FA(7:2)_<B>_n...,6:2 | 14:2 | 21:2
10,277.2,3,277.20 - 277.40,0.2,"277.20, 277.30, 277.40",FA(7:4)_<BBB>_n-2|FA(7:5)_<BBBF>_n-2|FA(8:4)_<...,7:4 | 14:4 | 21:4
12,279.2,3,279.20 - 279.40,0.2,"279.20, 279.30, 279.40",FA(7:3)_<BB>_n-2|FA(7:4)_<BBF>_n-2|FA(8:3)_<BB...,7:3 | 14:3 | 21:3
14,281.2,3,281.20 - 281.40,0.2,"281.20, 281.30, 281.40",FA(7:2)_<B>_n-2|FA(7:3)_<BF>_n-2|FA(8:2)_<B>_n...,7:2 | 14:2 | 21:2
17,289.2,3,289.20 - 289.40,0.2,"289.20, 289.30, 289.40",FA(8:5)_<BBBB>_n-2|FA(8:6)_<BBBBF>_n-2|FA(9:5)...,8:5 | 14:5 | 21:5
19,291.2,3,291.20 - 291.40,0.2,"291.20, 291.30, 291.40",FA(8:4)_<BBB>_n-2|FA(8:5)_<BBBF>_n-2|FA(9:4)_<...,8:4 | 14:4 | 21:4
21,293.2,3,293.20 - 293.40,0.2,"293.20, 293.30, 293.40",FA(8:3)_<BB>_n-2|FA(8:4)_<BBF>_n-2|FA(9:3)_<BB...,8:3 | 14:3 | 21:3
23,295.2,3,295.20 - 295.40,0.2,"295.20, 295.30, 295.40",FA(8:2)_<B>_n-2|FA(8:3)_<BF>_n-2|FA(9:2)_<B>_n...,8:2 | 14:2 | 21:2
26,301.2,3,301.20 - 301.40,0.2,"301.20, 301.30, 301.40",FA(9:6)_<BBBBB>_n-2|FA(10:6)_<BBBBB>_n-3|FA(11...,9:6 | 14:6 | 21:6
28,303.2,3,303.20 - 303.40,0.2,"303.20, 303.30, 303.40",FA(9:5)_<BBBB>_n-2|FA(9:6)_<BBBBF>_n-2|FA(10:5...,9:5 | 14:5 | 21:5
30,305.2,3,305.20 - 305.40,0.2,"305.20, 305.30, 305.40",FA(9:4)_<BBB>_n-2|FA(9:5)_<BBBF>_n-2|FA(10:4)_...,9:4 | 14:4 | 21:4
32,307.2,3,307.20 - 307.40,0.2,"307.20, 307.30, 307.40",FA(9:3)_<BB>_n-2|FA(9:4)_<BBF>_n-2|FA(10:3)_<B...,9:3 | 14:3 | 21:3
35,315.2,3,315.20 - 315.40,0.2,"315.20, 315.30, 315.40",FA(10:6)_<BBBBB>_n-2|FA(11:6)_<BBBBB>_n-3|FA(1...,10:6 | 14:6 | 21:6
37,317.2,3,317.20 - 317.40,0.2,"317.20, 317.30, 317.40",FA(10:5)_<BBBB>_n-2|FA(10:6)_<BBBBF>_n-2|FA(11...,10:5 | 14:5 | 21:5
39,319.2,3,319.20 - 319.40,0.2,"319.20, 319.30, 319.40",FA(10:4)_<BBB>_n-2|FA(10:5)_<BBBF>_n-2|FA(11:4...,10:4 | 14:4 | 21:4
41,321.2,3,321.20 - 321.40,0.2,"321.20, 321.30, 321.40",FA(10:3)_<BB>_n-2|FA(10:4)_<BBF>_n-2|FA(11:3)_...,10:3 | 14:3 | 21:3
45,329.2,3,329.20 - 329.40,0.2,"329.20, 329.30, 329.40",FA(11:6)_<BBBBB>_n-2|FA(12:6)_<BBBBB>_n-3|FA(1...,11:6 | 14:6 | 21:6
47,331.2,3,331.20 - 331.40,0.2,"331.20, 331.30, 331.40",FA(11:5)_<BBBB>_n-2|FA(11:6)_<BBBBF>_n-2|FA(12...,11:5 | 14:5 | 21:5
49,333.2,3,333.20 - 333.40,0.2,"333.20, 333.30, 333.40",FA(11:4)_<BBB>_n-2|FA(11:5)_<BBBF>_n-2|FA(12:4...,11:4 | 14:4 | 21:4
51,335.2,3,335.20 - 335.40,0.2,"335.20, 335.30, 335.40",FA(11:3)_<BB>_n-2|FA(11:4)_<BBF>_n-2|FA(12:3)_...,11:3 | 14:3 | 21:3
54,343.2,3,343.20 - 343.40,0.2,"343.20, 343.30, 343.40",FA(12:6)_<BBBBB>_n-2|FA(13:6)_<BBBBB>_n-3|FA(1...,12:6 | 14:6 | 21:6
56,345.2,3,345.20 - 345.40,0.2,"345.20, 345.30, 345.40",FA(12:5)_<BBBB>_n-2|FA(12:6)_<BBBBF>_n-2|FA(13...,12:5 | 14:5 | 21:5
58,347.2,3,347.20 - 347.40,0.2,"347.20, 347.30, 347.40",FA(12:4)_<BBB>_n-2|FA(12:5)_<BBBF>_n-2|FA(13:4...,12:4 | 14:4 | 21:4
61,351.2,3,351.20 - 351.40,0.2,"351.20, 351.30, 351.40",FA(12:2)_<B>_n-2|FA(12:3)_<BF>_n-2|FA(13:2)_<B...,12:2 | 14:2 | 21:2
63,357.2,3,357.20 - 357.40,0.2,"357.20, 357.30, 357.40",FA(13:6)_<BBBBB>_n-2|FA(13:6)_<BBBBB>_n-2|FA(1...,13:6 | 14:6 | 21:6
65,359.2,3,359.20 - 359.40,0.2,"359.20, 359.30, 359.40",FA(13:5)_<BBBB>_n-2|FA(13:6)_<BBBBF>_n-2|FA(13...,13:5 | 14:5 | 21:5
67,361.2,3,361.20 - 361.40,0.2,"361.20, 361.30, 361.40",FA(13:4)_<BBB>_n-2|FA(13:5)_<BBBF>_n-2|FA(13:4...,13:4 | 14:4 | 21:4
70,371.3,3,371.30 - 371.50,0.2,"371.30, 371.40, 371.50",FA(14:6)_<BBBBB>_n-2|FA(15:6)_<BBBBB>_n-3|FA(1...,14:6 | 21:6 | 28:6
71,373.3,3,373.30 - 373.50,0.2,"373.30, 373.40, 373.50",FA(14:5)_<BBBB>_n-2|FA(14:6)_<BBBBF>_n-2|FA(15...,14:5 | 21:5 | 28:5
72,375.3,3,375.30 - 375.50,0.2,"375.30, 375.40, 375.50",FA(14:4)_<BBB>_n-2|FA(14:5)_<BBBF>_n-2|FA(15:4...,14:4 | 21:4 | 28:4
74,385.3,3,385.30 - 385.50,0.2,"385.30, 385.40, 385.50",FA(15:6)_<BBBBB>_n-2|FA(16:6)_<BBBBB>_n-3|FA(1...,15:6 | 21:6 | 28:6
75,387.3,3,387.30 - 387.50,0.2,"387.30, 387.40, 387.50",FA(15:5)_<BBBB>_n-2|FA(15:6)_<BBBBF>_n-2|FA(16...,15:5 | 21:5 | 28:5
76,391.3,3,391.30 - 391.50,0.2,"391.30, 391.40, 391.50",FA(15:3)_<BB>_n-2|FA(15:4)_<BBF>_n-2|FA(16:3)_...,15:3 | 21:3 | 28:3
77,399.3,3,399.30 - 399.50,0.2,"399.30, 399.40, 399.50",FA(16:6)_<BBBBB>_n-2|FA(17:6)_<BBBBB>_n-3|FA(1...,16:6 | 21:6 | 28:6
78,401.3,3,401.30 - 401.50,0.2,"401.30, 401.40, 401.50",FA(16:5)_<BBBB>_n-2|FA(16:6)_<BBBBF>_n-2|FA(17...,16:5 | 21:5 | 28:5
81,413.3,3,413.30 - 413.50,0.2,"413.30, 413.40, 413.50",FA(17:6)_<BBBBB>_n-2|FA(18:6)_<BBBBB>_n-3|FA(1...,17:6 | 21:6 | 28:6
82,415.3,3,415.30 - 415.50,0.2,"415.30, 415.40, 415.50",FA(17:5)_<BBBB>_n-2|FA(17:6)_<BBBBF>_n-2|FA(18...,17:5 | 21:5 | 28:5
83,417.3,3,417.30 - 417.50,0.2,"417.30, 417.40, 417.50",FA(17:4)_<BBB>_n-2|FA(17:5)_<BBBF>_n-2|FA(18:4...,17:4 | 21:4 | 28:4
84,427.3,3,427.30 - 427.50,0.2,"427.30, 427.40, 427.50",FA(18:6)_<BBBBB>_n-2|FA(19:6)_<BBBBB>_n-3|FA(2...,18:6 | 21:6 | 28:6
86,431.3,3,431.30 - 431.50,0.2,"431.30, 431.40, 431.50",FA(18:4)_<BBB>_n-2|FA(18:5)_<BBBF>_n-2|FA(19:4...,18:4 | 21:4 | 28:4
87,433.3,3,433.30 - 433.50,0.2,"433.30, 433.40, 433.50",FA(18:3)_<BB>_n-2|FA(18:4)_<BBF>_n-2|FA(19:3)_...,18:3 | 21:3 | 28:3
88,441.3,3,441.30 - 441.50,0.2,"441.30, 441.40, 441.50",FA(19:6)_<BBBBB>_n-2|FA(20:6)_<BBBBB>_n-3|FA(1...,19:6 | 21:6 | 28:6
89,455.3,3,455.30 - 455.50,0.2,"455.30, 455.40, 455.50",FA(20:6)_<BBBBB>_n-2|FA(20:6)_<BBBBB>_n-2|FA(2...,20:6 | 21:6 | 28:6
90,457.3,3,457.30 - 457.50,0.2,"457.30, 457.40, 457.50",FA(20:5)_<BBBB>_n-2|FA(20:6)_<BBBBF>_n-2|FA(20...,20:5 | 21:5 | 28:5
91,459.3,3,459.30 - 459.50,0.2,"459.30, 459.40, 459.50",FA(20:4)_<BBB>_n-2|FA(20:5)_<BBBF>_n-2|FA(20:4...,20:4 | 21:4 | 28:4
92,461.3,3,461.30 - 461.50,0.2,"461.30, 461.40, 461.50",FA(20:3)_<BB>_n-2|FA(20:4)_<BBF>_n-2|FA(20:3)_...,20:3 | 21:3 | 28:3
93,463.3,3,463.30 - 463.50,0.2,"463.30, 463.40, 463.50",FA(20:2)_<B>_n-2|FA(20:3)_<BF>_n-2|FA(20:2)_<B...,20:2 | 21:2 | 28:2
94,483.4,2,483.40 - 483.50,0.1,"483.40, 483.50",FA(22:6)_<BBBBB>_n-2|FA(23:6)_<BBBBB>_n-3|FA(2...,22:6 | 28:6
95,485.4,2,485.40 - 485.50,0.1,"485.40, 485.50",FA(22:5)_<BBBB>_n-2|FA(22:6)_<BBBBF>_n-2|FA(23...,22:5 | 28:5
96,487.4,2,487.40 - 487.50,0.1,"487.40, 487.50",FA(22:4)_<BBB>_n-2|FA(22:5)_<BBBF>_n-2|FA(23:4...,22:4 | 28:4
97,489.4,2,489.40 - 489.50,0.1,"489.40, 489.50",FA(22:3)_<BB>_n-2|FA(22:4)_<BBF>_n-2|FA(23:3)_...,22:3 | 28:3
98,491.4,2,491.40 - 491.50,0.1,"491.40, 491.50",FA(22:2)_<B>_n-2|FA(22:3)_<BF>_n-2|FA(23:2)_<B...,22:2 | 28:2
99,497.4,2,497.40 - 497.50,0.1,"497.40, 497.50",FA(23:6)_<BBBBB>_n-2|FA(24:6)_<BBBBB>_n-3|FA(2...,23:6 | 28:6
100,499.4,2,499.40 - 499.50,0.1,"499.40, 499.50",FA(23:5)_<BBBB>_n-2|FA(23:6)_<BBBBF>_n-2|FA(24...,23:5 | 28:5
101,501.4,2,501.40 - 501.50,0.1,"501.40, 501.50",FA(23:4)_<BBB>_n-2|FA(23:5)_<BBBF>_n-2|FA(24:4...,23:4 | 28:4
102,511.4,2,511.40 - 511.50,0.1,"511.40, 511.50",FA(24:6)_<BBBBB>_n-2|FA(25:6)_<BBBBB>_n-3|FA(2...,24:6 | 28:6
103,513.4,2,513.40 - 513.50,0.1,"513.40, 513.50",FA(24:5)_<BBBB>_n-2|FA(24:6)_<BBBBF>_n-2|FA(25...,24:5 | 28:5
104,515.4,2,515.40 - 515.50,0.1,"515.40, 515.50",FA(24:4)_<BBB>_n-2|FA(24:5)_<BBBF>_n-2|FA(25:4...,24:4 | 28:4
105,517.4,2,517.40 - 517.50,0.1,"517.40, 517.50",FA(24:3)_<BB>_n-2|FA(24:4)_<BBF>_n-2|FA(25:3)_...,24:3 | 28:3
106,519.4,2,519.40 - 519.50,0.1,"519.40, 519.50",FA(24:2)_<B>_n-2|FA(24:3)_<BF>_n-2|FA(25:2)_<B...,24:2 | 28:2