# CT ON

In [1]:
import pandas as pd

# 1 mzml parse

In [4]:
!sbatch core/backend/CT/ON/mzml_parser_1_CT_ON.sh

Submitted batch job 22133724

In [5]:
df_mzml = pd.read_parquet('Projects/CT/mzml_parsed/ON/mzml_parser_1_CT_ON.parquet')
df_mzml

,Lipid,Parent_Ion,Product_Ion,Retention_Time,OzESI_Intensity,Sample_ID,Transition
0,None,227.1,183.0,3.019117,41.680004,01162025_Blank_AMP_OzoneOn_01,227.1 -> 183.0
1,None,227.1,183.0,3.034933,41.420002,01162025_Blank_AMP_OzoneOn_01,227.1 -> 183.0
2,None,227.1,183.0,3.050783,41.220001,01162025_Blank_AMP_OzoneOn_01,227.1 -> 183.0
3,None,227.1,183.0,3.066633,41.180004,01162025_Blank_AMP_OzoneOn_01,227.1 -> 183.0
4,None,227.1,183.0,3.082500,41.380001,01162025_Blank_AMP_OzoneOn_01,227.1 -> 183.0
...,...,...,...,...,...,...,...
419662,None,533.5,183.0,31.933100,41.700005,01162025_CisTransMix_AMP_OzoneOn_01,533.5 -> 183.0
419663,None,533.5,183.0,31.948950,41.660004,01162025_CisTransMix_AMP_OzoneOn_01,533.5 -> 183.0
419664,None,533.5,183.0,31.964800,41.480003,01162025_CisTransMix_AMP_OzoneOn_01,533.5 -> 183.0
419665,None,533.5,183.0,31.980650,41.200005,01162025_CisTransMix_AMP_OzoneOn_01,533.5 -> 183.0
419666,None,533.5,183.0,31.996500,41.560001,01162025_CisTransMix_AMP_OzoneOn_01,533.5 -> 183.0

In [6]:
df_mzml = pd.read_parquet('Projects/CT/mzml_parsed/ON/transitions/mzml_transition_summed_1_CT_ON.parquet')
df_mzml

,Parent_Ion,Product_Ion,Intensity,Transition,Sample_ID
0,227.1,183.0,73934.065178,227.1 -> 183.0,01162025_Blank_AMP_OzoneOn_01
1,241.1,183.0,73392.765186,241.1 -> 183.0,01162025_Blank_AMP_OzoneOn_01
2,253.2,183.0,73063.645134,253.2 -> 183.0,01162025_Blank_AMP_OzoneOn_01
3,255.2,183.0,73782.185234,255.2 -> 183.0,01162025_Blank_AMP_OzoneOn_01
4,265.2,183.0,72824.785095,265.2 -> 183.0,01162025_Blank_AMP_OzoneOn_01
...,...,...,...,...,...
229,519.4,183.0,76653.565327,519.4 -> 183.0,01162025_CisTransMix_AMP_OzoneOn_01
230,521.4,183.0,77980.745449,521.4 -> 183.0,01162025_CisTransMix_AMP_OzoneOn_01
231,533.4,183.0,77182.145420,533.4 -> 183.0,01162025_CisTransMix_AMP_OzoneOn_01
232,535.4,183.0,77307.765453,535.4 -> 183.0,01162025_CisTransMix_AMP_OzoneOn_01
233,533.5,183.0,75748.665382,533.5 -> 183.0,01162025_CisTransMix_AMP_OzoneOn_01

# 2 Sample

In [13]:
!sbatch core/backend/CT/ON/sample_2_CT_ON.sh

Submitted batch job 22135332

In [14]:
df_sample = pd.read_parquet('Projects/CT/samples/ON/df_sample_2_CisTrans_ON.parquet')
df_sample

,Lipid,Parent_Ion,Product_Ion,Retention_Time,OzESI_Intensity,Sample_ID,Transition,Sample,STD,STD_RT_ON,STD_Peak_Intensity,STD_Peak_Area
0,None,227.1,183.0,3.019117,41.560001,01162025_CisTransMix_AMP_OzoneOn_01,227.1 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804
1,None,227.1,183.0,3.034933,63.960003,01162025_CisTransMix_AMP_OzoneOn_01,227.1 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804
2,None,227.1,183.0,3.050783,67.240005,01162025_CisTransMix_AMP_OzoneOn_01,227.1 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804
3,None,227.1,183.0,3.066633,63.960003,01162025_CisTransMix_AMP_OzoneOn_01,227.1 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804
4,None,227.1,183.0,3.082500,41.420002,01162025_CisTransMix_AMP_OzoneOn_01,227.1 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804
...,...,...,...,...,...,...,...,...,...,...,...,...
214013,None,533.5,183.0,31.933100,41.700005,01162025_CisTransMix_AMP_OzoneOn_01,533.5 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804
214014,None,533.5,183.0,31.948950,41.660004,01162025_CisTransMix_AMP_OzoneOn_01,533.5 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804
214015,None,533.5,183.0,31.964800,41.480003,01162025_CisTransMix_AMP_OzoneOn_01,533.5 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804
214016,None,533.5,183.0,31.980650,41.200005,01162025_CisTransMix_AMP_OzoneOn_01,533.5 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804
214017,None,533.5,183.0,31.996500,41.560001,01162025_CisTransMix_AMP_OzoneOn_01,533.5 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804

# 3 Match

In [28]:
!sbatch core/backend/CT/ON/match_3_CT_ON.sh

Submitted batch job 22135546

In [29]:
df_match = pd.read_parquet('Projects/CT/match/ON/df_match_3_CisTrans.parquet')
df_match

,Lipid,Parent_Ion,Product_Ion,Retention_Time,OzESI_Intensity,Sample_ID,Transition,Sample,STD,STD_RT_ON,STD_Peak_Intensity,STD_Peak_Area,STD_RT_Dif,Adjusted_RT,Species,Class,STD_RT_OFF
0,,227.1,183.0,4.984683,42.0,01162025_CisTransMix_AMP_OzoneOn_01,227.1 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804,0.0,4.984683,6:2,,10.5243
1,,227.1,183.0,5.000533,42.0,01162025_CisTransMix_AMP_OzoneOn_01,227.1 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804,0.0,5.000533,6:2,,10.5243
2,,227.1,183.0,5.016383,42.0,01162025_CisTransMix_AMP_OzoneOn_01,227.1 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804,0.0,5.016383,6:2,,10.5243
3,,227.1,183.0,5.032233,42.0,01162025_CisTransMix_AMP_OzoneOn_01,227.1 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804,0.0,5.032233,6:2,,10.5243
4,,227.1,183.0,5.048083,41.0,01162025_CisTransMix_AMP_OzoneOn_01,227.1 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804,0.0,5.048083,6:2,,10.5243
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155031,,533.5,183.0,20.424933,42.0,01162025_CisTransMix_AMP_OzoneOn_01,533.5 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804,0.0,20.424933,22:0,,10.5243
155032,,533.5,183.0,20.440783,41.0,01162025_CisTransMix_AMP_OzoneOn_01,533.5 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804,0.0,20.440783,22:0,,10.5243
155033,,533.5,183.0,20.456650,41.0,01162025_CisTransMix_AMP_OzoneOn_01,533.5 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804,0.0,20.456650,22:0,,10.5243
155034,,533.5,183.0,20.472500,41.0,01162025_CisTransMix_AMP_OzoneOn_01,533.5 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804,0.0,20.472500,22:0,,10.5243
155035,,533.5,183.0,20.488350,41.0,01162025_CisTransMix_AMP_OzoneOn_01,533.5 -> 183.0,CisTrans,None,10.5243,1963.240112,187.813804,0.0,20.488350,22:0,,10.5243

In [30]:
unique_lipids = df_match['Lipid'].unique()
print(unique_lipids)

[''
 'FA(6:2)_<F>_n-4 | FA(6:3)_<FF>_n-4 | FA(7:2)_<F>_n-5 | FA(18:1)_<>_n-16 | FA(18:2)_<F>_n-16 | FA(18:3)_<FF>_n-16'
 'FA(6:2)_<B>_n-3 | FA(6:3)_<BF>_n-3 | FA(7:2)_<B>_n-4 | FA(18:2)_<B>_n-15 | FA(18:3)_<BF>_n-15'
 'FA(6:2)_<F>_n-3 | FA(6:3)_<FF>_n-3 | FA(7:2)_<F>_n-4 | FA(18:1)_<>_n-15 | FA(18:2)_<F>_n-15 | FA(18:3)_<FF>_n-15'
 'FA(6:3)_<BB>_n-2 | FA(18:3)_<BB>_n-14'
 'FA(6:2)_<B>_n-2 | FA(6:3)_<BF>_n-2 | FA(7:2)_<B>_n-3 | FA(18:2)_<B>_n-14 | FA(18:3)_<BF>_n-14'
 'FA(6:2)_<F>_n-2 | FA(7:2)_<F>_n-3 | FA(18:1)_<>_n-14 | FA(18:2)_<F>_n-14 | FA(18:3)_<FF>_n-14'
 'FA(18:3)_<BB>_n-13'
 'FA(7:2)_<B>_n-2 | FA(18:2)_<B>_n-13 | FA(18:3)_<BF>_n-13'
 'FA(7:2)_<F>_n-2 | FA(18:1)_<>_n-13 | FA(18:2)_<F>_n-13 | FA(18:3)_<FF>_n-13'
 'FA(18:3)_<BB>_n-12' 'FA(18:2)_<B>_n-12 | FA(18:3)_<BF>_n-12'
 'FA(18:1)_<>_n-12 | FA(18:2)_<F>_n-12 | FA(18:3)_<FF>_n-12'
 'FA(18:3)_<BB>_n-11' 'FA(18:2)_<B>_n-11 | FA(18:3)_<BF>_n-11'
 'FA(18:1)_<>_n-11 | FA(18:2)_<F>_n-11 | FA(18:3)_<FF>_n-11'
 'FA(18:3)_<BB>_n-10' 'FA(18:2)_<B>_n-10 | FA(18:3)_<BF>_n-10'
 'FA(18:1)_<>_n-10 | FA(18:2)_<F>_n-10 | FA(18:3)_<FF>_n-10'
 'FA(18:3)_<BB>_n-9' 'FA(18:2)_<B>_n-9 | FA(18:3)_<BF>_n-9'
 'FA(18:1)_<>_n-9 | FA(18:2)_<F>_n-9 | FA(18:3)_<FF>_n-9'
 'FA(18:3)_<BB>_n-8' 'FA(18:2)_<B>_n-8 | FA(18:3)_<BF>_n-8'
 'FA(18:1)_<>_n-8 | FA(18:2)_<F>_n-8 | FA(18:3)_<FF>_n-8'
 'FA(18:3)_<BB>_n-7' 'FA(18:2)_<B>_n-7 | FA(18:3)_<BF>_n-7'
 'FA(18:1)_<>_n-7 | FA(18:2)_<F>_n-7 | FA(18:3)_<FF>_n-7'
 'FA(18:3)_<BB>_n-6' 'FA(18:2)_<B>_n-6 | FA(18:3)_<BF>_n-6'
 'FA(18:1)_<>_n-6 | FA(18:2)_<F>_n-6 | FA(18:3)_<FF>_n-6'
 'FA(18:3)_<BB>_n-5' 'FA(18:2)_<B>_n-5 | FA(18:3)_<BF>_n-5'
 'FA(18:1)_<>_n-5 | FA(18:2)_<F>_n-5 | FA(18:3)_<FF>_n-5'
 'FA(18:3)_<BB>_n-4' 'FA(18:2)_<B>_n-4 | FA(18:3)_<BF>_n-4'
 'FA(18:1)_<>_n-4 | FA(18:2)_<F>_n-4 | FA(18:3)_<FF>_n-4'
 'FA(18:3)_<BB>_n-3' 'FA(18:2)_<B>_n-3 | FA(18:3)_<BF>_n-3'
 'FA(16:0) | FA(18:1)_<>_n-3 | FA(18:2)_<F>_n-3 | FA(18:3)_<FF>_n-3'
 'FA(18:3)_<BB>_n-2' 'FA(18:2)_<B>_n-2 | FA(18:3)_<BF>_n-2'
 'FA(18:1)_<>_n-2 | FA(18:2)_<F>_n-2' 'FA(18:0)' 'FA(20:0)' 'FA(22:0)']

# 4 Group

In [31]:
!sbatch core/backend/CT/ON/group_4_CT_ON.sh

Submitted batch job 22135554

In [32]:
df_group = pd.read_parquet('Projects/CT/group/ON/df_group_4_CisTrans.parquet')
df_group

,Lipid,Parent_Ion,Product_Ion,Retention_Time,OzESI_Intensity,Sample_ID,Transition,Sample,STD,STD_RT_ON,...,Species,Class,STD_RT_OFF,Possible_Lipids,Biology,Genotype,Cage,Mouse,group_by_ion,group_by_lipid
0,FA(18:1)_<>_n-10,325.2,183.0,10.798967,41.0,01162025_CisTransMix_AMP_OzoneOn_01,325.2 -> 183.0,CisTrans,None,10.5243,...,18:1,FA,10.5243,FA(18:1)_<>_n-10 | FA(18:2)_<F>_n-10 | FA(18:3...,,,,,17,0
1,FA(18:1)_<>_n-10,325.2,183.0,10.814817,41.0,01162025_CisTransMix_AMP_OzoneOn_01,325.2 -> 183.0,CisTrans,None,10.5243,...,18:1,FA,10.5243,FA(18:1)_<>_n-10 | FA(18:2)_<F>_n-10 | FA(18:3...,,,,,17,0
2,FA(18:1)_<>_n-10,325.2,183.0,10.830667,41.0,01162025_CisTransMix_AMP_OzoneOn_01,325.2 -> 183.0,CisTrans,None,10.5243,...,18:1,FA,10.5243,FA(18:1)_<>_n-10 | FA(18:2)_<F>_n-10 | FA(18:3...,,,,,17,0
3,FA(18:1)_<>_n-10,325.2,183.0,10.846517,42.0,01162025_CisTransMix_AMP_OzoneOn_01,325.2 -> 183.0,CisTrans,None,10.5243,...,18:1,FA,10.5243,FA(18:1)_<>_n-10 | FA(18:2)_<F>_n-10 | FA(18:3...,,,,,17,0
4,FA(18:1)_<>_n-10,325.2,183.0,10.862367,42.0,01162025_CisTransMix_AMP_OzoneOn_01,325.2 -> 183.0,CisTrans,None,10.5243,...,18:1,FA,10.5243,FA(18:1)_<>_n-10 | FA(18:2)_<F>_n-10 | FA(18:3...,,,,,17,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16165,FA(7:2)_<F>_n-5,241.1,183.0,4.810200,42.0,01162025_CisTransMix_AMP_OzoneOn_01,241.1 -> 183.0,CisTrans,None,10.5243,...,7:2,FA,10.5243,FA(6:2)_<F>_n-4 | FA(6:3)_<FF>_n-4 | FA(7:2)_<...,,,,,0,101
16166,FA(7:2)_<F>_n-5,241.1,183.0,4.826050,42.0,01162025_CisTransMix_AMP_OzoneOn_01,241.1 -> 183.0,CisTrans,None,10.5243,...,7:2,FA,10.5243,FA(6:2)_<F>_n-4 | FA(6:3)_<FF>_n-4 | FA(7:2)_<...,,,,,0,101
16167,FA(7:2)_<F>_n-5,241.1,183.0,4.841900,42.0,01162025_CisTransMix_AMP_OzoneOn_01,241.1 -> 183.0,CisTrans,None,10.5243,...,7:2,FA,10.5243,FA(6:2)_<F>_n-4 | FA(6:3)_<FF>_n-4 | FA(7:2)_<...,,,,,0,101
16168,FA(7:2)_<F>_n-5,241.1,183.0,4.857750,42.0,01162025_CisTransMix_AMP_OzoneOn_01,241.1 -> 183.0,CisTrans,None,10.5243,...,7:2,FA,10.5243,FA(6:2)_<F>_n-4 | FA(6:3)_<FF>_n-4 | FA(7:2)_<...,,,,,0,101
16169,FA(7:2)_<F>_n-5,241.1,183.0,4.873600,42.0,01162025_CisTransMix_AMP_OzoneOn_01,241.1 -> 183.0,CisTrans,None,10.5243,...,7:2,FA,10.5243,FA(6:2)_<F>_n-4 | FA(6:3)_<FF>_n-4 | FA(7:2)_<...,,,,,0,101

In [33]:
# print all column names
print(df_group.columns)

Index(['Lipid', 'Parent_Ion', 'Product_Ion', 'Retention_Time',
       'OzESI_Intensity', 'Sample_ID', 'Transition', 'Sample', 'STD',
       'STD_RT_ON', 'STD_Peak_Intensity', 'STD_Peak_Area', 'STD_RT_Dif',
       'Adjusted_RT', 'Species', 'Class', 'STD_RT_OFF', 'Possible_Lipids',
       'Biology', 'Genotype', 'Cage', 'Mouse', 'group_by_ion',
       'group_by_lipid'],
      dtype='object')

# 5 analysis

In [34]:
!sbatch core/backend/CT/ON/analysis_5_CT_ON.sh

Submitted batch job 22135571

In [35]:
df_analysis = pd.read_parquet('Projects/CT/analysis/ON/df_analysis_5_CisTrans.parquet')
df_analysis

,Lipid,Retention_Time,OzESI_Intensity,group_by_ion,group_by_lipid,Sample_ID,Transition,Sample,Parent_Ion,Product_Ion,...,Slope_Right,Asymmetry_Factor,Baseline_Drift,Shoulder_Count,Biology,Genotype,Cage,Mouse,Normalized_Peak_Area,n_value
0,FA(18:1)_<>_n-2,11.664867,919.0,41,7,01162025_CisTransMix_AMP_OzoneOn_01,437.4 -> 183.0,CisTrans,437.4,183.0,...,-4164.037855,2.000000,-1898.467511,2,,,,,0.418570,2
1,FA(18:1)_<>_n-2,11.696567,787.0,41,7,01162025_CisTransMix_AMP_OzoneOn_01,437.4 -> 183.0,CisTrans,437.4,183.0,...,-12239.747634,1.000000,7129.337539,0,,,,,0.061648,2
2,FA(18:1)_<>_n-3,11.665717,1452.0,38,8,01162025_CisTransMix_AMP_OzoneOn_01,423.3 -> 183.0,CisTrans,423.3,183.0,...,-6529.968454,2.000000,1576.688517,1,,,,,0.635683,3
3,FA(18:1)_<>_n-4,11.317717,885.0,35,9,01162025_CisTransMix_AMP_OzoneOn_01,409.3 -> 183.0,CisTrans,409.3,183.0,...,-8886.885985,1.000000,796.987891,1,,,,,0.289043,4
4,FA(18:1)_<>_n-4,11.698150,2496.0,35,9,01162025_CisTransMix_AMP_OzoneOn_01,409.3 -> 183.0,CisTrans,409.3,183.0,...,-23343.848580,1.272727,815.201637,1,,,,,1.135327,4
5,FA(18:1)_<>_n-5,11.255050,1352.0,32,10,01162025_CisTransMix_AMP_OzoneOn_01,395.3 -> 183.0,CisTrans,395.3,183.0,...,-1838.666066,1.800000,1921.403178,1,,,,,0.652568,5
6,FA(18:1)_<>_n-5,11.683033,7761.0,32,10,01162025_CisTransMix_AMP_OzoneOn_01,395.3 -> 183.0,CisTrans,395.3,183.0,...,-27634.069401,1.125000,19531.115572,1,,,,,2.640291,5
7,FA(18:1)_<>_n-5,11.825700,626.0,32,10,01162025_CisTransMix_AMP_OzoneOn_01,395.3 -> 183.0,CisTrans,395.3,183.0,...,-10000.000000,0.500000,10662.460568,0,,,,,0.045698,5
8,FA(18:1)_<>_n-6,11.255767,2105.0,29,11,01162025_CisTransMix_AMP_OzoneOn_01,381.3 -> 183.0,CisTrans,381.3,183.0,...,-33384.407391,0.454545,4182.619593,1,,,,,1.095198,6
9,FA(18:1)_<>_n-6,11.667900,10163.0,29,11,01162025_CisTransMix_AMP_OzoneOn_01,381.3 -> 183.0,CisTrans,381.3,183.0,...,-72597.408479,1.500000,-2882.844629,1,,,,,4.060775,6
10,FA(18:1)_<>_n-7,11.256500,1450.0,26,12,01162025_CisTransMix_AMP_OzoneOn_01,367.3 -> 183.0,CisTrans,367.3,183.0,...,-11266.336187,0.777778,2521.439076,1,,,,,0.724706,7
11,FA(18:1)_<>_n-7,11.700333,15396.0,26,12,01162025_CisTransMix_AMP_OzoneOn_01,367.3 -> 183.0,CisTrans,367.3,183.0,...,-145993.690852,1.750000,-25656.545741,1,,,,,6.321263,7
12,FA(18:1)_<>_n-8,11.273067,3767.0,23,13,01162025_CisTransMix_AMP_OzoneOn_01,353.3 -> 183.0,CisTrans,353.3,183.0,...,-52942.767012,1.000000,13275.669075,1,,,,,1.144526,8
13,FA(18:1)_<>_n-8,11.748617,21766.0,23,13,01162025_CisTransMix_AMP_OzoneOn_01,353.3 -> 183.0,CisTrans,353.3,183.0,...,-137539.432177,1.300000,-24011.333141,1,,,,,8.857493,8
14,FA(18:1)_<>_n-8,12.018083,502.0,23,13,01162025_CisTransMix_AMP_OzoneOn_01,353.3 -> 183.0,CisTrans,353.3,183.0,...,-4542.586751,0.600000,757.671351,1,,,,,0.149416,8
15,FA(18:1)_<>_n-9,11.321350,32542.0,20,14,01162025_CisTransMix_AMP_OzoneOn_01,339.3 -> 183.0,CisTrans,339.3,183.0,...,-274664.263182,1.400000,74469.815360,1,,,,,12.492208,9
16,FA(18:1)_<>_n-9,11.590817,733.0,20,14,01162025_CisTransMix_AMP_OzoneOn_01,339.3 -> 183.0,CisTrans,339.3,183.0,...,-220.820189,0.500000,2965.299685,0,,,,,0.059876,9
17,FA(18:1)_<>_n-9,11.622517,726.0,20,14,01162025_CisTransMix_AMP_OzoneOn_01,339.3 -> 183.0,CisTrans,339.3,183.0,...,-5962.145110,0.500000,2334.384858,0,,,,,0.059707,9
18,FA(18:1)_<>_n-9,11.654217,537.0,20,14,01162025_CisTransMix_AMP_OzoneOn_01,339.3 -> 183.0,CisTrans,339.3,183.0,...,-4948.338349,0.500000,1261.829653,0,,,,,0.044475,9
19,FA(18:1)_<>_n-9,11.844433,18940.0,20,14,01162025_CisTransMix_AMP_OzoneOn_01,339.3 -> 183.0,CisTrans,339.3,183.0,...,-206077.388208,0.636364,20346.188892,1,,,,,7.846046,9
20,FA(18:1)_<>_n-9,12.034650,987.0,20,14,01162025_CisTransMix_AMP_OzoneOn_01,339.3 -> 183.0,CisTrans,339.3,183.0,...,-6561.514196,1.000000,6435.331230,0,,,,,0.078991,9
21,FA(18:1)_<>_n-9,12.098067,640.0,20,14,01162025_CisTransMix_AMP_OzoneOn_01,339.3 -> 183.0,CisTrans,339.3,183.0,...,-11104.100946,1.000000,2082.018927,0,,,,,0.052618,9
22,FA(18:1)_<>_n-10,11.448867,2277.0,17,0,01162025_CisTransMix_AMP_OzoneOn_01,325.2 -> 183.0,CisTrans,325.2,183.0,...,-36977.791619,0.600000,16301.937810,1,,,,,0.604838,10
23,FA(18:1)_<>_n-10,11.528133,620.0,17,0,01162025_CisTransMix_AMP_OzoneOn_01,325.2 -> 183.0,CisTrans,325.2,183.0,...,-7634.069401,0.500000,6056.782334,0,,,,,0.048272,10
24,FA(18:1)_<>_n-10,11.908567,10799.0,17,0,01162025_CisTransMix_AMP_OzoneOn_01,325.2 -> 183.0,CisTrans,325.2,183.0,...,-157602.523659,1.125000,-11971.299833,1,,,,,3.657458,10
25,FA(18:1)_<>_n-10,12.098783,683.0,17,0,01162025_CisTransMix_AMP_OzoneOn_01,325.2 -> 183.0,CisTrans,325.2,183.0,...,-3722.397476,1.000000,3157.894737,0,,,,,0.150260,10
26,FA(18:1)_<>_n-11,11.560550,1724.0,14,1,01162025_CisTransMix_AMP_OzoneOn_01,311.3 -> 183.0,CisTrans,311.3,183.0,...,-19274.447950,1.400000,-246.056782,1,,,,,0.491753,11
27,FA(18:1)_<>_n-11,12.067783,6728.0,14,1,01162025_CisTransMix_AMP_OzoneOn_01,311.3 -> 183.0,CisTrans,311.3,183.0,...,-49411.764706,1.000000,7292.448661,1,,,,,3.097710,11
28,FA(18:1)_<>_n-11,12.194600,738.0,14,1,01162025_CisTransMix_AMP_OzoneOn_01,311.3 -> 183.0,CisTrans,311.3,183.0,...,-5457.413249,0.500000,820.189274,0,,,,,0.061733,11
29,FA(18:1)_<>_n-12,11.783183,523.0,11,2,01162025_CisTransMix_AMP_OzoneOn_01,297.2 -> 183.0,CisTrans,297.2,183.0,...,-1198.738170,0.611111,1165.525014,2,,,,,0.276795,12
30,FA(18:1)_<>_n-12,12.195317,1761.0,11,2,01162025_CisTransMix_AMP_OzoneOn_01,297.2 -> 183.0,CisTrans,297.2,183.0,...,4227.129338,0.500000,19558.359621,0,,,,,0.135534,12
31,FA(18:1)_<>_n-12,12.227017,1895.0,11,2,01162025_CisTransMix_AMP_OzoneOn_01,297.2 -> 183.0,CisTrans,297.2,183.0,...,-10315.457413,0.666667,2464.517845,1,,,,,1.014266,12
32,FA(18:1)_<>_n-13,12.449533,899.0,8,3,01162025_CisTransMix_AMP_OzoneOn_01,283.2 -> 183.0,CisTrans,283.2,183.0,...,-5867.507886,0.875000,2648.568625,1,,,,,0.321792,13
33,FA(18:2)_<B>_n-6,9.417133,12794.0,28,25,01162025_CisTransMix_AMP_OzoneOn_01,379.3 -> 183.0,CisTrans,379.3,183.0,...,-113862.100045,1.000000,66420.400185,1,,,,,4.217385,6
34,FA(18:2)_<B>_n-6,9.607350,502.0,28,25,01162025_CisTransMix_AMP_OzoneOn_01,379.3 -> 183.0,CisTrans,379.3,183.0,...,-3280.757098,3.000000,862.250263,1,,,,,0.076417,6
35,FA(18:2)_<F>_n-9,9.419167,14053.0,20,43,01162025_CisTransMix_AMP_OzoneOn_01,339.3 -> 183.0,CisTrans,339.3,183.0,...,-138436.048838,1.000000,64490.436786,1,,,,,4.459309,9
36,FA(18:2)_<F>_n-9,9.577683,577.0,20,43,01162025_CisTransMix_AMP_OzoneOn_01,339.3 -> 183.0,CisTrans,339.3,183.0,...,-567.823344,3.000000,715.036803,0,,,,,0.094815,9
37,FA(18:2)_<F>_n-9,9.641100,516.0,20,43,01162025_CisTransMix_AMP_OzoneOn_01,339.3 -> 183.0,CisTrans,339.3,183.0,...,-1451.104101,1.000000,129.687455,0,,,,,0.126673,9
38,FA(18:3)_<BB>_n-3,8.020133,4849.0,36,50,01162025_CisTransMix_AMP_OzoneOn_01,419.3 -> 183.0,CisTrans,419.3,183.0,...,-61110.410095,0.666667,31154.775871,0,,,,,1.588892,3
39,FA(18:3)_<FF>_n-5,7.862850,673.0,32,80,01162025_CisTransMix_AMP_OzoneOn_01,395.3 -> 183.0,CisTrans,395.3,183.0,...,-4429.022082,1.333333,701.887003,1,,,,,0.305910,5
40,FA(18:3)_<BF>_n-6,8.022200,5203.0,28,67,01162025_CisTransMix_AMP_OzoneOn_01,379.3 -> 183.0,CisTrans,379.3,183.0,...,-59674.949580,0.500000,35873.817035,0,,,,,1.132795,6
41,FA(18:3)_<FF>_n-9,8.024250,6440.0,20,84,01162025_CisTransMix_AMP_OzoneOn_01,339.3 -> 183.0,CisTrans,339.3,183.0,...,-72315.808498,0.666667,31242.902208,1,,,,,1.991653,9

In [36]:
df_analysis = pd.read_parquet('Projects/CT/analysis/ON/df_analysis_5_max_CisTrans.parquet')
df_analysis

,Lipid,group_by_lipid,Sample,Retention_Time,OzESI_Intensity,group_by_ion,Sample_ID,Transition,Parent_Ion,Product_Ion,...,Slope_Right,Asymmetry_Factor,Baseline_Drift,Shoulder_Count,Biology,Genotype,Cage,Mouse,Normalized_Peak_Area,n_value
0,FA(18:1)_<>_n-2,7,CisTrans,11.664867,919.0,41,01162025_CisTransMix_AMP_OzoneOn_01,437.4 -> 183.0,437.4,183.0,...,-4164.037855,2.000000,-1898.467511,2,,,,,0.418570,2
1,FA(18:1)_<>_n-3,8,CisTrans,11.665717,1452.0,38,01162025_CisTransMix_AMP_OzoneOn_01,423.3 -> 183.0,423.3,183.0,...,-6529.968454,2.000000,1576.688517,1,,,,,0.635683,3
2,FA(18:1)_<>_n-4,9,CisTrans,11.698150,2496.0,35,01162025_CisTransMix_AMP_OzoneOn_01,409.3 -> 183.0,409.3,183.0,...,-23343.848580,1.272727,815.201637,1,,,,,1.135327,4
3,FA(18:1)_<>_n-5,10,CisTrans,11.683033,7761.0,32,01162025_CisTransMix_AMP_OzoneOn_01,395.3 -> 183.0,395.3,183.0,...,-27634.069401,1.125000,19531.115572,1,,,,,2.640291,5
4,FA(18:1)_<>_n-6,11,CisTrans,11.667900,10163.0,29,01162025_CisTransMix_AMP_OzoneOn_01,381.3 -> 183.0,381.3,183.0,...,-72597.408479,1.500000,-2882.844629,1,,,,,4.060775,6
5,FA(18:1)_<>_n-7,12,CisTrans,11.700333,15396.0,26,01162025_CisTransMix_AMP_OzoneOn_01,367.3 -> 183.0,367.3,183.0,...,-145993.690852,1.750000,-25656.545741,1,,,,,6.321263,7
6,FA(18:1)_<>_n-8,13,CisTrans,11.748617,21766.0,23,01162025_CisTransMix_AMP_OzoneOn_01,353.3 -> 183.0,353.3,183.0,...,-137539.432177,1.300000,-24011.333141,1,,,,,8.857493,8
7,FA(18:1)_<>_n-9,14,CisTrans,11.321350,32542.0,20,01162025_CisTransMix_AMP_OzoneOn_01,339.3 -> 183.0,339.3,183.0,...,-274664.263182,1.400000,74469.815360,1,,,,,12.492208,9
8,FA(18:1)_<>_n-10,0,CisTrans,11.908567,10799.0,17,01162025_CisTransMix_AMP_OzoneOn_01,325.2 -> 183.0,325.2,183.0,...,-157602.523659,1.125000,-11971.299833,1,,,,,3.657458,10
9,FA(18:1)_<>_n-11,1,CisTrans,12.067783,6728.0,14,01162025_CisTransMix_AMP_OzoneOn_01,311.3 -> 183.0,311.3,183.0,...,-49411.764706,1.000000,7292.448661,1,,,,,3.097710,11
10,FA(18:1)_<>_n-12,2,CisTrans,12.227017,1895.0,11,01162025_CisTransMix_AMP_OzoneOn_01,297.2 -> 183.0,297.2,183.0,...,-10315.457413,0.666667,2464.517845,1,,,,,1.014266,12
11,FA(18:1)_<>_n-13,3,CisTrans,12.449533,899.0,8,01162025_CisTransMix_AMP_OzoneOn_01,283.2 -> 183.0,283.2,183.0,...,-5867.507886,0.875000,2648.568625,1,,,,,0.321792,13
12,FA(18:2)_<B>_n-6,25,CisTrans,9.417133,12794.0,28,01162025_CisTransMix_AMP_OzoneOn_01,379.3 -> 183.0,379.3,183.0,...,-113862.100045,1.000000,66420.400185,1,,,,,4.217385,6
13,FA(18:2)_<F>_n-9,43,CisTrans,9.419167,14053.0,20,01162025_CisTransMix_AMP_OzoneOn_01,339.3 -> 183.0,339.3,183.0,...,-138436.048838,1.000000,64490.436786,1,,,,,4.459309,9
14,FA(18:3)_<BB>_n-3,50,CisTrans,8.020133,4849.0,36,01162025_CisTransMix_AMP_OzoneOn_01,419.3 -> 183.0,419.3,183.0,...,-61110.410095,0.666667,31154.775871,0,,,,,1.588892,3
15,FA(18:3)_<FF>_n-5,80,CisTrans,7.862850,673.0,32,01162025_CisTransMix_AMP_OzoneOn_01,395.3 -> 183.0,395.3,183.0,...,-4429.022082,1.333333,701.887003,1,,,,,0.305910,5
16,FA(18:3)_<BF>_n-6,67,CisTrans,8.022200,5203.0,28,01162025_CisTransMix_AMP_OzoneOn_01,379.3 -> 183.0,379.3,183.0,...,-59674.949580,0.500000,35873.817035,0,,,,,1.132795,6
17,FA(18:3)_<FF>_n-9,84,CisTrans,8.024250,6440.0,20,01162025_CisTransMix_AMP_OzoneOn_01,339.3 -> 183.0,339.3,183.0,...,-72315.808498,0.666667,31242.902208,1,,,,,1.991653,9