# QTRAP Parse and Plot

# 1 - QTRAP Parse

# call python file

In [1]:
# Import the function from QTRAP.py
from QTRAP import parse_chromatogram_data

# Define input and output directories
input_dir = 'data/text/'
output_dir = 'result/'

# Parse the chromatogram data and save to a CSV
chromatogram_df = parse_chromatogram_data(input_dir, output_dir)

# Display the resulting DataFrame
chromatogram_df

,Date,Sample_Name,Sample,Blank_Group,Lipid,Q1,Q3,Intensity,Filename
0,20241115,Plasma_TG_18-3,Sample,1,"""[TG(50:9),TG(49:2)]_FA18:3""",834.76,539.46,2000,20241115_Plasma_TG_18
1,20241115,Plasma_TG_18-3,Sample,1,"""[TG(51:9),TG(50:2)]_FA18:3""",848.77,553.47,4800,20241115_Plasma_TG_18
2,20241115,Plasma_TG_18-3,Sample,1,"""[TG(52:9),TG(51:2)]_FA18:3""",862.79,567.49,800,20241115_Plasma_TG_18
3,20241115,Plasma_TG_18-3,Sample,1,"""[TG(53:9),TG(52:2)]_FA18:3""",876.80,581.50,1400,20241115_Plasma_TG_18
4,20241115,Plasma_TG_18-3,Sample,1,"""[TG(57:9),TG(56:2)]_FA18:3""",932.86,637.56,9280,20241115_Plasma_TG_18
...,...,...,...,...,...,...,...,...,...
6461,20241115,Plasma_PC,Sample,25,PC(52:0),1014.88,184.10,1160,20241115_Plasma_PC.wiff.scan
6462,20241115,Plasma_PC,Sample,25,PC(54:12),1018.73,184.10,640,20241115_Plasma_PC.wiff.scan
6463,20241115,Plasma_PC,Sample,25,PC(56:12),1046.76,184.10,640,20241115_Plasma_PC.wiff.scan
6464,20241115,Plasma_PC,Sample,25,PC(56:9),1052.80,184.10,440,20241115_Plasma_PC.wiff.scan
6465,20241115,Plasma_PC,Sample,25,PC(56:8),1054.82,184.10,1000,20241115_Plasma_PC.wiff.scan

In [2]:
#print unique Sample_Name values
print(chromatogram_df['Sample_Name'].unique())
chromatogram_df

['Plasma_TG_18-3' 'Plasma_Blank_PI' 'Plasma_FFA SFA USFA' 'Plasma_DG_18-0'
 'Plasma_DG_16-0' 'Plasma_DG_18-1' 'Plasma_TG_22-6'
 'Plasma_Blank_Acyl-Carnitines' 'Plasma_Blank_TG_14-0'
 'Plasma_Blank_DG_16-1' 'Plasma_Blank_TG_18-3' 'Plasma_Blank_TG_22-6'
 'Plasma_TG_16-1' 'Plasma_Blank_TG_22-5'
 'Plasma_Blank_Cholesteryrl Esters' 'Plasma_Blank_DG_16-0' 'Plasma_PS'
 'Plasma_Blank_PG' 'Plasma_PG' 'Plasma_Blank_TG_18-0' 'Plasma_Ceramides'
 'Plasma_TG_18-2' 'Plasma_TG_20-4' 'Plasma_Blank_TG_18-2' 'Plasma_SM'
 'Plasma_TG_22-5' 'Plasma_Blank_PS' 'Plasma_Blank_TG_18-1' 'Plasma_PI'
 'Plasma_Blank_DB_18-1-Plasma_Blank_DG_18-1' 'Plasma_Cholesteryrl Esters'
 'Plasma_Acyl-Carnitines' 'Plasma_TG_18-1' 'Plasma_Blank_TG_20-4'
 'Plasma_TG_16-0' 'Plasma_Blank_TG_16-0' 'Plasma_DG_16-1' 'Plasma_PE'
 'Plasma_Blank_DG_18-0' 'Plasma_Blank_FFA SFA USFA' 'Plasma_Blank_PC'
 'Plasma_TG_14-0' 'Plasma_Blank_TG_16-1' 'Plasma_Blank_PE'
 'Plasma_Blank_DG_18-2' 'Plasma_DG_18-2' 'Plasma_Blank_Ceramides'
 'Plasma_TG_18-0' 'Plasma_PC']

,Date,Sample_Name,Sample,Blank_Group,Lipid,Q1,Q3,Intensity,Filename
0,20241115,Plasma_TG_18-3,Sample,1,"""[TG(50:9),TG(49:2)]_FA18:3""",834.76,539.46,2000,20241115_Plasma_TG_18
1,20241115,Plasma_TG_18-3,Sample,1,"""[TG(51:9),TG(50:2)]_FA18:3""",848.77,553.47,4800,20241115_Plasma_TG_18
2,20241115,Plasma_TG_18-3,Sample,1,"""[TG(52:9),TG(51:2)]_FA18:3""",862.79,567.49,800,20241115_Plasma_TG_18
3,20241115,Plasma_TG_18-3,Sample,1,"""[TG(53:9),TG(52:2)]_FA18:3""",876.80,581.50,1400,20241115_Plasma_TG_18
4,20241115,Plasma_TG_18-3,Sample,1,"""[TG(57:9),TG(56:2)]_FA18:3""",932.86,637.56,9280,20241115_Plasma_TG_18
...,...,...,...,...,...,...,...,...,...
6461,20241115,Plasma_PC,Sample,25,PC(52:0),1014.88,184.10,1160,20241115_Plasma_PC.wiff.scan
6462,20241115,Plasma_PC,Sample,25,PC(54:12),1018.73,184.10,640,20241115_Plasma_PC.wiff.scan
6463,20241115,Plasma_PC,Sample,25,PC(56:12),1046.76,184.10,640,20241115_Plasma_PC.wiff.scan
6464,20241115,Plasma_PC,Sample,25,PC(56:9),1052.80,184.10,440,20241115_Plasma_PC.wiff.scan
6465,20241115,Plasma_PC,Sample,25,PC(56:8),1054.82,184.10,1000,20241115_Plasma_PC.wiff.scan

In [3]:
# print uniqu filename
print(chromatogram_df['Filename'].unique())

['20241115_Plasma_TG_18' '20241115_Plasma_Blank_PI.wiff.scan'
 '20241115_Plasma_FFA' '20241115_Plasma_DG_18' '20241115_Plasma_DG_16'
 '20241115_Plasma_TG_22' '20241115_Plasma_Blank_Acyl'
 '20241115_Plasma_Blank_TG_14' '20241115_Plasma_Blank_DG_16'
 '20241115_Plasma_Blank_TG_18' '20241115_Plasma_Blank_TG_22'
 '20241115_Plasma_TG_16' '20241115_Plasma_Blank_Cholesteryrl'
 '20241115_Plasma_PS.wiff.scan' '20241115_Plasma_Blank_PG.wiff.scan'
 '20241115_Plasma_PG.wiff.scan' '20241115_Plasma_Ceramides.wiff.scan'
 '20241115_Plasma_TG_20' '20241115_Plasma_SM.wiff.scan'
 '20241115_Plasma_Blank_PS.wiff.scan' '20241115_Plasma_PI.wiff.scan'
 '20241115_Plasma_Blank_DB_18' '20241115_Plasma_Cholesteryrl'
 '20241115_Plasma_Acyl' '20241115_Plasma_Blank_TG_20'
 '20241115_Plasma_Blank_TG_16' '20241115_Plasma_PE.wiff.scan'
 '20241115_Plasma_Blank_DG_18' '20241115_Plasma_Blank_FFA'
 '20241115_Plasma_Blank_PC.wiff.scan' '20241115_Plasma_TG_14'
 '20241115_Plasma_Blank_PE.wiff.scan'
 '20241115_Plasma_Blank_Ceramides.wiff.scan'
 '20241115_Plasma_PC.wiff.scan']

# 2 - QTRAP Plot

In [4]:
from QTRAP_plot import plot_lipid_intensities

# Define input CSV and output directory for plots
input_csv = 'result/parsed_chromatogram_data.csv'
output_dir = 'result/plots/'

# # Generate bar plots sorted by Lipid
# plot_lipid_intensities(input_csv, output_dir, sorting='Lipid')

# Generate bar plots sorted by Intensity
plot_lipid_intensities(input_csv, output_dir, sorting='Intensity')

Processing files:   0%|          | 0/34 [00:00<?, ?it/s]

Plot saved: result/plots/20241115_Plasma_Acyl/20241115_Plasma_Acyl_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Acyl/20241115_Plasma_Acyl_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Acyl/20241115_Plasma_Acyl_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Acyl/20241115_Plasma_Acyl_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Acyl/20241115_Plasma_Acyl_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Acyl/20241115_Plasma_Acyl_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Acyl/20241115_Plasma_Acyl_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Acyl/20241115_Plasma_Acyl_chunk_8_lipid_intensities.png

Processing files:   3%|▎         | 1/34 [00:02<01:06,  2.01s/it]

Plot saved: result/plots/20241115_Plasma_Acyl/20241115_Plasma_Acyl_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Acyl/20241115_Plasma_Blank_Acyl_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Acyl/20241115_Plasma_Blank_Acyl_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Acyl/20241115_Plasma_Blank_Acyl_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Acyl/20241115_Plasma_Blank_Acyl_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Acyl/20241115_Plasma_Blank_Acyl_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Acyl/20241115_Plasma_Blank_Acyl_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Acyl/20241115_Plasma_Blank_Acyl_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Acyl/20241115_Plasma_Blank_Acyl_chunk_8_lipid_intensities.png

Processing files:   6%|▌         | 2/34 [00:02<00:43,  1.36s/it]

Plot saved: result/plots/20241115_Plasma_Blank_Acyl/20241115_Plasma_Blank_Acyl_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Ceramides.wiff.scan/20241115_Plasma_Blank_Ceramides.wiff.scan_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Ceramides.wiff.scan/20241115_Plasma_Blank_Ceramides.wiff.scan_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Ceramides.wiff.scan/20241115_Plasma_Blank_Ceramides.wiff.scan_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Ceramides.wiff.scan/20241115_Plasma_Blank_Ceramides.wiff.scan_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Ceramides.wiff.scan/20241115_Plasma_Blank_Ceramides.wiff.scan_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Ceramides.wiff.scan/20241115_Plasma_Blank_Ceramides.wiff.scan_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Ceramides.wiff.scan/20241115_Plasma_Blank_Ceramides.wiff.scan_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Ceramides.wiff.scan/20241115_Plasma_Blank_Ceramides.wiff.scan_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Ceramides.wiff.scan/20241115_Plasma_Blank_Ceramides.wiff.scan_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Ceramides.wiff.scan/20241115_Plasma_Blank_Ceramides.wiff.scan_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Ceramides.wiff.scan/20241115_Plasma_Blank_Ceramides.wiff.scan_chunk_11_lipid_intensities.png

Processing files:   9%|▉         | 3/34 [00:04<00:42,  1.36s/it]

Plot saved: result/plots/20241115_Plasma_Blank_Ceramides.wiff.scan/20241115_Plasma_Blank_Ceramides.wiff.scan_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Cholesteryrl/20241115_Plasma_Blank_Cholesteryrl_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Cholesteryrl/20241115_Plasma_Blank_Cholesteryrl_chunk_2_lipid_intensities.png

Processing files:  12%|█▏        | 4/34 [00:04<00:28,  1.04it/s]

Plot saved: result/plots/20241115_Plasma_Blank_Cholesteryrl/20241115_Plasma_Blank_Cholesteryrl_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_Cholesteryrl/20241115_Plasma_Blank_Cholesteryrl_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DB_18/20241115_Plasma_Blank_DB_18_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DB_18/20241115_Plasma_Blank_DB_18_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DB_18/20241115_Plasma_Blank_DB_18_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DB_18/20241115_Plasma_Blank_DB_18_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DB_18/20241115_Plasma_Blank_DB_18_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DB_18/20241115_Plasma_Blank_DB_18_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DB_18/20241115_Plasma_Blank_DB_18_chunk_7_lipid_intensities.png

Processing files:  15%|█▍        | 5/34 [00:05<00:28,  1.02it/s]

Plot saved: result/plots/20241115_Plasma_Blank_DB_18/20241115_Plasma_Blank_DB_18_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DB_18/20241115_Plasma_Blank_DB_18_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DB_18/20241115_Plasma_Blank_DB_18_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_16_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_17_lipid_intensities.png

Processing files:  18%|█▊        | 6/34 [00:07<00:38,  1.36s/it]

Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_18_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_19_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_16/20241115_Plasma_Blank_DG_16_chunk_20_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_16_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_17_lipid_intensities.png

Processing files:  21%|██        | 7/34 [00:09<00:42,  1.57s/it]

Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_18_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_DG_18/20241115_Plasma_Blank_DG_18_chunk_19_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_16_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_17_lipid_intensities.png

Processing files:  24%|██▎       | 8/34 [00:11<00:43,  1.67s/it]

Plot saved: result/plots/20241115_Plasma_Blank_FFA/20241115_Plasma_Blank_FFA_chunk_18_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_15_lipid_intensities.png

Processing files:  26%|██▋       | 9/34 [00:13<00:43,  1.72s/it]

Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_16_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_17_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PC.wiff.scan/20241115_Plasma_Blank_PC.wiff.scan_chunk_18_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PE.wiff.scan/20241115_Plasma_Blank_PE.wiff.scan_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PE.wiff.scan/20241115_Plasma_Blank_PE.wiff.scan_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PE.wiff.scan/20241115_Plasma_Blank_PE.wiff.scan_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PE.wiff.scan/20241115_Plasma_Blank_PE.wiff.scan_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PE.wiff.scan/20241115_Plasma_Blank_PE.wiff.scan_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PE.wiff.scan/20241115_Plasma_Blank_PE.wiff.scan_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PE.wiff.scan/20241115_Plasma_Blank_PE.wiff.scan_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PE.wiff.scan/20241115_Plasma_Blank_PE.wiff.scan_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PE.wiff.scan/20241115_Plasma_Blank_PE.wiff.scan_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PE.wiff.scan/20241115_Plasma_Blank_PE.wiff.scan_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PE.wiff.scan/20241115_Plasma_Blank_PE.wiff.scan_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PE.wiff.scan/20241115_Plasma_Blank_PE.wiff.scan_chunk_12_lipid_intensities.png

Processing files:  29%|██▉       | 10/34 [00:15<00:41,  1.74s/it]

Plot saved: result/plots/20241115_Plasma_Blank_PE.wiff.scan/20241115_Plasma_Blank_PE.wiff.scan_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PE.wiff.scan/20241115_Plasma_Blank_PE.wiff.scan_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PE.wiff.scan/20241115_Plasma_Blank_PE.wiff.scan_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PG.wiff.scan/20241115_Plasma_Blank_PG.wiff.scan_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PG.wiff.scan/20241115_Plasma_Blank_PG.wiff.scan_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PG.wiff.scan/20241115_Plasma_Blank_PG.wiff.scan_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PG.wiff.scan/20241115_Plasma_Blank_PG.wiff.scan_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PG.wiff.scan/20241115_Plasma_Blank_PG.wiff.scan_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PG.wiff.scan/20241115_Plasma_Blank_PG.wiff.scan_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PG.wiff.scan/20241115_Plasma_Blank_PG.wiff.scan_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PG.wiff.scan/20241115_Plasma_Blank_PG.wiff.scan_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PG.wiff.scan/20241115_Plasma_Blank_PG.wiff.scan_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PG.wiff.scan/20241115_Plasma_Blank_PG.wiff.scan_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PG.wiff.scan/20241115_Plasma_Blank_PG.wiff.scan_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PG.wiff.scan/20241115_Plasma_Blank_PG.wiff.scan_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PG.wiff.scan/20241115_Plasma_Blank_PG.wiff.scan_chunk_13_lipid_intensities.png

Processing files:  32%|███▏      | 11/34 [00:16<00:37,  1.65s/it]

Plot saved: result/plots/20241115_Plasma_Blank_PG.wiff.scan/20241115_Plasma_Blank_PG.wiff.scan_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PI.wiff.scan/20241115_Plasma_Blank_PI.wiff.scan_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PI.wiff.scan/20241115_Plasma_Blank_PI.wiff.scan_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PI.wiff.scan/20241115_Plasma_Blank_PI.wiff.scan_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PI.wiff.scan/20241115_Plasma_Blank_PI.wiff.scan_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PI.wiff.scan/20241115_Plasma_Blank_PI.wiff.scan_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PI.wiff.scan/20241115_Plasma_Blank_PI.wiff.scan_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PI.wiff.scan/20241115_Plasma_Blank_PI.wiff.scan_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PI.wiff.scan/20241115_Plasma_Blank_PI.wiff.scan_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PI.wiff.scan/20241115_Plasma_Blank_PI.wiff.scan_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PI.wiff.scan/20241115_Plasma_Blank_PI.wiff.scan_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PI.wiff.scan/20241115_Plasma_Blank_PI.wiff.scan_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PI.wiff.scan/20241115_Plasma_Blank_PI.wiff.scan_chunk_12_lipid_intensities.png

Processing files:  35%|███▌      | 12/34 [00:18<00:35,  1.60s/it]

Plot saved: result/plots/20241115_Plasma_Blank_PI.wiff.scan/20241115_Plasma_Blank_PI.wiff.scan_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PI.wiff.scan/20241115_Plasma_Blank_PI.wiff.scan_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PI.wiff.scan/20241115_Plasma_Blank_PI.wiff.scan_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PS.wiff.scan/20241115_Plasma_Blank_PS.wiff.scan_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PS.wiff.scan/20241115_Plasma_Blank_PS.wiff.scan_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PS.wiff.scan/20241115_Plasma_Blank_PS.wiff.scan_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PS.wiff.scan/20241115_Plasma_Blank_PS.wiff.scan_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PS.wiff.scan/20241115_Plasma_Blank_PS.wiff.scan_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PS.wiff.scan/20241115_Plasma_Blank_PS.wiff.scan_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PS.wiff.scan/20241115_Plasma_Blank_PS.wiff.scan_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PS.wiff.scan/20241115_Plasma_Blank_PS.wiff.scan_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PS.wiff.scan/20241115_Plasma_Blank_PS.wiff.scan_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PS.wiff.scan/20241115_Plasma_Blank_PS.wiff.scan_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PS.wiff.scan/20241115_Plasma_Blank_PS.wiff.scan_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PS.wiff.scan/20241115_Plasma_Blank_PS.wiff.scan_chunk_12_lipid_intensities.png

Processing files:  38%|███▊      | 13/34 [00:19<00:33,  1.60s/it]

Plot saved: result/plots/20241115_Plasma_Blank_PS.wiff.scan/20241115_Plasma_Blank_PS.wiff.scan_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_PS.wiff.scan/20241115_Plasma_Blank_PS.wiff.scan_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_16_lipid_intensities.png

Processing files:  41%|████      | 14/34 [00:21<00:34,  1.71s/it]

Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_17_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_18_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_14/20241115_Plasma_Blank_TG_14_chunk_19_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_16_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_17_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_18_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_19_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_20_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_21_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_22_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_23_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_24_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_25_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_26_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_27_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_28_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_29_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_30_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_31_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_32_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_33_lipid_intensities.png

Processing files:  44%|████▍     | 15/34 [00:25<00:45,  2.42s/it]

Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_34_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_16/20241115_Plasma_Blank_TG_16_chunk_35_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_16_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_17_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_18_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_19_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_20_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_21_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_22_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_23_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_24_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_25_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_26_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_27_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_28_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_29_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_30_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_31_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_32_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_33_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_34_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_35_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_36_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_37_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_38_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_39_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_40_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_41_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_42_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_43_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_44_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_45_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_46_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_47_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_48_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_49_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_50_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_51_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_52_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_53_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_54_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_55_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_56_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_57_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_58_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_59_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_60_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_61_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_62_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_63_lipid_intensities.png

Processing files:  47%|████▋     | 16/34 [00:33<01:10,  3.91s/it]

Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_64_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_65_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_18/20241115_Plasma_Blank_TG_18_chunk_66_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_20/20241115_Plasma_Blank_TG_20_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_20/20241115_Plasma_Blank_TG_20_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_20/20241115_Plasma_Blank_TG_20_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_20/20241115_Plasma_Blank_TG_20_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_20/20241115_Plasma_Blank_TG_20_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_20/20241115_Plasma_Blank_TG_20_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_20/20241115_Plasma_Blank_TG_20_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_20/20241115_Plasma_Blank_TG_20_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_20/20241115_Plasma_Blank_TG_20_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_20/20241115_Plasma_Blank_TG_20_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_20/20241115_Plasma_Blank_TG_20_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_20/20241115_Plasma_Blank_TG_20_chunk_12_lipid_intensities.png

Processing files:  50%|█████     | 17/34 [00:34<00:54,  3.18s/it]

Plot saved: result/plots/20241115_Plasma_Blank_TG_20/20241115_Plasma_Blank_TG_20_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_20/20241115_Plasma_Blank_TG_20_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_16_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_17_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_18_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_19_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_20_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_21_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_22_lipid_intensities.png

Processing files:  53%|█████▎    | 18/34 [00:37<00:48,  3.02s/it]

Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_23_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_24_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Blank_TG_22/20241115_Plasma_Blank_TG_22_chunk_25_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Ceramides.wiff.scan/20241115_Plasma_Ceramides.wiff.scan_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Ceramides.wiff.scan/20241115_Plasma_Ceramides.wiff.scan_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Ceramides.wiff.scan/20241115_Plasma_Ceramides.wiff.scan_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Ceramides.wiff.scan/20241115_Plasma_Ceramides.wiff.scan_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Ceramides.wiff.scan/20241115_Plasma_Ceramides.wiff.scan_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Ceramides.wiff.scan/20241115_Plasma_Ceramides.wiff.scan_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Ceramides.wiff.scan/20241115_Plasma_Ceramides.wiff.scan_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Ceramides.wiff.scan/20241115_Plasma_Ceramides.wiff.scan_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Ceramides.wiff.scan/20241115_Plasma_Ceramides.wiff.scan_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Ceramides.wiff.scan/20241115_Plasma_Ceramides.wiff.scan_chunk_10_lipid_intensities.png

Processing files:  56%|█████▌    | 19/34 [00:38<00:37,  2.49s/it]

Plot saved: result/plots/20241115_Plasma_Ceramides.wiff.scan/20241115_Plasma_Ceramides.wiff.scan_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Ceramides.wiff.scan/20241115_Plasma_Ceramides.wiff.scan_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Cholesteryrl/20241115_Plasma_Cholesteryrl_chunk_1_lipid_intensities.png

Processing files:  59%|█████▉    | 20/34 [00:38<00:25,  1.85s/it]

Plot saved: result/plots/20241115_Plasma_Cholesteryrl/20241115_Plasma_Cholesteryrl_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Cholesteryrl/20241115_Plasma_Cholesteryrl_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_Cholesteryrl/20241115_Plasma_Cholesteryrl_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_16_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_17_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_18_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_19_lipid_intensities.png

Processing files:  62%|██████▏   | 21/34 [00:41<00:26,  2.06s/it]

Plot saved: result/plots/20241115_Plasma_DG_16/20241115_Plasma_DG_16_chunk_20_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_16_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_17_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_18_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_19_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_20_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_21_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_22_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_23_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_24_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_25_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_26_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_27_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_28_lipid_intensities.png

Processing files:  65%|██████▍   | 22/34 [00:44<00:27,  2.33s/it]

Plot saved: result/plots/20241115_Plasma_DG_18/20241115_Plasma_DG_18_chunk_29_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_16_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_17_lipid_intensities.png

Processing files:  68%|██████▊   | 23/34 [00:46<00:23,  2.13s/it]

Plot saved: result/plots/20241115_Plasma_FFA/20241115_Plasma_FFA_chunk_18_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_15_lipid_intensities.png

Processing files:  71%|███████   | 24/34 [00:47<00:20,  2.05s/it]

Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_16_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_17_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PC.wiff.scan/20241115_Plasma_PC.wiff.scan_chunk_18_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PE.wiff.scan/20241115_Plasma_PE.wiff.scan_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PE.wiff.scan/20241115_Plasma_PE.wiff.scan_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PE.wiff.scan/20241115_Plasma_PE.wiff.scan_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PE.wiff.scan/20241115_Plasma_PE.wiff.scan_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PE.wiff.scan/20241115_Plasma_PE.wiff.scan_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PE.wiff.scan/20241115_Plasma_PE.wiff.scan_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PE.wiff.scan/20241115_Plasma_PE.wiff.scan_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PE.wiff.scan/20241115_Plasma_PE.wiff.scan_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PE.wiff.scan/20241115_Plasma_PE.wiff.scan_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PE.wiff.scan/20241115_Plasma_PE.wiff.scan_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PE.wiff.scan/20241115_Plasma_PE.wiff.scan_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PE.wiff.scan/20241115_Plasma_PE.wiff.scan_chunk_12_lipid_intensities.png

Processing files:  74%|███████▎  | 25/34 [00:49<00:17,  1.89s/it]

Plot saved: result/plots/20241115_Plasma_PE.wiff.scan/20241115_Plasma_PE.wiff.scan_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PE.wiff.scan/20241115_Plasma_PE.wiff.scan_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PE.wiff.scan/20241115_Plasma_PE.wiff.scan_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PG.wiff.scan/20241115_Plasma_PG.wiff.scan_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PG.wiff.scan/20241115_Plasma_PG.wiff.scan_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PG.wiff.scan/20241115_Plasma_PG.wiff.scan_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PG.wiff.scan/20241115_Plasma_PG.wiff.scan_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PG.wiff.scan/20241115_Plasma_PG.wiff.scan_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PG.wiff.scan/20241115_Plasma_PG.wiff.scan_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PG.wiff.scan/20241115_Plasma_PG.wiff.scan_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PG.wiff.scan/20241115_Plasma_PG.wiff.scan_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PG.wiff.scan/20241115_Plasma_PG.wiff.scan_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PG.wiff.scan/20241115_Plasma_PG.wiff.scan_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PG.wiff.scan/20241115_Plasma_PG.wiff.scan_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PG.wiff.scan/20241115_Plasma_PG.wiff.scan_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PG.wiff.scan/20241115_Plasma_PG.wiff.scan_chunk_13_lipid_intensities.png

Processing files:  76%|███████▋  | 26/34 [00:50<00:14,  1.76s/it]

Plot saved: result/plots/20241115_Plasma_PG.wiff.scan/20241115_Plasma_PG.wiff.scan_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PI.wiff.scan/20241115_Plasma_PI.wiff.scan_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PI.wiff.scan/20241115_Plasma_PI.wiff.scan_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PI.wiff.scan/20241115_Plasma_PI.wiff.scan_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PI.wiff.scan/20241115_Plasma_PI.wiff.scan_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PI.wiff.scan/20241115_Plasma_PI.wiff.scan_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PI.wiff.scan/20241115_Plasma_PI.wiff.scan_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PI.wiff.scan/20241115_Plasma_PI.wiff.scan_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PI.wiff.scan/20241115_Plasma_PI.wiff.scan_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PI.wiff.scan/20241115_Plasma_PI.wiff.scan_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PI.wiff.scan/20241115_Plasma_PI.wiff.scan_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PI.wiff.scan/20241115_Plasma_PI.wiff.scan_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PI.wiff.scan/20241115_Plasma_PI.wiff.scan_chunk_12_lipid_intensities.png

Processing files:  79%|███████▉  | 27/34 [00:53<00:13,  1.89s/it]

Plot saved: result/plots/20241115_Plasma_PI.wiff.scan/20241115_Plasma_PI.wiff.scan_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PI.wiff.scan/20241115_Plasma_PI.wiff.scan_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PI.wiff.scan/20241115_Plasma_PI.wiff.scan_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PS.wiff.scan/20241115_Plasma_PS.wiff.scan_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PS.wiff.scan/20241115_Plasma_PS.wiff.scan_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PS.wiff.scan/20241115_Plasma_PS.wiff.scan_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PS.wiff.scan/20241115_Plasma_PS.wiff.scan_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PS.wiff.scan/20241115_Plasma_PS.wiff.scan_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PS.wiff.scan/20241115_Plasma_PS.wiff.scan_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PS.wiff.scan/20241115_Plasma_PS.wiff.scan_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PS.wiff.scan/20241115_Plasma_PS.wiff.scan_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PS.wiff.scan/20241115_Plasma_PS.wiff.scan_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PS.wiff.scan/20241115_Plasma_PS.wiff.scan_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PS.wiff.scan/20241115_Plasma_PS.wiff.scan_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PS.wiff.scan/20241115_Plasma_PS.wiff.scan_chunk_12_lipid_intensities.png

Processing files:  82%|████████▏ | 28/34 [00:54<00:10,  1.73s/it]

Plot saved: result/plots/20241115_Plasma_PS.wiff.scan/20241115_Plasma_PS.wiff.scan_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_PS.wiff.scan/20241115_Plasma_PS.wiff.scan_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_SM.wiff.scan/20241115_Plasma_SM.wiff.scan_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_SM.wiff.scan/20241115_Plasma_SM.wiff.scan_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_SM.wiff.scan/20241115_Plasma_SM.wiff.scan_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_SM.wiff.scan/20241115_Plasma_SM.wiff.scan_chunk_4_lipid_intensities.png

Processing files:  85%|████████▌ | 29/34 [00:54<00:06,  1.35s/it]

Plot saved: result/plots/20241115_Plasma_SM.wiff.scan/20241115_Plasma_SM.wiff.scan_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_16_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_17_lipid_intensities.png

Processing files:  88%|████████▊ | 30/34 [00:56<00:06,  1.53s/it]

Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_18_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_14/20241115_Plasma_TG_14_chunk_19_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_16_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_17_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_18_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_19_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_20_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_21_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_22_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_23_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_24_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_25_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_26_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_27_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_28_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_29_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_30_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_31_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_32_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_33_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_34_lipid_intensities.png

Processing files:  91%|█████████ | 31/34 [01:00<00:06,  2.18s/it]

Plot saved: result/plots/20241115_Plasma_TG_16/20241115_Plasma_TG_16_chunk_35_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_16_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_17_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_18_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_19_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_20_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_21_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_22_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_23_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_24_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_25_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_26_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_27_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_28_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_29_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_30_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_31_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_32_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_33_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_34_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_35_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_36_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_37_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_38_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_39_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_40_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_41_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_42_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_43_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_44_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_45_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_46_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_47_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_48_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_49_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_50_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_51_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_52_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_53_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_54_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_55_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_56_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_57_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_58_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_59_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_60_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_61_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_62_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_63_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_64_lipid_intensities.png

Processing files:  94%|█████████▍| 32/34 [01:08<00:07,  3.85s/it]

Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_65_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_18/20241115_Plasma_TG_18_chunk_66_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_20/20241115_Plasma_TG_20_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_20/20241115_Plasma_TG_20_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_20/20241115_Plasma_TG_20_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_20/20241115_Plasma_TG_20_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_20/20241115_Plasma_TG_20_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_20/20241115_Plasma_TG_20_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_20/20241115_Plasma_TG_20_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_20/20241115_Plasma_TG_20_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_20/20241115_Plasma_TG_20_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_20/20241115_Plasma_TG_20_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_20/20241115_Plasma_TG_20_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_20/20241115_Plasma_TG_20_chunk_12_lipid_intensities.png

Processing files:  97%|█████████▋| 33/34 [01:09<00:03,  3.14s/it]

Plot saved: result/plots/20241115_Plasma_TG_20/20241115_Plasma_TG_20_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_20/20241115_Plasma_TG_20_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_1_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_2_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_3_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_4_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_5_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_6_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_7_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_8_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_9_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_10_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_11_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_12_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_13_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_14_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_15_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_16_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_17_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_18_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_19_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_20_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_21_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_22_lipid_intensities.png

Processing files: 100%|██████████| 34/34 [01:12<00:00,  2.13s/it]

Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_23_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_24_lipid_intensities.png
Plot saved: result/plots/20241115_Plasma_TG_22/20241115_Plasma_TG_22_chunk_25_lipid_intensities.png

['20241023_PlasmaExtract11.wiff.scan' '20241023_Blank31.wiff.scan'
 '20241023_PlasmaExtract13.wiff.scan' '20241023_PlasmaExtract8.wiff.scan'
 '20241023_PlasmaExtract14.wiff.scan' '20241023_PlasmaExtract4.wiff.scan'
 '20241023_PlasmaExtract3.wiff.scan' '20241023_PlasmaExtract12.wiff.scan'
 '20241023_PlasmaExtract21.wiff.scan' '20241023_PlasmaExtract24.wiff.scan'
 '20241023_PlasmaExtract16.wiff.scan' '20241023_PlasmaExtract20.wiff.scan'
 '20241023_PlasmaExtract17.wiff.scan' '20241023_PlasmaExtract23.wiff.scan'
 '20241023_PlasmaExtract15.wiff.scan' '20241023_PlasmaExtract10.wiff.scan'
 '20241023_PlasmaExtract25.wiff.scan' '20241023_PlasmaExtract19.wiff.scan'
 '20241023_PlasmaExtract5.wiff.scan' '20241023_PlasmaExtract18.wiff.scan'
 '20241023_Blank34.wiff.scan' '20241023_PlasmaExtract2.wiff.scan'
 '20241023_Blank33.wiff.scan' '20241023_PlasmaExtract9.wiff.scan'
 '20241023_Blank32.wiff.scan' '20241023_PlasmaExtract1.wiff.scan'
 '20241023_Blank35.wiff.scan' '20241023_PlasmaExtract7.wiff.scan'
 '20241023_PlasmaExtract22.wiff.scan' '20241023_PlasmaExtract6.wiff.scan']